pq-code-package/mlkem-native

.astylerc
=> Add astyle

mlkem/LICENSE, mlkem/api.h, mlkem/cbd.c, mlkem/cbd.h, mlkem/indcpa.c, mlkem/indcpa.h, mlkem/kem.c, mlkem/kem.h, mlkem/ntt.c, mlkem/ntt.h, mlkem/params.h, mlkem/poly.c, mlkem/poly.h, mlkem/polyvec.c, mlkem/polyvec.h, mlkem/reduce.c, mlkem/reduce.h, mlkem/symmetric-shake.c, mlkem/symmetric.h, mlkem/verify.c, mlkem/verify.h
This MLKEM reference code is taken directly from Kyber standard branch https://github.com/pq-crystals/kyber/tree/11d00ff1f20cfca1f72d819e5a45165c1e0a2816
with Kyber 90s variants and KEX removed.
=> Add MLKEM C reference code

randombytes/randombytes.c, randombytes/randombytes.h
=> Add randombytes

fips202/LICENSE, fips202/fips202.c, fips202/fips202.h, fips202/keccakf1600.c, fips202/keccakf1600.h
This FIPS202 follow the same idea of mlkem-c-embbedded.
This is for further optimization directly at keccakf1600 function.
=> Add FIPS202

fips202/fips202.c, fips202/keccakf1600.c, fips202/keccakf1600.h, mlkem/cbd.c, mlkem/cbd.h, mlkem/indcpa.c, mlkem/kem.c, mlkem/ntt.c, mlkem/params.h, mlkem/poly.c, mlkem/poly.h, mlkem/polyvec.c, mlkem/polyvec.h, mlkem/reduce.c, mlkem/symmetric-shake.c, mlkem/verify.c, randombytes/randombytes.c
=> Format the code base with Astyle

.github/workflows/ci.yml, Makefile, arm-gnu-gcc.nix, flake.nix
Made x86-64 linux machine to use the pre-built corss-compile aarch64 gcc
Added x86-64 linux GitHub runner, it will only cross compile the project, emulation on qemu will be done in other PR
- **add arm gnu gcc nix spec for x86_64**
- **use the pre-built cross-compiled gcc for x86_64 machines in ci**
=> Use pre-built cross-compiled aarch64 gcc for x86-64 linux machine

.github/workflows/bench_ec2_reusable.yml
Update github action to latest.
=> Update configure-aws-credentials to latest

Makefile, mk/bench.mk, mk/config.mk, mk/crypto.mk, mk/nistkat.mk
=> Fix variable detection of recursive make

.github/actions/bench/action.yml, .github/actions/cbmc/action.yml, .github/actions/functest/action.yml, .github/actions/lint/action.yml, .github/workflows/bench.yml, .github/workflows/bench_ec2_all.yml, .github/workflows/bench_ec2_any.yml, .github/workflows/bench_ec2_reusable.yml, .github/workflows/ci_ec2_any.yml, .github/workflows/ci_ec2_reusable.yml
=> Make AMI ID dropdown

.github/actions/bench/action.yml, .github/actions/functest/action.yml, .github/workflows/bench_ec2_all.yml, .github/workflows/bench_ec2_any.yml, .github/workflows/bench_ec2_reusable.yml, .github/workflows/ci.yml, .github/workflows/ci_ec2_any.yml, .github/workflows/ci_ec2_reusable.yml
Make running opt/non-opt code in CI configurable
=> Run opt/non-opt in CI

.github/workflows/ci_ec2_any.yml
=> Fix name propagation in manually triggered CI workflow

.github/actions/bench/action.yml
=> Fix string vs. boolean in store_results argument to bench action

fips202/asm/aarch64/common.i, fips202/asm/aarch64/keccak_f1600_x2_v48a_clean.S, fips202/asm/asm.h, fips202/fips202x4.c, fips202/fips202x4.h, fips202/keccakf1600.c, fips202/keccakf1600.h, mlkem/asm/aarch64/common.i, mlkem/indcpa.c, mlkem/symmetric-shake.c, mlkem/symmetric.h, mlkem/sys/cpucap.h
This PR makes various preparations towards using an interleaved batched Keccak state. See individual commits.
=> Add batched Keccak ASM

cbmc/0001-Do-not-download-sources-in-cmake.patch, cbmc/default.nix, cbmc/proofs/Makefile.common, flake.nix
Copy of @rod-chapman's original PR #148. Because of #149 we have to open the PR from the main repo.
=> Update cbmc 6.3.1

cbmc/default.nix, cbmc/proofs/poly_decompress/Makefile, cbmc/proofs/poly_decompress/poly_decompress_harness.c, mlkem/poly.c, mlkem/poly.h
Re-opening #161 on the main repo to run CI.
=> Prove poly decompress

.github/workflows/bench.yml
=> Add Graviton4 benchmarks to CI

.github/workflows/ci_ec2_reusable.yml
Seemed to found a way to fix https://github.com/pq-code-package/mlkem-c-aarch64/issues/155 by using matrix exclude
=> Fix CI skipped job

fips202/keccakf1600.h, fips202/native/fips202_native.h, fips202/native/x86_64/fips202_native_x86_64.h, fips202/native/x86_64/profiles/xkcp.h, fips202/native/x86_64/xkcp/KeccakP-1600-times4-SIMD256.c, fips202/native/x86_64/xkcp/KeccakP-1600-times4-SnP.h, fips202/native/x86_64/xkcp/KeccakP-1600-unrolling.macros, fips202/native/x86_64/xkcp/KeccakP-SIMD256-config.h, fips202/native/x86_64/xkcp/KeccakP-align.h, fips202/native/x86_64/xkcp/KeccakP-brg_endian.h, mk/crypto.mk
Add AVX2 code for Keccak-f1600-x4 from XKCP / Kyber official repository.
Based on #219
=> Add AVX2 Keccak-x4 from XKCP

mlkem/native/aarch64/arith_native_aarch64.h, mlkem/native/aarch64/polyvec_clean.S, mlkem/native/aarch64/polyvec_opt.S, mlkem/native/aarch64/profiles/clean.h, mlkem/native/aarch64/profiles/opt.h, test/bench_components_mlkem.c
=> AArch64: Simplify polyvec_basemul_acc_montgomery interface 

cbmc/proofs/poly_frombytes/Makefile, cbmc/proofs/poly_frombytes/cbmc-proof.txt, cbmc/proofs/poly_frombytes/poly_frombytes_harness.c, mlkem/poly.c, mlkem/poly.h
=> CBMC: Add spec & proof for `poly_frombytes()`

cbmc/proofs/basemul_cached/Makefile, cbmc/proofs/basemul_cached/basemul_cached_harness.c, cbmc/proofs/basemul_cached/cbmc-proof.txt, cbmc/proofs/poly_mulcache_compute/Makefile, cbmc/proofs/poly_mulcache_compute/cbmc-proof.txt, cbmc/proofs/poly_mulcache_compute/poly_mulcache_compute_harness.c, cbmc/proofs/polyvec_mulcache_compute/Makefile, cbmc/proofs/polyvec_mulcache_compute/cbmc-proof.txt, cbmc/proofs/polyvec_mulcache_compute/polyvec_mulcache_compute_harness.c, mlkem/ntt.h, mlkem/poly.c, mlkem/poly.h, mlkem/polyvec.h
* `basemul_cached()`: Fixes #281
* `poly_mulcache_compute` and `polyvec_mulcache_compute`: Fixes #284 
=> CBMC: Add various simple specs and proofs

cbmc/proofs/poly_basemul_montgomery_cached/Makefile, cbmc/proofs/poly_basemul_montgomery_cached/cbmc-proof.txt, cbmc/proofs/poly_basemul_montgomery_cached/poly_basemul_montgomery_cached_harness.c, mlkem/ntt.h, mlkem/poly.c, mlkem/poly.h
=> Add spec + proof for poly_basemul_montgomery_cached()

.github/workflows/bench_ec2_reusable.yml, .github/workflows/ci_ec2_reusable.yml, .github/workflows/scorecard.yaml
This updates the github action dependencies to the most recent versions:
- #294
- #295 
- #296 
- #297
=> Update Github Action dependencies

cbmc/proofs/poly_reduce/Makefile, cbmc/proofs/poly_reduce/cbmc-proof.txt, cbmc/proofs/poly_reduce/poly_reduce_harness.c, mlkem/poly.c, mlkem/poly.h
=> CBMC: add spec + proof of poly_reduce

cbmc/proofs/rej_uniform/Makefile, cbmc/proofs/rej_uniform/cbmc-proof.txt, cbmc/proofs/rej_uniform/rej_uniform_harness.c, mlkem/cbmc.h, mlkem/rej_uniform.c, mlkem/rej_uniform.h
=> CBMC: Add spec + proof for rej_uniform

cbmc/proofs/Makefile_params.common, cbmc/proofs/poly_getnoise_eta1122_4x/Makefile, cbmc/proofs/poly_getnoise_eta1122_4x/cbmc-proof.txt, cbmc/proofs/poly_getnoise_eta1122_4x/poly_getnoise_eta1122_4x_harness.c, cbmc/proofs/poly_getnoise_eta1_4x/Makefile, cbmc/proofs/poly_getnoise_eta1_4x/cbmc-proof.txt, cbmc/proofs/poly_getnoise_eta1_4x/poly_getnoise_eta1_4x_harness.c, cbmc/proofs/poly_getnoise_eta2/Makefile, cbmc/proofs/poly_getnoise_eta2/cbmc-proof.txt, cbmc/proofs/poly_getnoise_eta2/poly_getnoise_eta2_harness.c, cbmc/proofs/poly_getnoise_eta2_4x/Makefile, cbmc/proofs/poly_getnoise_eta2_4x/cbmc-proof.txt, cbmc/proofs/poly_getnoise_eta2_4x/poly_getnoise_eta2_4x_harness.c, fips202/fips202.h, fips202/fips202x4.h, mlkem/cbmc.h, mlkem/poly.c, mlkem/poly.h, mlkem/symmetric.h
Resolves #310 
Based on #313 
Noteworthy: This PR _axiomatizes_ the behaviour of `shake256x4` and `mlkem_sha256_prf` until we have proof.
=> CBMC: Add specs and proofs for poly_getnoise_xxx

cbmc/proofs/poly_tomont/Makefile, cbmc/proofs/poly_tomont/cbmc-proof.txt, cbmc/proofs/poly_tomont/poly_tomont_harness.c, mlkem/poly.c, mlkem/poly.h
This is my first attempt at adding a CBMC proof follwing the excellent guide by @rod-chapman in #246. 
Please have a look. 
Resolves #305.
=> CBMC: add spec + proof of poly_tomont

cbmc/proofs/polyvec_add/Makefile, cbmc/proofs/polyvec_add/cbmc-proof.txt, cbmc/proofs/polyvec_add/polyvec_add_harness.c, mlkem/poly.h, mlkem/polyvec.c, mlkem/polyvec.h
=> CBMC: Add spec + proof for polyvec_add

cbmc/proofs/poly_tomsg/Makefile, cbmc/proofs/poly_tomsg/cbmc-proof.txt, cbmc/proofs/poly_tomsg/poly_tomsg_harness.c, mlkem/poly.c, mlkem/poly.h
Fixes #328 
Adds contracts and proof artefacts for poly_tomsg()
=> Proof of poly_tomsg()

cbmc/proofs/gen_matrix/Makefile, cbmc/proofs/gen_matrix/cbmc-proof.txt, cbmc/proofs/gen_matrix/gen_matrix_harness.c, cbmc/proofs/gen_matrix_entry_x4/Makefile, cbmc/proofs/gen_matrix_entry_x4/cbmc-proof.txt, cbmc/proofs/gen_matrix_entry_x4/gen_matrix_entry_x4_harness.c, fips202/fips202x4.h, mlkem/indcpa.c, mlkem/indcpa.h
Much harder than anticipated. See the individual commit messages for detailed descriptions of the pre-work that had to happen.
- Resolves #327 
- Resolves #322
=> CBMC: Add spec + proof for gen_matrix_entry_x4 and gen_matrix

cbmc/proofs/pack_sk/Makefile, cbmc/proofs/pack_sk/cbmc-proof.txt, cbmc/proofs/pack_sk/pack_sk_harness.c, cbmc/proofs/unpack_sk/Makefile, cbmc/proofs/unpack_sk/cbmc-proof.txt, cbmc/proofs/unpack_sk/unpack_sk_harness.c, mlkem/indcpa.c
=> CBMC: Spec + proof `pack_sk` and `unpack_sk`

scripts/lib/mlkem_test.py, scripts/lib/util.py
- fix `tests all` return code
- log to stdout so that goup logging in GH can work
=> Fix tests error handling and logging output file

cbmc/default.nix
=> Update CBMC to 6.4.0

cbmc/proofs/indcpa_enc/Makefile, cbmc/proofs/indcpa_enc/cbmc-proof.txt, cbmc/proofs/indcpa_enc/indcpa_enc_harness.c, mlkem/indcpa.h, mlkem/poly.h
=> CBMC: Prove `indcpa enc`

cbmc/proofs/indcpa_dec/Makefile, cbmc/proofs/indcpa_dec/cbmc-proof.txt, cbmc/proofs/indcpa_dec/indcpa_dec_harness.c, cbmc/proofs/unpack_ciphertext/Makefile, cbmc/proofs/unpack_ciphertext/cbmc-proof.txt, cbmc/proofs/unpack_ciphertext/unpack_ciphertext_harness.c, mlkem/indcpa.c, mlkem/indcpa.h
Adds contracts and proof artefacts for
unpack_ciphertext() (local function within indcpa.c)
and
indcpa_dec()
All tests OK
All proofs OK
lint OK
=> CBMC Proof of indcpa_dec()

.github/workflows/bench.yml
=> CI: Fix bench.yml

.github/workflows/bench.yml
=> CI benchmark with `-flto` cflags set

scripts/lib/mlkem_test.py
- Resolves #413
The output now looks like:
```
INFO  > Benchmark          ML-KEM-512  (native,    opt) 
keypair cycles = 29185
encaps cycles = 35522
decaps cycles = 46340
percentile      1     10     20     30     40     50     60     70     80     90     99
keypair percentiles:  29153  29161  29168  29178  29183  29185  29186  29189  29201  29211  31892
encaps percentiles:  35479  35493  35500  35508  35515  35522  35525  35531  35543  35554  38204
decaps percentiles:  46298  46317  46325  46333  46337  46340  46344  46351  46359  46374  49030
```
```
INFO  > Benchmark Components ML-KEM-512  (native,    opt) 
keccak-f1600-x1 cycles=927
keccak-f1600-x4 cycles=2608
rej_uniform (bulk) cycles=405
rej_uniform (residue) cycles=392
poly_compress cycles=210
poly_decompress cycles=2
poly_tobytes …
```
=> Fix benchmark output

.github/workflows/ci.yml
=> Pin `ilammy/msvc-dev-cmd` version in MSVC CI

.github/workflows/bench.yml, .github/workflows/bench_ec2_reusable.yml
=> Fix Token Permission Again

cbmc/proofs/poly_compress_du/Makefile, cbmc/proofs/poly_compress_dv/Makefile, cbmc/proofs/poly_decompress_du/Makefile, cbmc/proofs/poly_decompress_dv/Makefile, mlkem/indcpa.c, mlkem/native/arith_native.h, mlkem/native/x86_64/arith_native_x86_64.h, mlkem/native/x86_64/profiles/default.h, mlkem/poly.c, mlkem/poly.h, mlkem/polyvec.c
=> Resolve or remove various small TODOs

.github/workflows/ci.yml, mk/rules.mk
=> Fix duplicated symbol check for building libraries

FIPS202.md
=> Refer to bring-your-own-FIPS202 example from FIPS202.md

mlkem/native/x86_64/src/rej_uniform_avx2.c
The code guarded by `BMI` was inherited from the offical AVX2 implementation, and never exercised or tested since its integration into mlkem-native.
This commit removes it.
* Fixes #577
=> AVX2: Remove BMI code from native rej_uniform implementation

README.md
Strictly speaking, `git` may need to be installed to on a fresh Ubuntu system, so reorder the git clone and apt install steps, and add git to the latter.
=> README: Minor improvement to Ubuntu quickstart

cbmc/KeccakF1600x4_StateExtractBytes/KeccakF1600x4_StateExtractBytes_harness.c, cbmc/KeccakF1600x4_StateXORBytes/KeccakF1600x4_StateXORBytes_harness.c, mlkem/fips202/keccakf1600.h
=> CBMC: A few fixes to FIPS202 harnesses

mlkem/cbd.c, mlkem/cbmc.h, mlkem/fips202/keccakf1600.c, mlkem/fips202/native/x86_64/src/KeccakP-1600-times4-SIMD256.c, mlkem/indcpa.c, mlkem/indcpa.h, mlkem/native/x86_64/src/basemul.c, mlkem/poly.c, mlkem/poly.h, mlkem/polyvec.c, mlkem/polyvec.h, mlkem/verify.h
=> Always use `unsigned` as type for loop indices

cbmc/proof_guide.md
* Fix #382 
- Provide some more details on annotations
- Shorten in various places
- Adjust to changed syntax and convention
=> CBMC: Update proof guide

.github/workflows/bench.yml, .github/workflows/ci.yml, examples/custom_backend/Makefile, mlkem/fips202/fips202_backend.h, mlkem/fips202/native/x86_64/xkcp.h, test/bench_components_mlkem.c, test/bench_mlkem.c
#641 forgot to adjust the benchmarks. This PR fixes that. 
I also extended the quickcheck to additionally run the benchmarks without counting cycles to avoid such errors in the future.
=> Fix includes in benchmarks

.github/workflows/ci.yml, examples/bring_your_own_fips202/Makefile, examples/custom_backend/Makefile, examples/mlkem_native_as_code_package/Makefile, examples/monolithic_build/Makefile, examples/monolithic_build/mlkem_native_all.c, examples/monolithic_build/mlkem_native_monobuild.c, mlkem/arith_backend.h, mlkem/fips202/fips202_backend.h, mlkem/kem.h, scripts/autogen, test/mk/config.mk
See individual commit messages.
=> Add -Wredundant-decls to default CFLAGS

mlkem/fips202/keccakf1600.c, mlkem/fips202/keccakf1600.h, mlkem/native/aarch64/src/arith_native_aarch64.h, mlkem/native/aarch64/src/clean_impl.h, mlkem/native/aarch64/src/opt_impl.h, mlkem/native/aarch64/src/rej_uniform_asm_clean.S, mlkem/native/api.h, mlkem/native/x86_64/src/arith_native_x86_64.h, mlkem/native/x86_64/src/default_impl.h, mlkem/native/x86_64/src/rej_uniform_avx2.c, mlkem/sampling.c, mlkem/verify.h, proofs/cbmc/KeccakF1600_StateExtractBytes/KeccakF1600_StateExtractBytes_harness.c, proofs/cbmc/KeccakF1600_StateExtractBytes_BE/KeccakF1600_StateExtractBytes_be_harness.c, proofs/cbmc/KeccakF1600_StateXORBytes/KeccakF1600_StateXORBytes_harness.c, proofs/cbmc/KeccakF1600_StateXORBytes_BE/KeccakF1600_StateXORBytes_be_harness.c, proofs/cbmc/KeccakF1600x4_StateExtractBytes/KeccakF1600x4_StateExtractBytes_harness.c, proofs/cbmc/KeccakF1600x4_StateXORBytes/KeccakF1600x4_StateXORBytes_harness.c, proofs/cbmc/rej_uniform/rej_uniform_harness.c, proofs/cbmc/rej_uniform_native/rej_uniform_native_harness.c, proofs/cbmc/rej_uniform_scalar/rej_uniform_scalar_harness.c, test/bench_components_mlkem.c, test/bench_mlkem.c, test/gen_KAT.c, test/hal/hal.c, test/nistrng/aes.c, test/test_mlkem.c
Resolves https://github.com/pq-code-package/mlkem-native/issues/689
=> Use unsigned rather than unsigned int everywhere

.github/workflows/ci.yml, nix/util.nix
Resolves https://github.com/pq-code-package/mlkem-native/issues/238.
=> Nix: switch default compiler to gcc14

.gitignore, Makefile
Celebratory 🎉 #768 PR not doing much.
=> ML-MEM -> ML-KEM

dev/x86_64/src/basemul.c, mlkem/compress.c, mlkem/compress.h, mlkem/config.h, mlkem/fips202/fips202.c, mlkem/fips202/fips202x4.c, mlkem/indcpa.c, mlkem/indcpa.h, mlkem/kem.c, mlkem/kem.h, mlkem/mlkem_native.h, mlkem/native/x86_64/src/basemul.c, mlkem/poly.h, mlkem/poly_k.c, mlkem/poly_k.h, mlkem/sampling.c, mlkem/sampling.h, mlkem/symmetric.h, mlkem/verify.h
This PR annotates headers with citations of relevant sections in the FIPS 203 standard.
* Resolves #775
=> Requirements Traceability: Add FIPS 203 citations to function headers

mlkem/verify.h, proofs/cbmc/ct_get_optblocker_i32/Makefile, proofs/cbmc/ct_get_optblocker_i32/ct_get_optblocker_i32_harness.c, proofs/cbmc/ct_get_optblocker_u32/Makefile, proofs/cbmc/ct_get_optblocker_u32/ct_get_optblocker_u32_harness.c, proofs/cbmc/ct_get_optblocker_u8/Makefile, proofs/cbmc/ct_get_optblocker_u8/ct_get_optblocker_u8_harness.c, proofs/cbmc/poly_permute_bitrev_to_custom/Makefile, proofs/cbmc/poly_permute_bitrev_to_custom/poly_permute_bitrev_to_custom_harness.c, proofs/cbmc/value_barrier_i32/Makefile, proofs/cbmc/value_barrier_i32/value_barrier_i32_harness.c, proofs/cbmc/value_barrier_u32/Makefile, proofs/cbmc/value_barrier_u32/value_barrier_u32_harness.c, proofs/cbmc/value_barrier_u8/Makefile, proofs/cbmc/value_barrier_u8/value_barrier_u8_harness.c, scripts/check-contracts, scripts/lint
* Resolves https://github.com/pq-code-package/mlkem-native/issues/802
=> CBMC: Add contract checker

.github/workflows/base.yml, .github/workflows/cbmc.yml, .github/workflows/ci.yml
base.yml runs 'base tests'. If base.yml completes successfully, it runs cbmc.yml and ci.yml.
=> CI: Split ci.yml in three workflows

README.md, RELEASE.md
Here is a draft for the release notes of the upcoming release. 
@hanno-becker any thoughts?
=> Release v1.0.0-beta

README.md, proofs/hol_light/arm/README.md
This commit modifies proofs/hol_light/arm/README.md to update the list of functions covered by a functional correctness proof in HOL-Light.
=> HOL-Light: Update proofs/hol_light/arm/README.md

README.md
=> README: Add badge for different test/proof workflows

README.md
=> README: Document multi-level and C-only build, + various minor fixes

nix/cbmc/default.nix
=> Update CBMC to version 6.5.0

.github/workflows/all.yml, .github/workflows/ci_ec2_reusable.yml, .github/workflows/slothy.yml, dev/aarch64_opt/src/Makefile, flake.nix, nix/slothy/default.nix, nix/util.nix
See individual commit messages. 
Resolves #536
=> Install slothy-cli in nix shell and run optimization of all code in CI

flake.lock, flake.nix, nix/cbmc/default.nix
Resolves https://github.com/pq-code-package/mlkem-native/issues/870
=> CBMC: Update z3 to 4.14.1

integration/liboqs/ML-KEM-1024_META.yml, integration/liboqs/ML-KEM-512_META.yml, integration/liboqs/ML-KEM-768_META.yml
=> liboqs: Extend meta files with _derand functions

.github/actions/functest/action.yml, .github/actions/multi-functest/action.yml, .github/workflows/ci.yml, mlkem/debug.h, nix/slothy/default.nix, nix/util.nix
=> SLOTHY: Update ortools to 9.12 + LLVM nix clean-up

.github/workflows/base.yml, .github/workflows/bench_ec2_reusable.yml, .github/workflows/ci_ec2_container.yml, .github/workflows/ci_ec2_reusable.yml, .github/workflows/hol_light.yml, .github/workflows/scorecard.yaml
Combination of #935 #936 #937 + ec2-github-runner update.
=> CI: Update dependencies 

scripts/autogen
* Resolves #932 
The `autogen` script performs a few tasks which are parametrized over the source files in the mlkem-native repository.
This commit parallelizes those tasks for better performance.
On my Apple M1, time drops from ~44s to ~12s.
=> Parallelize scripts/autogen

RELICENSE.md
This PR adds Mila Anastasova to `RELICENSE.md`.
=> Add Mila Anastasova

RELICENSE.md
**Summary**:
Add my name to RELICENSE.md for aarch64 asm. 
**Steps**:
-
**Do you expect this change to impact performance**: No
=> Add AArch64 ASM relicensing consent for Amin Abdulrahman

scripts/autogen
**Summary**:
Typo in `autogen` script prevents autogenerating new files.
**Steps**:
If your pull request consists of multiple sequential changes, please describe them here:
**Do you expect this change to impact performance**: No
=> Fix a typo in scripts/autogen

nix/cbmc/cbmc-viewer.nix, nix/cbmc/default.nix
Fixes #1019 
Updates nix setup to adopt cbmc-viewer 3.11
=> Adopt cbmc-viewer 3.11

test/acvp_client.py
The ACVTS data structure is very slightly different from the sample files in the usnistgov/ACVP-Server Github repository:
The prompt consists of a 2-element list, where the first element is solely consisting of {"acvVersion": "1.0"} and the second element is the usual prompt containing the test values.
This commit extends the ACVP client to automatically detect that case and handle it properly.
The result is adjusted accordingly (getting the acvVersion appended).
I also disabled the alphabetic sorting of json keys as that just leads to confusion. We are already using the same order as the NIST testvectors, so there is no need to sort alphabetically.
=> ACVP: Adjust to additionally support ACVTS data format

mlkem/src/poly_k.c, nix/cbmc/default.nix, nix/cbmc/z3-lower-bound-typo.patch, proofs/cbmc/polyvec_compress_du/Makefile, proofs/cbmc/polyvec_tobytes/Makefile
=> Revert to Z3 4.12.6

nix/hol_light/0005-Fix-hollight-path.patch, nix/hol_light/default.nix, nix/s2n_bignum/default.nix, proofs/hol_light/arm/proofs/keccak_f1600_x1_scalar.ml, proofs/hol_light/arm/proofs/keccak_f1600_x1_v84a.ml, proofs/hol_light/arm/proofs/keccak_f1600_x2_v84a.ml, proofs/hol_light/arm/proofs/keccak_f1600_x4_v8a_scalar.ml, proofs/hol_light/arm/proofs/keccak_f1600_x4_v8a_v84a_scalar.ml
Previously, we were John Harrison's development branch for ML-KEM, but the work has since been merged into the main s2n-bignum repository.
* Resolves https://github.com/pq-code-package/mlkem-native/issues/1023
=> nix: Switch s2n-bignum remote to awslabs/s2n-bignum

.github/workflows/bench_ec2_reusable.yml, .github/workflows/ci_ec2_container.yml, .github/workflows/ci_ec2_reusable.yml, .github/workflows/hol_light.yml, .github/workflows/nix.yml, .github/workflows/scorecard.yaml
- Resolves: #1207 
- Resolves: #1208 
- Resolves: #1209 
- Resolves: #1210 
- This PR update the dependencies according to PR 1207~1210
=> CI dependency updates
