- fips202/fips202.c
- fips202/fips202.h
- fips202/keccakf1600.c
- fips202/keccakf1600.h
- mlkem/api.h
- mlkem/cbd.c
- mlkem/cbd.h
- mlkem/indcpa.c
- mlkem/indcpa.h
- mlkem/kem.c
- mlkem/kem.h
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/params.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/reduce.c
- mlkem/reduce.h
- mlkem/symmetric-shake.c
- mlkem/symmetric.h
- mlkem/verify.c
- mlkem/verify.h
- randombytes/randombytes.c
- randombytes/randombytes.h
- test/test_kyber.c
Signed-off-by: Duc Tri Nguyen <dnguye69@gmu.edu>
Solve #23 
> Add SPDX license

- .github/workflows/build.yml
- .gitignore
- Makefile
- checksum.sh
- test/gen_KAT.c
- test/gen_NISTKAT.c
- test/nistrng/aes.c
- test/nistrng/aes.h
- test/nistrng/randombytes.h
- test/nistrng/rng.c
This PR should be merged after #24 . 
This PR add:
- `gen_KAT.c`: A way to deterministic generate KAT file. 
- `gen_NISTKAT.c`: Generate NISTKAT file to compare with official/upstream ML-KEM KATs.
- `checksum.sh`: A bash script run executable and compare output of executable with an hash. 
- `Github workflow` to test checksum of MLKEM512, 768, 1024 from 10,000 iterations.
> Add checksum KAT to Github Workflow

- .envrc
- .github/actions/setup-nix/action.yml
- .github/workflows/build.yml
- .gitignore
- Makefile
- flake.nix
- scripts/checksum
- scripts/ci/lint
I've specifically specified to install arm64 gcc in nix
I've set macos-latest as our GitHub runner for now, according to the [official document](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories), `macos-latest` is currently using M1 CPU with 7 GB RAM, which should help #38 for now. 
But as https://github.com/pq-code-package/mlkem-c-aarch64/issues/27 mentioned, we still would like a build system that support cross compilation and testing in qemu in the future
The `checksum.sh` script is moved under `scripts/` folder, and renamed as `checksum` for convenience. In the nix shell, `checksum` should be available instead of …
> Wrap up Nix configuration, setup arm64 github runner

- .github/actions/setup-nix/action.yml
- flake.nix
This PR is building CBMC from sources. Right now it's pinned to the `cbmc-5.95.1` tag (https://github.com/diffblue/cbmc/commit/731338d5d82ac86fc447015e0bd24cdf7a74c442), but we can update it to other commits when needed. 
The build requires around 10 minutes on my machine and in CI.
To make this feasible in the CI, the dependency builds are cached in the Github Action Cache using https://github.com/DeterminateSystems/magic-nix-cache. This means it should only take 10 minutes once, and then consecutive builds should be as fast as loading it from the package manager. 
I tested here by re-running the CI jobs and it seems to work fine.
If we see any CI performance degradation in other PRs, I'll need to look more into the configuration of https://github.com/DeterminateSystems/magic-nix-cache
> Build CBMC from source and add to nix CI cache

- mlkem/poly.c
- mlkem/verify.c
- mlkem/verify.h
See pq-crystals/kyber@9b8d306
See https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/hqbtIGFKIpU/m/cnE3pbueBgAJ
We likely want to implement `cmov_int16` in assembly at some point to make sure it's constant time.
> Fix secret-dependent branch in poly_fromsg

- .github/workflows/ci.yml
I think it makes more sense to run a normal job like linting on standard GitHub-hosted runner instead of a runner for special purpose like `pqcp-arm64`.
> Use ubuntu-latest for lint job instead

- Makefile
- cbmc/proofs/Makefile.common
- cbmc/proofs/poly_compress/Makefile
- cbmc/proofs/scalar_compress_q_16/Makefile
- cbmc/proofs/scalar_compress_q_16/scalar_compress_q_16_harness.c
- cbmc/proofs/scalar_compress_q_32/Makefile
- cbmc/proofs/scalar_compress_q_32/scalar_compress_q_32_harness.c
- cbmc/proofs/scalar_decompress_q_16/Makefile
- cbmc/proofs/scalar_decompress_q_16/scalar_decompress_q_16_harness.c
- cbmc/proofs/scalar_decompress_q_32/Makefile
- cbmc/proofs/scalar_decompress_q_32/scalar_decompress_q_32_harness.c
- mlkem/cbmc.h
- mlkem/poly.c
- mlkem/poly.h
This PR adds contract based CBMC proofs of four functions in mlkem/poly.c
scalar_compress_q_16
scalar_compress_q_32
scalar_decompress_q_16
scalar_decompress_q_32
No functional change.
> Contract-based proofs of poly.c scalar_[de]compress_q*

- README.md
The instructions for setting up using `nix` were not copied over when the nix setup was taken from https://github.com/pq-code-package/mlkem-c-embedded. I added them now. 
@hanno-becker does this contain all the information you were missing?
> Add nix instructions for developers

- .astylerc
- cbmc/proofs/poly_compress/poly_compress_harness.c
- cbmc/proofs/poly_decompress/poly_decompress_harness.c
- cbmc/proofs/scalar_compress_q_16/scalar_compress_q_16_harness.c
- cbmc/proofs/scalar_compress_q_32/scalar_compress_q_32_harness.c
- cbmc/proofs/scalar_decompress_q_16/scalar_decompress_q_16_harness.c
- cbmc/proofs/scalar_decompress_q_32/scalar_decompress_q_32_harness.c
- fips202/fips202.c
- fips202/fips202.h
- fips202/keccakf1600.c
- mlkem/cbd.c
- mlkem/indcpa.c
- mlkem/kem.c
- mlkem/ntt.c
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/reduce.c
- mlkem/symmetric-shake.c
- mlkem/verify.c
- randombytes/randombytes.c
- test/gen_KAT.c
- test/gen_NISTKAT.c
- test/nistrng/aes.c
- test/nistrng/aes.h
- test/nistrng/rng.c
- test/test_kyber.c
This PR closes Issue #59
.astylerc changed to use "bsd" style for braces to ease editing of CBMC contracts, and removes the "--pad-oper" option which breaks CBMC's special "==>" operator.
All .c and .h files reformatted as above and committed as one.
> Reformat with bsd style and NO pad-oper otions for compatibility with CBMC

- Makefile
Signed-off-by: Duc Tri Nguyen <dnguye69@gmu.edu>
The pragma warnings are for CBMC, so for normal usage, it is not neccsary to show. 
Before: 
```
(nix:nix-shell-env) cothans-air:mlkem-c-aarch64 cothan$ scripts/tests kat
INFO  > Kat test
INFO  > make test/bin/gen_KAT512
mlkem/poly.c:28:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma CPROVER check push
^
mlkem/poly.c:29:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma CPROVER check disable "unsigned-overflow"
^
mlkem/poly.c:31:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma CPROVER check pop
^
mlkem/poly.c:67:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma CPROVER check push
^
mlkem/poly.c:68:9: warning: unknown pragma ignored …
```
> Disable unknown pragma warnings

- Makefile
To avoid warnings like https://github.com/pq-code-package/mlkem-c-aarch64/pull/65 going unnoticed, do we maybe just want to error on warnings in CI?
> Add -Werror

- Makefile
- scripts/tests
- test/bench_kyber.c
- test/hal.c
- test/hal.h
This PR adds benchmarking code using either the PMU cycle counter or perf. 
For using PMU, user-space access to PMU registers is required (need to be enabled through a corresponding kernel module).
for using perf, the kernel needs to have `perf` support.
It's based on https://github.com/slothy-optimizer/pqax
We'll have a separate PR for MacOS benchmarks to fully address #28. 
This also adds a `tests bench` command that runs the benchmarks for all parameter sets.
You can either run  `tests bench --cycles PMU` or `tests bench --cycles PERF`. It defaults to `tests bench --cycles NO` which will always print zeros. 
In parallel, @potsrevennil and I are setting up CI to run those benchmarks on a RPi4 (Arm Cortex-A72). We'll add that in a separate PR. 
The current nwarmup/niteration/ntest work …
> Add PMU+PERF benchmarking code 

- .github/actions/setup-nix/action.yml
- .github/workflows/bench.yml
- .github/workflows/ci.yml
- Makefile
- flake.nix
- scripts/tests
This PR depends on #68
I Added a benchmark workflow. Note that the workflow will only run on `main` branch or PR labeled as `benchmark`. The `tests` script is also refactored a bit in order to show the benchmark summary on GitHub action.
I refactored the `nix` shell specification in order to speed up ci, and also
disabled ci jobs running on self-host runner when pushed to fork repositories by the way.
> Add benchmark workflow (RPi4 / Arm Cortex-A72)

- .github/workflows/bench.yml
This should fix the issue of triggering the `bench` workflow for a PR when the `benchmark` label is set, which is what @hanno-becker discovered at https://github.com/pq-code-package/mlkem-c-aarch64/pull/71#issuecomment-2180377139
> Fix the trigger of bench workflow for PR

- cbmc/proofs/Makefile.common
- cbmc/proofs/poly_compress/poly_compress_harness.c
- cbmc/proofs/poly_decompress/poly_decompress_harness.c
- flake.nix
- mlkem/poly.c
Bump CBMC to [freshly released](https://github.com/diffblue/cbmc/releases/tag/cbmc-6.0.0) version 6.
> CBMC: Update to Version 6

- README.md
The README previously suggested that 'clean' code is a necessity for amenability to verification. This was not intentional, and as noted in #63, not true.
This commit removes the mentioning of 'clean' code from the README. The primary qualities that we seek from 'cleanliness' are amenability for manual audit and adaptability. The former was already mentioned explicitly in the README, while the latter is added in this commit.
Closes #63
> Remove mention of 'clean' code from README

- .github/workflows/bench.yml
Follow the [slothy](https://github.com/slothy-optimizer/slothy/blob/main/.github/workflows/test_basic.yaml#L8) approach as @hanno-becker and @mkannwischer suggested.
> Make the bench workflow trigger more naturally

- .gitignore
- Makefile
- mk/config.mk
This PR resolves the issue mentioned in https://github.com/pq-code-package/mlkem-c-aarch64/issues/75
> Makefile keep track of variables

- mk/config.mk
- scripts/tests
- test/hal.c
This adds M1 benchmarking code based on based on https://gist.github.com/dougallj/5bafb113492047c865c0c8cfbc930155. 
~@potsrevennil @hanno-becker, please test this on your M1 devices. Can you also each run it maybe 3 times and post the results here , so we can make sure we are getting stable results?~ 
Results seem stable accross 4 different M1 devices (MacMini and various MacBook). 
To run on the P-cores (Firestorm), run 
```
tests bench -c M1 --run-as-root   
```
To run on the E-cores (Icestorm), run 
```
tests bench -c M1 --run-as-root --mac-taskpolicy background
```
Internally this runs:
```
taskpolicy -c background sudo ./test/bin/bench_kyberXXX
```
Currently this requires to be run as the `root` user, so I added a flag `--run-as-root` to the benchmarking script, but this may require …
> Add M1 benchmarking code

- arm-gnu-gcc.nix
- flake.nix
In the `nix` shell, we specify that `gcc` is downloaded from arm gnu official website for `x86_64` linux, and use the nixpkgs `gcc` for `aarch64` linux. 
However glibc only comes as a dynamic library in both cases, making compiling with `-static` result in error: 
```
ld: cannot find -lc: No such file or directory
```
Now I added glibc static library as a dependency, and configured it into one of the gcc default search path. Additional context, some package manager like `pacman` in `archlinux` packed the gcc with glibc, so that compilation with `-static` works automatically in this case.
@hanno-becker @mkannwischer Please have a look and see if the static compilation works, and the original usage won't break. The static compilation can be …
> Add support for static linking of glibc on aarch64 and x86_64 linux 

- .github/workflows/bench.yml
Depends on #84
We recently bought a Raspberry Pi 5 which comes with a Arm Cortex-A76 (BCM2712).
I've setup up a self-hosted Github runner on it today. 
This PR adds it to the benchmarking. I'm using perf on this platform as I could not yet get a kernel module to compile on this version of Raspberry Pi OS.
This should also automatically create a new section on https://pq-code-package.github.io/mlkem-c-aarch64/dev/bench/ once it is merged.
> Benchmarking on Cortex-A76 (Raspberry Pi 5)

- Makefile
- fips202/fips202x4.c
- fips202/fips202x4.h
- mlkem/indcpa.c
- mlkem/poly.c
- mlkem/poly.h
- mlkem/symmetric-shake.c
Potential optimization: 
- **Multiple Pass Squeezing**: Currently, if `rej_uniform` fails to sample the full vector size, it continues by squeezing a single Keccak lane. By rewriting this logic to append single Keccak calls into a single Keccak X-way call, CPU cycles can be saved. For simplicity, it is currently implemented as a single pass.
- Add Keccak_X4 assembly to replace the `keccak_absorb_x4keccak_squeezeblocks_x4` in `fips202x.c`.
Fixes #35
> Add Keccak X4 interface

- cbmc/cbmc-viewer.nix
- cbmc/default.nix
For compatibility with CBMC 6.1.1 and above, we should upgrade to cbmc-viewer 3.9
This PR updates the version number and hash for this in the NIX flake.
> Update to cbmc-viewer version 3.9

- .github/actions/clear-cache/action.yml
- .github/workflows/bench_ec2_any.yml
- .github/workflows/bench_ec2_reusable.yml
There are spurious failures with the EC2 benchmarking workflows related to the nix-installer cache. This commit modifies the EC2 benchmarking workflow to clear the respective caches first, forcing the download of the installer and thereby avoiding the caching issue.
It also adds an option to keep benchmarking instances are the workflow terminates, which can be useful for debugging issues on workflow failure.
> Clear nix-installer cache prior to EC2 benchmarks

- cbmc/default.nix
- flake.nix
This PR upgrades the CBMC tool in NIX to version 6.2.0.
All existing proofs should pass OK with this new version.
> Update CBMC to version 6.2.0

- .github/workflows/bench.yml
- .github/workflows/bench_ec2_all.yml
- .github/workflows/ci.yml
- cbmc/proofs/Makefile.common
- mk/schemes.mk
- mlkem/params.h
- mlkem/sys/cpucap.h
Also, allow `FORCE_AARCH64` to double-check that a system is recognized as AArch64. Use this in all AArch64-based CI builds.
> Add cpucap.h header and detect AArch64 systems

- .github/actions/bench/action.yml
- .github/actions/cbmc/action.yml
- .github/actions/functest/action.yml
- .github/actions/lint/action.yml
- .github/workflows/bench_ec2_reusable.yml
- .github/workflows/ci.yml
- .github/workflows/ci_ec2_reusable.yml
- flake.nix
- mk/config.mk
In order to support native and cross compiled gcc on x86_64 linux, I added some extra nix shell, since mixing different version of gcc in a same shell, and correctly linking against standard library like glibc is a nightmare...
Therefore there are some changes for ci workflows accordingly, including ec2 related workflows. We should test those workflows as well.
> X86 64 gcc

- META.yml
- mlkem/indcpa.c
- scripts/tests
Resolves #95 
Following https://github.com/pq-crystals/kyber/commit/3c874cddd5fdaf4a7bd13f7e2e4d98a2a1eb8dc4
I created the NISTKAT testvectors with the Kyber reference implementation; these are matching ours
I created the KAT testvectors with the implementation here.
We should still compare against the official NIST testvectors in https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files/ML-KEM-encapDecap-FIPS203
> Update to FIPS203

- .github/actions/bench/action.yml
- .github/actions/cbmc/action.yml
- .github/actions/functest/action.yml
- .github/actions/lint/action.yml
- .github/actions/setup-nix/action.yml
- .github/actions/setup-shell/action.yml
- .github/workflows/bench.yml
There is a cache issue in the Nix installer action, and since we don't really need to cache the nix installer, and there is no config for turning this off, I figured it'd be better to simply install the nix installer manually.
> Fix nix installer cache issue

- mlkem/indcpa.c
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/reduce.h
Asymmetric multiplication [1] speeds up matrix-vector multiplication in NTT-domain via additional caching on the polyvec argument.
This commit provides a C implementation of this strategy and paves the way for clean integration of ASM.
It introduces types poly_mulcache and polyvec_mulcache for precomputed data used by poly/polyvec base multiplication. Those types are meant to be opaque to the caller, an exposed only to allow their construction on the stack.
The mulcache for a poly/polyvec can be computed via `poly[vec]_mulcache_compute()`. It is then passed to base multiplication routines as an additional argument.
Apart from caching repeated computations, another benefit of asymmetric multiplication is that it allows lazy Montgomery reduction during base multiplication, and even …
> Add cache for scaled polys/polyvecs in NTT domain

- mlkem/common.h
- mlkem/indcpa.c
- mlkem/kem.c
- mlkem/params.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.h
- test/gen_KAT.c
- test/gen_NISTKAT.c
Unaligned structures can incur significant performance penalties during memory operations.
Fixes #145 
> Force alignment of structures

- fips202/asm/aarch64/keccak_f1600_x1_v84a_clean.S
- fips202/asm/asm.h
Previous, we would use the lazy-rotation scalar assembly. Since Barrel shifting comes at a performance penalty on Apple CPUs (see https://dougallj.github.io/applecpu/firestorm.html), this implementation is slower than the standard C implementation.
Moreover, the standard C implementation is slower than the x2-batched Neon implementation, restricted to one lane.
This commit therefore changes the default Keccak-f1600 implementation on Apple CPUs to be a 1-fold Neon-based Keccak using SHA3 instructions.
> Use v8.4A-based x1 Keccak-f1600 on Apple CPUs

- mlkem/poly.c
- mlkem/poly.h
We are using poly_getnoise_eta1_4x everywhere.
> Remove unused function poly_getnoise_eta1

- .github/workflows/ci.yml
Fixes https://github.com/pq-code-package/mlkem-c-aarch64/issues/117
> Run CBMC on EC2 runner in CI and guard by label

- .github/workflows/ci.yml
Uses ubuntu-24.04 large runners
Update to use hosted runners.
> Use large runners

- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
This PR removes the indirection `poly_[inv]ntt() -> [inv]ntt()` and instead defines [inv]NTT as operating on `poly` directly.
It also removes an unnecessary double Barrett reduction at the end of the AArch64 NTT.
> Remove `poly_[inv]ntt -> [inv]ntt()` indirection and unnecessary reduction

- .github/actions/bench/action.yml
- Makefile
- mk/bench_components.mk
- mk/schemes.mk
- scripts/tests
- test/bench_components_kyber.c
Until now, `tests bench` would only give performance numbers for the MLKEM toplevel API. While most interesting to the user, the developer needs more insight into where cycles are spent.
This commit introdues `tests bench --components`, backed by a new benchmarking binary `bench_components_kyber{512,768,1024}`, benchmarking various performance critical components of MLKEM.
For now, there is one binary per security level, despite all benchmarks except for the base multiplication being the same for all levels. This is mostly to fit easily into the existing makefile framework, and will likely need refining.
> Add binary for benchmarking MLKEM components

- scripts/tests
Symptom: `scripts/tests` does no longer write benchmarking outputs, which leads to subsequent invocations of the `benchmark-action` failing. This only happens _after_ merge to `main`, as the call to `benchmark-action` is skipped otherwise.
Bug: A previous commit replaced an `if output` check by `if output is True` in the wrong assumption that `output` is a boolean. Instead, it's `None` or a string, so the previous version of the check is necessary.
This commit reverts the respective change.
> tests: Fix bug in export of benchmarking results

- .github/workflows/ci.yml
Run the CI workflow automatically as before, 
enable re-running it by adding a label, 
and ensure the CI ec2 workflow only runs if the PR is created from the main repository.
> Fix CI workflow trigger

- mlkem/indcpa.c
When building the public matrix, we first squeeze GEN_MATRIX_NBLOCKS out of the Keccak state and rejection sample them into the matrix entries. We then run a 'fill up' stage, squeezing and sampling one block a time, until the entry buffers are full.
The previous code got the fill-up stage wrong: Instead of squeezing one block a time, we squeezed GEN_MATRIX_NBLOCKS, _but_ sampled as if we had only squeezed one. This would lead to incorrect results if the fill-up stage needs more than one iteration. Thanks to the large default value of GEN_MATRIX_NBLOCKS, this would not happen in any of the KAT tests, but it may still fail in rare cases. It also fails when setting GEN_MATRIX_NBLOCKS=2.
> Fix gen_matrix()

- mlkem/native/aarch64/profiles/clean.h
- mlkem/native/aarch64/profiles/opt.h
- scripts/ci/lint
Fixes #193 
Adds -Werror flag to run of clang-format in "lint" script so that clang-format returns
an error code if any file needs formatting.
This forces the "lint" script (and CI) to fail and report the error.
> Fix linter for clang-format

- .github/workflows/ci.yml
The current use of 4xlarge instances leads to spurious CI failures due to exceeded vCPU quota.
This commit switches to a lower number of vCPUs, which will lead to a slower, but more reliable CI.
> Reduce number of vCPUs in CBMC CI task

- .github/workflows/bench.yml
As we start integrating AVX2 assembly, this will help us gauge its performance impact.
> Add some x86_64 based benchmarks to CI

- mlkem/native/aarch64/arith_native_aarch64.h
- mlkem/native/aarch64/profiles/clean.h
- mlkem/native/aarch64/profiles/opt.h
- mlkem/native/aarch64/rej_uniform_asm_clean.S
- mlkem/native/arith_native.h
- mlkem/rej_uniform.c
Previously, the native interface for rejection sampling was
```
static inline unsigned int rej_uniform_native
(int16_t *r, unsigned int len,
const uint8_t *buf,
unsigned int *buf_consumed,
unsigned int buflen)
```
Here, `*buf_consumed` would contain the number of bytes processed from the input buffer, and the return value would be the number of valid coefficients sampled.
This generality is not needed -- iInstead, there are only two cases to consider: First, the native call does not support the input arguments, in which case no data is being processed, and one should fallback to the generic C implementation. Second, the call satisfies the same semantics as the C call, that is, it returns the number of sampled coefficients, and guarantees that the entire input buffer was processed if that …
> Simplify native interface for rej_uniform

- mlkem/native/aarch64/profiles/clean.h
- mlkem/native/aarch64/profiles/opt.h
- scripts/ci/lint
The `clang-format` step in the `lint` script would correctly fail
upon badly formatting source files, but (a) the error would not be
displayed correctly, (b) fail to propagate to the result of  `lint`.
This commit fixes this by adjusting the output of the format checker
to match the expectation of `lint`'s internals:
- The output must be to stdout
- The output must consist of lines of the form "file:line:..."
showing every ill-formatted line/file combination once
The output of `clang-format` does not match this format,
and thus needs a bit of massaging.
> Fix `lint` script

- mlkem/indcpa.c
- mlkem/native/arith_native.h
- mlkem/native/profile.h
- mlkem/poly.c
The reference implementation uses the standard bitreversed
order for polynomials in NTT domain. Some optimized native
implementations, however, may want to use a different order
that's easier to work with, for NTT, invNTT, and base multiplication.
When such custom order is used, the generation of the public matrix
needs adjusting, since it is generated directly in NTT domain.
This commit extends the native arithmetic interface to include
an option MLKEM_USE_NATIVE_NTT_CUSTOM_ORDER and an associated
function poly_permute_bitrev_to_custom(), which can be used to
indicate that the native backend uses a custom order.
> Allow non-standard ordering of polynomials in NTT domain

- mk/schemes.mk
- mlkem/common.h
- mlkem/indcpa.c
- mlkem/kem.c
- mlkem/native/x86_64/arith_native_x86_64.h
- mlkem/native/x86_64/consts.h
- mlkem/native/x86_64/fq.inc
- mlkem/native/x86_64/intt.S
- mlkem/native/x86_64/ntt.S
- mlkem/native/x86_64/profiles/default.h
- mlkem/native/x86_64/rej_uniform_avx2.c
- mlkem/native/x86_64/shuffle.S
- mlkem/native/x86_64/shuffle.inc
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.h
- test/bench_components_kyber.c
- test/gen_KAT.c
- test/gen_NISTKAT.c
Based on #201 
The AVX2 Kyber NTT produces non-reduced outputs in non-standard order, for better performance. Neither is currently supported by the C<->Native interface.
To accommodate, we temporarily reduce and reorder the output of the AVX2 NTT to match the current C<->Native interface. This will likely need changing later.
Likewise, the inverse NTT operates on a non-standard order that is currently not supported by our C<->Native interface. To accommodate, we shuffle the data in the expected order first before calling the AVX2 iNTT. This may need revisiting later for better performance.
> Add AVX2 [inv]NTT from official Kyber repository

- mlkem/indcpa.c
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
In `indcpa_enc()`, a single vector `sp` is subject to multiple scalar products. For efficiency, a mulcache for `sp` is used for most of them. The final scalar product with `sp`, however, is recomputing the mulcache instead of using the existing one.
> Add missing use of precomputed mulcache

- mlkem/native/x86_64/arith_native_x86_64.h
- mlkem/native/x86_64/basemul.S
- mlkem/native/x86_64/basemul.c
- mlkem/native/x86_64/profiles/default.h
- mlkem/native/x86_64/shuffle.S
- scripts/tests
Add AVX2 assembly for base multiplication from official Kyber repository.
Since we don't yet integrate all AVX2 assembly, we need to conjugate the basemul assembly with transformation to/from standard coefficient order and the custom order used by the AVX2 code.
> Add AVX2 assembly for base multiplication

- mlkem/native/x86_64/basemul.c
- mlkem/native/x86_64/profiles/default.h
- mlkem/native/x86_64/shuffle.S
The AVX2 assembly routines use a custom coefficient ordering in NTT domain, but until now, we've always conjugated the routines with permutations to keep them in standard order. This commit removes those conjugations, switching to using the custom order throughout.
> AVX2: Switch to custom NTT coefficient ordering 

- .github/actions/bench/action.yml
- .github/actions/cbmc/action.yml
- .github/actions/functest/action.yml
- .github/actions/lint/action.yml
- .github/actions/multi-functest/action.yml
- .github/actions/setup-nix/action.yml
- .github/actions/setup-shell/action.yml
- .github/workflows/bench_ec2_any.yml
- .github/workflows/bench_ec2_reusable.yml
- .github/workflows/ci_ec2_any.yml
- .github/workflows/ci_ec2_reusable.yml
- cbmc/default.nix
- flake.nix
- scripts/tests
Currently since we're equipping our shells with both x64_64 and aarch64 gcc and glibc, which results in quite a large cache size, if we were to upload to and fetch the GH cache, we would easily run into GH cache throttling and rate limiting issues.
Therefore, allowing the nix-setup interface to control the use of the GH cache and disabling it in certain scenarios would be better.
> Fix tests and GH cache issue

- flake.lock
- flake.nix
Somehow nix clang-tools version control is off between linux and macOS, so we need to pin the clang-tools version for now.
According to the `clang-tools` source code, the version is determined by the parameter `clang-unwrapped`, which is why I do nix override `clang-unwrapped` instead of `version`.
By a quick check, using `llvmPackages_18` would results in quite a large size for the nix derivation, I'm not sure the reason of this, but anyway, sticking to `llvmPacakges_17` for now should be fine
> Pin clang-tools version to 17.0.6 in nix flake

- flake.lock
- flake.nix
Reverting #228 because it broke CI because of newly arising out-of-memory conditions on the EC2 machines.
> Revert "Pin clang-tools version in nix flake (#228)"

- mlkem/native/x86_64/arith_native_x86_64.h
- mlkem/native/x86_64/basemul.c
- mlkem/native/x86_64/fq.S
- mlkem/native/x86_64/profiles/default.h
- scripts/tests
- test/bench_kyber.c
Previously, the AVX2 NTT and invNTT assembly was suffixed by a call to `poly_reduce()` to ensure polynomial coefficients sufficiently small that the subsequent arithmetic would not overflow.
If we trust the bounds for the output of the NTT and invNTT [provided by the Kyber repository](https://github.com/pq-crystals/kyber/blob/main/avx2/poly.c#L387), those reductions are not necessary: The bounds are already below the contractual bounds for the C<->native interface on the basis of which correctness of the remaining code can be argued.
This PR therefore removes the reductions after the AVX2 NTT and invNTT.
It also modifies the vector-vector native code to use AVX2 intrinsics for the accumulation, and adds an AVX2 version for `poly_tomont()`.
> Smaller performance improvements of AVX2 backend

- .github/actions/bench/action.yml
- .github/workflows/bench.yml
- .github/workflows/bench_ec2_reusable.yml
- flake.nix
`Bench` shell is added, and `ci-cbmc` and `bench` shell are set to only
include the native gcc as cross gcc is not needed in these cases.
nix cache is disabled for all bench jobs, let's only used nix cache for cbmc to avoid cache hassels
> Split nix shells to avoid `no more space left on disk` issue for benchmarking on some resource-limited machines

- mk/config.mk
- mlkem/debug/debug.h
- randombytes/randombytes.c
- test/hal/hal.c
MLKEM-C-AArch64 strives to be compatible with a wide range of (old) compilers. Force restriction to C99 to facilitate this.
> Set C standard to C99

- fips202/native/x86_64/profiles/xkcp.h
- fips202/native/x86_64/xkcp/KeccakP-1600-times4-SIMD256.c
The FIPS202 C<->native interface operates on de-interleaved batched Keccak states. That is, the Keccak-x4 state is the concatenation, not the interleaving, of four individual Keccak states.
In contrast, SIMD implementations of batched Keccak naturally operate on interleaved states. This is in particular true for the AVX2 implementation from XKCP which we are presently using. To remedy, the native interface implementation conjugates the XKCP core with zipping/unzipping functions for the (de)interleaving of Keccak states.
This commit slightly improves performance by absorbing the zip/unzip of Keccak-x4 states into the XKCP implementation of Keccak-x4. Specifically, the initial memory->register loads are replaced by gather loads, and the final register->memory stores are replaced by scatter …
> Remove explicit zipping/unzipping of Keccak-x4 state in AVX2 FIPS202 backend

- .github/workflows/ci.yml
- Makefile
This PR adds another job to the CI workflow which runs out of the box `make quickcheck`on aarch64-ubuntu
and x86_64-ubuntu. With the exception of `lint` which is always run, other jobs are only run if this succeeds.
> Add 'out of the box' make to CI

- mk/rules.mk
Make 3.8.1 has more restricted support for target pattern matching. By making the make rules more explicit, we ensure compatibility with different make versions and avoid ambiguity.
> Allow makefile to be compatible with make 3.8

- .github/actions/functest/action.yml
- flake.nix
- mk/config.mk
- mk/rules.mk
This commit changes the Makefiles so that the developer can write
```
CC=XXX make ...
```
to overwrite the default compiler choice `gcc` with `XXX`.
This is useful for quick exploration of different compiler choices.
> Allow overwriting default values CC, CPP, AR, LD

- cbmc/proofs/barrett_reduce/Makefile
- cbmc/proofs/barrett_reduce/barrett_reduce_harness.c
- cbmc/proofs/barrett_reduce/cbmc-proof.txt
- cbmc/proofs/fqmul/Makefile
- cbmc/proofs/fqmul/cbmc-proof.txt
- cbmc/proofs/fqmul/fqmul_harness.c
- cbmc/proofs/montgomery_reduce/Makefile
- cbmc/proofs/montgomery_reduce/cbmc-proof.txt
- cbmc/proofs/montgomery_reduce/montgomery_reduce_harness.c
- mlkem/reduce.c
- mlkem/reduce.h
This PR adds CBMC type-safety proof for the reduce.c module,
Specifically, montgomery_reduce() and barrett_reduce()
These functions depend on implementation-defined behaviour, such as casting int32_t to int16_t, and shift-right on
a signed (possibly negative) integer, so proofs of full correctness have not been attempted at this stage.
> CBMC proofs for type-safety of reduce.c

- cbmc/proofs/poly_tobytes/Makefile
- cbmc/proofs/poly_tobytes/cbmc-proof.txt
- mlkem/poly.c
- mlkem/poly.h
This PR adds contracts and proof artefacts for poly_tobytes()
Code updated to add contracts, and make type conversions more explicit for CBMC.
> Add proof artefacts for poly_tobytes()

- .github/actions/bench/action.yml
- .github/actions/setup-shell/action.yml
- .github/actions/setup-ubuntu/action.yml
- .github/workflows/bench_ec2_any.yml
- .github/workflows/bench_ec2_reusable.yml
- mk/config.mk
- Remove redundant `nix-shell` argument from `bench` composite action
- Use relative path for `tests` script in `bench` action to allow running it from non-nix shell.
- Add `setup-ubuntu` composite action for installation of Ubuntu dependencies, if nix is not used.
- Modify bench_ec2_reusable and bench_ec2_any to allow specification of custom compiler, instead of CC in nix shell.
> Modify benchmark actions and workflows to allow custom compiler

- .github/actions/setup-ubuntu/action.yml
- .github/workflows/ci.yml
- Makefile
- flake.nix
- requirements.txt
- scripts/tests
Previously, the quickcheck CI (which guards other CI jobs)
would only run `make quickcheck`, but not exercise the `tests`
script.
This commit adds an invocation of `tests all` to the quickcheck CI,
after setting up the necessary dependencies via the newly introduced
`setup-ubuntu` action.
> Add `tests func` to quickcheck CI

- .github/actions/bench/action.yml
- .github/actions/cbmc/action.yml
- .github/actions/functest/action.yml
- .github/actions/lint/action.yml
- .github/actions/multi-functest/action.yml
- .github/actions/setup-nix/action.yml
- .github/actions/setup-shell/action.yml
- .github/workflows/bench.yml
- .github/workflows/bench_ec2_reusable.yml
- .github/workflows/ci.yml
- .github/workflows/ci_ec2_reusable.yml
- flake.lock
- flake.nix
- Re-ping clang-tools version to `17.0.6` as #228 is reverted in #230
- Solve nix cache issue on CI
- `magic-nix-cache` somehow doesn't work on ec2 instances
- `magic-nix-cache` runs into GH rate limit easily
- replacing `magic-nix-cache` to `cache-nix-action` which is a wrapper over gH official `actions/cache`.
- for adopting `cache-nix-action`, GH shared runner needed to install nix in single user mode
- now nix cache is split by os/arch/nix shell/nix install mode/hash of nix files, for avoiding cache pollution
- cache is sharable among branches, since we suffix cache by hash of nix files, it should be safe to share among branches
- ci nix shells are adjusted accordingly
- ci: native shells
- ci-cross: native shells + cross compiled gcc and glibc
- ci-cbmc: ci shell + cbmc
- …
> Nix cache enhancement in CI and ping clang-tools version to `17.0.6`

- mlkem/poly.h
- mlkem/reduce.h
This PR prevents clang-format reformatting the CBMC contracts that are attached
to function declarations, by wrapping them in // clang-format [off|on]
pairs.
NO CHANGE to the .clang-format file
lint OK
All tests pass OK
All CBMC proofs OK for KYBER_K=2,3,4
> Prevent clang-format from formatting CBMC contracts on functions

- .github/workflows/ci.yml
Previously, CI would only be run when a PR is _modified_, but not when it is originally opened.
This commit fixes that, running CI also when a PR is opened.
> Run CI when PR is opened

- .github/actions/functest/action.yml
- .github/workflows/ci.yml
- flake.nix
This PR adds nix shells for gcc 4.8, 4.9, 7, 11, and clang-18, and adds build+functest runs for them to CI.
> Add gcc 4.8, 4.9, 7 tests to CI

- .github/workflows/ci.yml
Somehow our functional tests are not doing what they are supposed to do
For example: https://github.com/pq-code-package/mlkem-c-aarch64/actions/runs/11566834855/job/32196177392?pr=266
This is running:
```
tests all  --cross-prefix="" --cflags="" --opt --no-func --no-kat --no-nistkat --compile --no-run -v
tests all  --cross-prefix="" --cflags="" --opt --no-func --no-kat --no-nistkat --no-compile --run -v
```
Which are both no-ops. I am not quite sure what these are for, but this is an attempt to fix it.
> Fix CI: Re-enable functional tests

- .github/workflows/bench.yml
- .github/workflows/bench_ec2_any.yml
- .github/workflows/bench_ec2_reusable.yml
- .github/workflows/ci.yml
- .github/workflows/ci_ec2_any.yml
- .github/workflows/ci_ec2_reusable.yml
Most of our jobs don't need any extra permissions, and if they do, this is already set on the job level.
This was flagged by the security code scanning: e.g., https://github.com/pq-code-package/mlkem-c-aarch64/security/code-scanning/60
> CI: Set top-level workflow permissions to contents: read

- .github/actions/cbmc/action.yml
- .github/workflows/bench.yml
- .github/workflows/bench_ec2_reusable.yml
- .github/workflows/ci.yml
- .github/workflows/ci_ec2_reusable.yml
This commit pins all workflow dependencies to specific hashes of the current versions of the respective dependency. This avoid unexpected breaks of our CI and also defends against dependency confusion attacks.
This was flagged by the security code scanning: e.g., https://github.com/pq-code-package/mlkem-c-aarch64/security/code-scanning/51
> Pin CI workflow dependencies

- scripts/tests
Previously, `tests all --cflags="A B"` would not work because the recursive call to `tests func/kat/nistkat` would not properly quote the CFLAGS, leading to an unrecognized option error.
Fixes #276.
> Fix quoting of CFLAGS when fwding from `tests all` to `tests func/kat/nistkat`

- .github/workflows/ci.yml
This PR extends the native debug tests in the CI to enable the address and undefined-behaviour sanitizers in GCC.
Based on #277 
Fixes https://github.com/pq-code-package/mlkem-c-aarch64/issues/278
> Add address + UB sanitizer to CI debug tests

- mlkem/debug/debug.c
- mlkem/debug/debug.h
- mlkem/ntt.c
- mlkem/poly.c
- mlkem/reduce.h
This is a preparatory PR for CBMC proofs. It reorders arguments to `fqmul()` so that the signed canonical twiddle is always in the second position, says as much in the textual description of `fqmul()`, and adds runtime assertions checking the input and output bounds during runtime (for debug builds).
> Add verbal specification and runtime-checking for `fqmul()`

- mlkem/kem.c
- test/test_mlkem.c
Resolves #210.
FIPS204 mandates input validation of the public key in encapsulation, and for the secret key in decapsulation.
This commit adds the input validation for both.
Input validation for the public key is described in Section 7.2 and ensures that coefficients in the public key are in the valid range [0, q-1]. We check this by decoding the public key, reducing to the canonical unsigned representative, re-encoding the reduced polynomial, and comparing it to the input public key.
Input validation for the secret key is described in Section 7.3 and ensures that the hash of the public key (that is part of the secret key) actually corresponds to the real hash of the public key.
We check this by re-computing the hash.
> Add input validation for public key and secret key

- .github/dependabot.yml
- requirements.txt
This adds a dependabot configruation that open pull requests if our github-actions or pip dependencies get updated.
This was flagged by the security code scanning: https://github.com/pq-code-package/mlkem-c-aarch64/security/code-scanning/2
> Add dependency-update tool dependabot

- mlkem/indcpa.c
Previously, the matrix generation was done in a single routine, gen_matrix.
This routine is among the most complex in MLKEM. In particular, verification
is likely going to be challenging with the monolithic structure and up to
three nested loops.
This commit aims to facilitate readability and verifiability by hoisting
the core of the matrix generation into separate helper functions:
- gen_matrix_entry(), generating a single matrix entry from a seed buffer
- gen_matrix_entry_x4(), generating 4 matrix entries from 4 seed buffers
Apart from splitting the code between gen_matrix and the new helper
functions, some more comments have been added.
> Hoist core of gen_matrix() into helper functions

- cbmc/proofs/poly_cbd_eta1/Makefile
- cbmc/proofs/poly_cbd_eta1/cbmc-proof.txt
- cbmc/proofs/poly_cbd_eta1/poly_cbd_eta1_harness.c
- cbmc/proofs/poly_cbd_eta2/Makefile
- cbmc/proofs/poly_cbd_eta2/cbmc-proof.txt
- cbmc/proofs/poly_cbd_eta2/poly_cbd_eta2_harness.c
- mlkem/cbd.c
- mlkem/cbd.h
This commit adds proofs of type safety, memory safety, and output bounds for poly_cbd_eta1 and poly_cbd_eta2.
Resolves #309
> CBMC: Add specs + proofs for poly_cbd_eta{1,2}

- cbmc/proofs/basemul_cached/basemul_cached_harness.c
- cbmc/proofs/cmov_int16/cmov_int16_harness.c
- cbmc/proofs/poly_basemul_montgomery_cached/poly_basemul_montgomery_cached_harness.c
- cbmc/proofs/poly_cbd_eta1/poly_cbd_eta1_harness.c
- cbmc/proofs/poly_cbd_eta2/poly_cbd_eta2_harness.c
- cbmc/proofs/poly_compress/poly_compress_harness.c
- cbmc/proofs/poly_decompress/poly_decompress_harness.c
- cbmc/proofs/poly_frombytes/poly_frombytes_harness.c
- cbmc/proofs/poly_getnoise_eta1122_4x/poly_getnoise_eta1122_4x_harness.c
- cbmc/proofs/poly_getnoise_eta1_4x/poly_getnoise_eta1_4x_harness.c
- cbmc/proofs/poly_getnoise_eta2/poly_getnoise_eta2_harness.c
- cbmc/proofs/poly_getnoise_eta2_4x/poly_getnoise_eta2_4x_harness.c
- cbmc/proofs/poly_mulcache_compute/poly_mulcache_compute_harness.c
- cbmc/proofs/poly_reduce/poly_reduce_harness.c
- cbmc/proofs/poly_tobytes/poly_tobytes_harness.c
- cbmc/proofs/poly_tomont/poly_tomont_harness.c
- cbmc/proofs/polyvec_mulcache_compute/polyvec_mulcache_compute_harness.c
- mlkem/cbd.h
- mlkem/ntt.h
- mlkem/poly.h
- mlkem/polyvec.h
- mlkem/rej_uniform.h
- mlkem/verify.h
Previously, when a function under proof would assume a pointer to a structure, the verification harness would construct an instance of that structure on the stack and pass its address.
This approach is unsound, because it adds to the contractual assumptions of the function the specifics of the function invocation in the test harness. For example, a missing bounds constraint in the spec might go undetected just because the stack-allocated variable happens to satisfy it.
The most robust way to deal with this, so it seems, is to minimize the harnesses to merely pass uninitialized variables of the right type to the function under proof. In particular, where a pointer is expected, pass an uninitialized pointer, rather than the address of a stack allocated structure.
Also, remove redundant `x …
> CBMC: Pass uninitialized pointers in all verification harnesses

- cbmc/proofs/poly_add/Makefile
- cbmc/proofs/poly_add/cbmc-proof.txt
- cbmc/proofs/poly_add/poly_add_harness.c
- cbmc/proofs/polyvec_basemul_acc_montgomery_cached/Makefile
- cbmc/proofs/polyvec_basemul_acc_montgomery_cached/cbmc-proof.txt
- cbmc/proofs/polyvec_basemul_acc_montgomery_cached/polyvec_basemul_acc_montgomery_cached_harness.c
- mlkem/indcpa.c
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
> CBMC: Add spec + proof for `polyvec_basemul_acc_montgomery_cached` + `poly_add`

- cbmc/proofs/pack_pk/Makefile
- cbmc/proofs/pack_pk/cbmc-proof.txt
- cbmc/proofs/pack_pk/pack_pk_harness.c
- cbmc/proofs/polyvec_frombytes/Makefile
- cbmc/proofs/polyvec_frombytes/cbmc-proof.txt
- cbmc/proofs/polyvec_frombytes/polyvec_frombytes_harness.c
- cbmc/proofs/polyvec_reduce/Makefile
- cbmc/proofs/polyvec_reduce/cbmc-proof.txt
- cbmc/proofs/polyvec_reduce/polyvec_reduce_harness.c
- cbmc/proofs/polyvec_tobytes/Makefile
- cbmc/proofs/polyvec_tobytes/cbmc-proof.txt
- cbmc/proofs/polyvec_tobytes/polyvec_tobytes_harness.c
- cbmc/proofs/unpack_pk/Makefile
- cbmc/proofs/unpack_pk/cbmc-proof.txt
- cbmc/proofs/unpack_pk/unpack_pk_harness.c
- mlkem/cbmc.h
- mlkem/indcpa.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
Based on #340 
Fixes #337, #338, #334 #331 #333
> CBMC: `polyvec_[to|from]bytes()`, `[un]pack_pk()`, `polyvec_reduce()`

- .github/actions/cbmc/action.yml
- .github/workflows/ci.yml
- .github/workflows/ci_ec2_reusable.yml
By now, the CBMC proofs take more than >40min. This commit
- Spawns separate instances for MLKEM_K=2,3,4 CBMC proofs
- Uses -j8 to enable multicore checking
> CI: Run CBMC proofs for MLKEM=2,3,4 on separate EC2 instances

- .github/workflows/ci.yml
- cbmc/proofs/gen_matrix_entry/Makefile
- cbmc/proofs/gen_matrix_entry/cbmc-proof.txt
- cbmc/proofs/gen_matrix_entry/gen_matrix_entry_harness.c
- cbmc/proofs/polyvec_tobytes/Makefile
- cbmc/proofs/rej_uniform/rej_uniform_harness.c
- fips202/fips202.h
- mlkem/indcpa.c
- mlkem/polyvec.c
- mlkem/rej_uniform.c
- mlkem/rej_uniform.h
This was pretty hard. I did not manage to verify `gen_matrix_entry()` in acceptable time as it stood, because the reasoning about the pointer increment in the coefficient buffer somehow tripped up the SAT solvers. Instead, I had to modify the signature of `rej_uniform()` to always take the polynomial base -- luckily, this arguably makes the code cleaner anyway. With that signature change in place, things are quite fast. See commit messages for some detail.
Resolves #326
> CBMC: Add spec+proof for `gen_matrix_entry()`

- test/bench_components_mlkem.c
https://github.com/pq-code-package/mlkem-c-aarch64/pull/348 changed the signature of rej_uniform, but missed to adjust the component benchmarks and, hence, benchmarking fails.
This PR fixes that.
> Fix bench_components

- scripts/tests
originally, `tests all` called `tests func/kat/nistkat` internally, since we assumed the tests script is executed in nix shell.
Calling the `func/kat/nistkat` functions internally instead, could avoid the issue if tests script is not executed in nix shell, which means if `tests` is not in PATH.
However, the `func/kat/nistkat` functions are transferred to click command instead, therefore it's not directly callable. The easiest way is to simply factor out the underlying logic to a separate functions (e.g. `_func/_kat/_nistkat`) and call them instead.
- Fix #251
> Fix tests all not working if tests not in PATH

- cbmc/proofs/poly_frommsg/Makefile
- cbmc/proofs/poly_frommsg/cbmc-proof.txt
- cbmc/proofs/poly_frommsg/poly_frommsg_harness.c
- mlkem/poly.c
- mlkem/poly.h
- mlkem/verify.h
- Fixes #336 
Adds proof of poly_frommsg() function. In particular:
1. Strengthen post-condition of cmov_int16() to use OBJECT_UPTO rather than OBJECT_WHOLE to allow a caller to modify one element of a larger array.
2. Add contracts to specification and body of poly_frommsg()
3. Add CBMC proof artefacts for this function.
> Proofs of poly_frommsg

- .github/actions/bench/action.yml
- README.md
- cbmc/proofs/Makefile-template-defines
- cbmc/proofs/README.md
- fips202/native/x86_64/xkcp/KeccakP-1600-times4-SIMD256.c
- flake.nix
https://github.com/pq-code-package/tsc/issues/105
> Rename mlkem-c-aarch64 to mlkem-native

- cbmc/proofs/gen_matrix_entry/Makefile
- fips202/fips202.c
- fips202/fips202.h
- fips202/fips202x4.c
- fips202/fips202x4.h
- mlkem/indcpa.c
- mlkem/symmetric-shake.c
- test/gen_KAT.c
Some consumers may want to provide their own Kecak implementations instead of using the ones provided by us. Such implementations may be using Keccak implementations using dynamic memory allocations, e.g., the Keccak from OpenSSL does that.
In that case, we need to explicitly free the state once it is no longer needed.
This PR adds corresponding functions called _ctx_release() and calls them in the appropriate places.
Since all of our Keccak implementations use a statically allocated state, the xxx_ctx_release() is implemented as a no-op here.
Naming of functions follows PQClean and liboqs.
> FIPS202: Add _ctx_release() functions to support 3rd party FIPS202 implementations using dynamically allocated state

- cbmc/default.nix
- cbmc/litani.nix
- cbmc/z3.nix
- flake.lock
- flake.nix
- #349 (bitwuzla is bumped to 0.6.0)
- #351 
- flake lock is updated, we can update gcc to 14.1.0 whenever we want now
- nix flake is slightly refactored by using nix flake packages, it'd be easier to test some nix derivations
- ex: `nix build .#cbmc` would built cbmc dependencies in to local directory `result`. We could thus check the binaries in `result/bin` to see if everything works out as expected
> Update bitwuzla -> 0.6.0 &  Z3 -> 4.13.3

- cbmc/proofs/polyvec_compress/Makefile
- cbmc/proofs/polyvec_compress/cbmc-proof.txt
- cbmc/proofs/polyvec_compress/cbmc-viewer.json
- cbmc/proofs/polyvec_compress/polyvec_compress_harness.c
- cbmc/proofs/polyvec_decompress/Makefile
- cbmc/proofs/polyvec_decompress/cbmc-proof.txt
- cbmc/proofs/polyvec_decompress/cbmc-viewer.json
- cbmc/proofs/polyvec_decompress/polyvec_decompress_harness.c
- cbmc/proofs/scalar_decompress_d10/Makefile
- cbmc/proofs/scalar_decompress_d10/README.md
- cbmc/proofs/scalar_decompress_d10/cbmc-proof.txt
- cbmc/proofs/scalar_decompress_d10/cbmc-viewer.json
- cbmc/proofs/scalar_decompress_d10/scalar_decompress_d10_harness.c
- cbmc/proofs/scalar_decompress_d11/Makefile
- cbmc/proofs/scalar_decompress_d11/README.md
- cbmc/proofs/scalar_decompress_d11/cbmc-proof.txt
- cbmc/proofs/scalar_decompress_d11/cbmc-viewer.json
- cbmc/proofs/scalar_decompress_d11/scalar_decompress_d11_harness.c
- mlkem/cbmc.h
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
This PR adds a largely straightforward spec + proof for polyvec_compress() and poly_decompress(). Care needs to be taken to track the bounds of the compressed data, and to introduce explicit masking when writing out the individual bytes, since in the configuration used by our CI, CBMC fails upon implicit truncation that cannot be proved to be effectless.
> CBMC: Spec + proof `polyvec_[de]compress` 

- .github/actions/bench/action.yml
- .github/actions/functest/action.yml
- .github/actions/multi-functest/action.yml
- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/ci_ec2_any.yml
- .github/workflows/ci_ec2_reusable.yml
- .gitignore
- scripts/lib/mlkem_test.py
- scripts/lib/util.py
- scripts/tests
Refactor `tests` script mainly for preparation to easily integrate acvp into `tests`:
- Split the original tests script into three files: the main `scripts/tests` script now acts as a Click-based CLI interface.
- Moved core testing logic to `scripts/lib/test.py`, providing APIs that the Click commands call for main testing functionality.
- Added scripts/lib/util.py for common type classes and utility functions.
- Rename the `State` class as mentioned in https://github.com/pq-code-package/mlkem-c-aarch64/pull/347#discussion_r1830477719)
- Make `tests func/kat/nistkat/all` interface consistent:
- `--opt` flags become choice of `ALL | OPT | NO_OPT` (case insensitive)
> Refactor Tests Script for preparing ACVP python script Integration

- .github/actions/cbmc/action.yml
- cbmc/proofs/crypto_kem_keypair_derand/Makefile
- cbmc/proofs/crypto_kem_keypair_derand/cbmc-proof.txt
- cbmc/proofs/crypto_kem_keypair_derand/crypto_kem_keypair_derand_harness.c
- cbmc/proofs/indcpa_keypair_derand/Makefile
- cbmc/proofs/indcpa_keypair_derand/cbmc-proof.txt
- cbmc/proofs/indcpa_keypair_derand/indcpa_keypair_derand_harness.c
- cbmc/proofs/matvec_mul/Makefile
- cbmc/proofs/matvec_mul/cbmc-proof.txt
- cbmc/proofs/matvec_mul/matvec_mul_harness.c
- cbmc/proofs/polyvec_tomont/Makefile
- cbmc/proofs/polyvec_tomont/cbmc-proof.txt
- cbmc/proofs/polyvec_tomont/polyvec_tomont_harness.c
- fips202/fips202.h
- mlkem/cbd.h
- mlkem/cbmc.h
- mlkem/indcpa.c
- mlkem/indcpa.h
- mlkem/kem.h
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
This PR brings together the work of the past weeks into a top-level type+memory safety proof of `crypto_kem_keypair_derand()` -- with only NTT and SHA3 axiomatized, but all other lower level functions specified and proved.
A few changes had to be made to the existing lower level proofs -- see the individual commit messages for details.
> CBMC: Proof of type safety and memory safety for toplevel MLKEM KeyGen (modulo NTT+SHA3)

- cbmc/proofs/ntt_butterfly_block/Makefile
- cbmc/proofs/ntt_butterfly_block/cbmc-proof.txt
- cbmc/proofs/ntt_butterfly_block/ntt_butterfly_block_harness.c
- cbmc/proofs/ntt_layer/Makefile
- cbmc/proofs/ntt_layer/cbmc-proof.txt
- cbmc/proofs/ntt_layer/ntt_layer_harness.c
- cbmc/proofs/poly_ntt/Makefile
- cbmc/proofs/poly_ntt/cbmc-proof.txt
- cbmc/proofs/poly_ntt/poly_ntt_harness.c
- mlkem/cbmc.h
- mlkem/common.h
- mlkem/debug/debug.h
- mlkem/ntt.c
- mlkem/ntt.h
> CBMC: Proof of `poly_ntt()`

- cbmc/proofs/polyvec_invntt_tomont/Makefile
- cbmc/proofs/polyvec_invntt_tomont/cbmc-proof.txt
- cbmc/proofs/polyvec_invntt_tomont/polyvec_invntt_tomont_harness.c
- cbmc/proofs/polyvec_ntt/Makefile
- cbmc/proofs/polyvec_ntt/cbmc-proof.txt
- cbmc/proofs/polyvec_ntt/polyvec_ntt_harness.c
- mlkem/ntt.h
- mlkem/polyvec.c
- mlkem/polyvec.h
This PR:
- Proves `polyvec_ntt` based on the proof of `poly_ntt` (not that the previous spec missed the pre-condition on the input bounds)
- States the contract of `poly_invntt_tomont` (but does not proof it)
- Proves `polyvec_invntt_tomont` based on the contract of `poly_invntt_tomont` 
Resolves #330 
Resolves #378 
Based on #371
> CBMC: State (not prove) `poly_invntt_tomont` + Prove `polyvec_ntt` and `polyvec_invntt_tomont`

- mlkem/polyvec.h
Fixes #362 
Removes detailed ENSURES clause for polyvec_add()
since this is not required for proof of type-safety of calling units.
Proof time improves from 11minutes to 1 minute on MacBook Pro using Z3.
Tried Bitwuzla but was slower.
All tests OK
lint OK
> Improve speed of polyvec_add() proof.

- fips202/fips202.h
- mlkem/indcpa.c
- mlkem/symmetric-shake.c
- mlkem/symmetric.h
This PR adds CBMC contracts to the FIPS202 hash functions and their MLKEM-specific variants.
We also adjust indcpa_keypair_derand() to avoid explicit aliasing of actual parameters in the call to hash_g(), as is already done in AWS-LC.
All tests OK
All proofs OK
lint OK
> Axiomatize FIPS-202 Hash functions

- cbmc/proofs/proof_guide.md
- cbmc/sources/README.md
- mlkem/cbd.c
- mlkem/cbd.h
- mlkem/cbmc.h
- mlkem/indcpa.c
- mlkem/indcpa.h
- mlkem/ntt.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/rej_uniform.c
- mlkem/rej_uniform.h
> CBMC: More minor clean-up

- cbmc/proofs/poly_invntt_tomont/Makefile
- cbmc/proofs/poly_invntt_tomont/cbmc-proof.txt
- cbmc/proofs/poly_invntt_tomont/poly_invntt_tomont_harness.c
- mlkem/ntt.c
This commit adds a memory and type safety proof for the inverse NTT, using CBMC.
Contrary to the proof for the forward NTT, which required introducing helper functions per loop, the inverse NTT can be verified as-is, providing suitable invariants for the inner loops, and unrolling the outer loop. The decisive simplification compared to the forward NTT is that there's a constant bound on the coefficients, independent of the layer. This is because the inverse NTT reduces more eagerly than the forward NTT.
A stumbling stone during development was the meaning of the UNWINDSET. In the context of the inverse NTT, the loop structure is
```c
for (...) { ...}
for (...) { // XXX
for (...) {
for (...) { ...}
}
}
```
and, oddly enough, the loop `XXX` has index 3.
That aside, CBMC+Z3 get through the …
> CBMC: Add spec + proof for poly_invntt_tomont

- cbmc/proofs/cmov/Makefile
- cbmc/proofs/cmov/cbmc-proof.txt
- cbmc/proofs/cmov/cmov_harness.c
- cbmc/proofs/crypto_kem_dec/Makefile
- cbmc/proofs/crypto_kem_dec/cbmc-proof.txt
- cbmc/proofs/crypto_kem_dec/crypto_kem_dec_harness.c
- cbmc/proofs/crypto_kem_enc/Makefile
- cbmc/proofs/crypto_kem_enc/cbmc-proof.txt
- cbmc/proofs/crypto_kem_enc/crypto_kem_enc_harness.c
- cbmc/proofs/crypto_kem_enc_derand/Makefile
- cbmc/proofs/crypto_kem_enc_derand/cbmc-proof.txt
- cbmc/proofs/crypto_kem_enc_derand/crypto_kem_enc_derand_harness.c
- cbmc/proofs/crypto_kem_keypair/Makefile
- cbmc/proofs/crypto_kem_keypair/cbmc-proof.txt
- cbmc/proofs/crypto_kem_keypair/crypto_kem_keypair_harness.c
- cbmc/proofs/verify/Makefile
- cbmc/proofs/verify/cbmc-proof.txt
- cbmc/proofs/verify/verify_harness.c
- mlkem/kem.c
- mlkem/kem.h
- mlkem/randombytes.h
- mlkem/verify.c
- mlkem/verify.h
This PR adds a memory and type safety proofs for `crypto_kem_enc_derand`, `crypto_kem_enc` and `crypto_kem_keypair` using CBMC. This brings together various lower level proofs established before.
Unfortunately, the `memcmp()` invocation in `check_pk()` had to be wrapped manually to prevent CBMC from inlining an implementation of `memcmp()` and somehow getting stuck.
* Resolves #387 
* Resolves #386 
* Resolves #388 
> CBMC: Add proof for crypto_kem_enc[_derand], crypto_kem_keypair, crypto_kem_dec

- mlkem/ntt.c
This is to address what appears to be proof brittleness in the previous, monolithic version. This version did succeed on Apple M1 machines, but failed regularly on the Graviton3 CI machines.
> Minor cleanup in invNTT proof

- cbmc/proofs/verify/Makefile
- cbmc/proofs/verify/verify_harness.c
- mlkem/verify.c
- mlkem/verify.h
Adds proof of type-safety AND partial correctness
of the verify() function.
All tests OK
lint OK
All proofs OK, including calling unit crypto_kem_dec()
> CBMC proof of verify()

- scripts/lib/mlkem_test.py
Fix `tests bench --opt=all` only compile the benchmark once and run the binary twice, while it should compile and run the opt benchmark then compile and run the non-opt benchmark instead.
Fix `tests all` flag `--no-acvp` not actually used in function `all`, accidentally acvp tests would be disabled if kat test is disabled.
> fix: tests bench --opt=all and tests all --no-acvp

- cbmc/proofs/matvec_mul/Makefile
- mlkem/indcpa.c
Adjust modelling of arrays in CBMC for proof of this function, as recommended by CBMC team (See [CBMC Issue 8505](https://github.com/diffblue/cbmc/issues/8505)).
Proof for this function reduces from 70 seconds to about 9 seconds on desktop.
All tests OK
All proofs OK
lint OK
> Improve speed of proof of matvec_mul()

- mlkem/indcpa.c
- mlkem/native/x86_64/rej_uniform_avx2.c
- mlkem/rej_uniform.c
This fixes a bug that caused our rej_uniform implementation to always use the C version instead of correctly using the native implementation when it should.
This bug was introduced, when we added the x86_64 backend as the flag for enabling it was renamed from MLKEM_USE_NATIVE_AARCH64 to MLKEM_USE_NATIVE_REJ_UNIFORM. This was not correctly changed in the rej_uniform.c.
Below are the performance results on my 13th Gen Intel i7-1360P (Raptor Lake) using gcc 14.2.1 from the Arch Linux repo.
Before (6aa6118e):
ML-KEM-512: 22353, 27820, 35663
ML-KEM-768: 39626, 43605, 54916
ML-KEM-1024: 58983, 65402, 80370
After:
ML-KEM-512:  19652, 25165, 32945
ML-KEM-768: 33383, 37343, 48652
ML-KEM-1024: 47658, 54087, 69003
#224
> Enable rej_uniform native implementation in x86_64

- .github/workflows/bench_ec2_reusable.yml
- .github/workflows/ci_ec2_reusable.yml
The `start-ec2-runner` job's responsibility is to bring up an EC2 instance and have it self-register as a self-hosted github runner. The output of this job is needed in the cleanup job `stop-ec2-runner`.
The `stop-ec2-runner` job is marked as `always()`, to make it non-cancellable. However, it is still possible that `start-ec2-runner` is cancelled after an instance has been brought up and potentially self-registered as a GH runner, and in that case, `stop-ec2-runner` wouldn't have the instance and runner ID at its disposal to clean things up.
This commit tries to fix this race condition by marking `start-ec2-runner` as `always()`, thereby making it non-cancellable.
> CI: Make EC2 instance-bringup job non-cancellable

- .github/workflows/ci.yml
- Makefile.Microsoft_nmake
- README.md
- fips202/keccakf1600.h
- mlkem/common.h
- mlkem/indcpa.c
- mlkem/kem.c
- mlkem/poly.c
- test/bench_components_mlkem.c
- test/gen_KAT.c
- Resolves #227
- For simplicity, I only provide a `quickcheck` target in the windows makefile for building and running the functional tests binaries
- Windows nmake command:
- `nmake /f ./Makefile.Microsoft_nmake quickcheck`
- Built binaries path:
- `test/build/mlkem512/bin/test_mlkem512.exe`
- `test/build/mlkem768/bin/test_mlkem768.exe`
- `test/build/mlkem1024/bin/test_mlkem1024.exe`
- Only support for compiling non-opt implementation, as I don't know how to make the assembly compatible on Windows
> Add Windows build + functional test (using nmake)

- .github/workflows/bench.yml
- .github/workflows/bench_ec2_any.yml
Until now, we only pushed benchmarks for optimized code to the github pages. That was the wrong decision, as we are now curious to understand (a) where mlkem-native's pure-C performance stands in comparison to the reference implementation, and (b) how it has evolved over time, esp. in light of restructurings we made for the CBMC proofs.
Ultimately, we should retroactively conduct & push non-opt benchmarks. For now, this commit merely enables pushing benchmarking results to GH pages for non-optimized code.
Care needs to be taken to not mess up with existing optimized benchmarks by changing their name. Thus, we keep the previous names (which matched the target name, e.g. "Graviton 3"), but append " (no-opt)" in case we benchmarked the C backend.
* Resolves #406
> CI: Push non-opt benchmarks to GH pages

- .github/workflows/bench.yml
- .github/workflows/bench_ec2_reusable.yml
- test/hal/hal.c
Benchmarking on x86_64 instances using `perf` seems less accurate than using `rdtsc`. This PR (a) adds support for `PMU_CYCLES` on x86_64 systems, and (b) changes the CI to use `rdtsc`-based cycle counting for all x86_64-based benchmarks. See the commit messages for a bit more detail.
> Bench: Use PMU instead of PERF for x86_64 benchmarking

- test/bench_components_mlkem.c
This extends our component benchmarks by all poly_* functions and all polyvec_*. Additionally, `gen_matrix` from indcpa.c is added.
> Extend component benchmarks

- mk/bench.mk
- mk/config.mk
- mk/crypto.mk
- mk/rules.mk
- mk/schemes.mk
- scripts/ci/check-namespace
Currently in nix shell, the build system won't properly linked if `-flto` is set.
This is due to that nix `gcc` comes with lto library, binutils like `ar` doesn't seem to
properly configured regarding this.
The easiest workaround to make `-flto` work is therefore to avoid building
libraries, let `gcc` take over everything.
Namespace checking needed to be updated as well, due to the new build system compiles fips202 artifact to `test/build/mlkemxxx/fips202` now.
> Adjust makefile for support -flto in nix shell

- .github/workflows/ci.yml
- mlkem/indcpa.c
GEN_MATRIX_NBLOCKS is a heuristic value estimating the amount of rejection sampling input to sample 256 polynomial coefficients.
While this value is hardcoded to 3 by default, one should be able to set it to any positive value. Moreover, some code-paths are not as easily reached with the default value, and testing a lower value increases the chances of catching bugs in those.
This commit allows the user to specify GEN_MATRIX_NBLOCKS in the CFLAGS, and extends the CI to test the non-standard values 1,2, and 4.
* Fixes #186 
> CI: Add test for non-standard values of GEN_MATRIX_NBLOCKS

- .github/workflows/bench.yml
These are wrongly configured. 
After we merge this we should delete the wrong benchmarking data.
>  EC2 bench: Fix c6a/c6i instance types

- .github/workflows/bench.yml
c6a.medium is not a valid instance type.
#431 was wrong. Sorry about that.
> EC2 bench: c6a.medium -> c6a.large

- README.md
- mk/schemes.mk
- mlkem/verify.c
verify.c contains various functions which must not be inlined because compilers are tempted to compile them into code that's not constant time and thereby leaks something about the secret data being processed.
If `-flto` is used as a compile-time flag, verify.c is likely to be inlined.
This commit modifies the Makefile to force `-fno-lto` for verify.c, overwriting `-flto` if present.
This in particular affects our CI benchmarks, which do compile with `-flto`.
> Build: Never use -flto for verify.c

- .github/workflows/bench.yml
- .github/workflows/bench_ec2_any.yml
- .github/workflows/bench_ec2_reusable.yml
Previously, we were spinning up separate instances for benchmarking
optimized and non-optimized code. This is inefficient and incurs
unnecessary cost for very large instances (e.g. metal).
This commit changes the benchmarking CI to benchmark optimized
and non-optimized code on the same EC2 instance.
> CI: Benchmark opt and non-opt on the same EC2 instance

- .github/workflows/bench.yml
- .github/workflows/bench_ec2_reusable.yml
Current benchmarks on c7i.large exhibit a high performance variability
that is likely due to virtualization.
This commit switches to a metal instance for c7i to counter this problem.
https://pq-code-package.github.io/mlkem-native/dev/bench/ suggests that 
the issue does not appear for c6a, c6i, c7a, so those are not touched (and
indeed it would be non-trivial to do so because we'd exceed the vCPU quote
with more than one metal instance).
> Benchmark c7i on metal

- flake.nix
This PR properly set $CC in Nix shells when using multiple GCC versions (the last GCC in the package list overwrites $CC), thus avoiding cumbersome nix setup.
1. Properly Set $CC:
- Overridden in stdenv to ensure consistent behavior across platforms.
- Explicitly set via shellHook on Darwin, where GCC is not installed via Nix.
2. Refactor GCC Configuration:
- Introduced native-gcc to streamline platform-specific logic (null on Darwin, wraps pkgs elsewhere).
- Simplified code by merging default_gcc into core and removing redundant checks.
These changes eliminate the need for manual workarounds and simplify working with GCC toolchains in Nix, and make it easier to integrate additional toolchains:
- see #449 
> Properly set $CC in nix shell for different architecture

- .clang-format
- mlkem/cbd.c
- mlkem/ntt.c
- mlkem/poly.c
- mlkem/rej_uniform.c
- mlkem/verify.c
Fixes #450 
This PR tracks efforts to remove the ASSIGNS contract from loop statement now that CBMC 6.4.0 can infer them automatically, most of the time.
As a proof of concept, all-but-one of the ASSIGNS contracts in poly.c have been removed.
> Remove loop ASSIGNS contracts now CBMC can infer most of them

- mlkem/indcpa.c
- mlkem/poly.h
In encapsulation of ml-kem-768 and ml-kem-1024, we are using poly_getnoise_eta1_4x to sample both the secret and the error. This works because ETA1 = ETA2 = 2.
However, this is somewhat confusing when reading the code.
This commit uses poly_getnoise_eta2_4x instead and defines it as an alias for poly_getnoise_eta1_4x in case ETA1=ETA2. I think this the cleaner solution.
> Add poly_getnoise_eta2_4x alias for poly_getnoise_eta1_4x

- .github/actions/functest/action.yml
- .github/actions/multi-functest/action.yml
- .github/workflows/ci.yml
- .github/workflows/ci_ec2_reusable.yml
- META.yml
- flake.nix
- scripts/lib/mlkem_test.py
- scripts/lib/util.py
- scripts/tests
- test/gen_KAT.c
- ~Based on #448~ 
- Add riscv64 toolchain in nix shell
- Add riscv64 qemu support in the tests script
- Fixed an issue where test scripts could incorrectly execute binaries using a custom exec wrapper in QEMU when a cross prefix differs from the native toolchain and a custom exec wrapper is provided.
- With the fix, we could now also run `tests func/kat/nistkat/all` with a provided custom wrapper
> Add riscv64 toolchain support

- mlkem/native/x86_64/basemul.S
- mlkem/native/x86_64/basemul.c
- mlkem/native/x86_64/fq.inc
- mlkem/native/x86_64/intt.S
- mlkem/native/x86_64/ntt.S
- mlkem/native/x86_64/profiles/default.h
- mlkem/native/x86_64/shuffle.inc
Resolves #222
This commit documents the AVX2 assembly for the [inv]NTT in the x86_64 native backend. In particular, it tracks the bounds of data through the various layers.
The invNTT implementation is highly aggressive in terms of minimizing the number of modular reductions, which makes a pen-and-paper analysis rather difficult.
At the last invNTT layer, the bounds reasoning applied is not enough to show absence of overflow. To remedy, an additional reduction is added.
The analysis for the forward NTT is straightforward.
Ultimately, we confirm the absolute bound of 8*MLKEM_Q for the output of forward and inverse NTT; this is the contractual bound that the higher-level C-code is working with.
> AVX2: Document bounds in NTT and invNTT

- .github/actions/cbmc/action.yml
- scripts/lib/mlkem_test.py
- scripts/tests
Currently to run all CBMC proofs, we have to run
```
cd cbmc/proofs
MLKEM_K=2 python3 run-cbmc-proofs.py
MLKEM_K=3 python3 run-cbmc-proofs.py
MLKEM_K=4 python3 run-cbmc-proofs.py
```
This commit wraps all that into a single wrapper:
`tests cbmc`
This is not integrated into CI.
> CBMC: add `tests cbmc` command

- cbmc/proofs/mlkem_shake256_prf/Makefile
- cbmc/proofs/mlkem_shake256_prf/cbmc-proof.txt
- cbmc/proofs/mlkem_shake256_prf/mlkem_shake256_prf_harness.c
- cbmc/proofs/mlkem_shake256_rkprf/Makefile
- cbmc/proofs/mlkem_shake256_rkprf/cbmc-proof.txt
- cbmc/proofs/mlkem_shake256_rkprf/mlkem_shake256_rkprf_harness.c
- fips202/fips202.h
- fips202/fips202x4.h
These two are still missing. As they are basically wrappers around the FIPS202 functions, these are straightforward given the FIPS202 contracts.
> CBMC: Prove `mlkem_shake256_prf` and `mlkem_shake256_rkprf`

- scripts/lib/mlkem_test.py
- #449 accidentally broke `tests bench` cli parsing on mac when `mac-taskpolicy` option is presented.
- `tests bench -c M1 --run-as-root` would still work as expected
> Fix `tests bench` mac-taskpolicy handling in benchmarks

- fips202/fips202.c
- fips202/fips202.h
- mlkem/indcpa.c
- mlkem/indcpa.h
- mlkem/kem.c
- mlkem/kem.h
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/reduce.c
- mlkem/reduce.h
We have partially moved documentations describing function sigantures to header files while writing CBMC proofs. However, it's currently not consistent and there is still come documentation left in C sources.
This commit moves all those comments to the header files.
Resolves https://github.com/pq-code-package/mlkem-native/issues/434 Resolves https://github.com/pq-code-package/mlkem-native/issues/211
I also cleaned up the placement of the namespacing.
> Move all function signature documentation to header files

- mlkem/reduce.c
The previous bounds documentation in reduce.h was difficult to follow
and lacked details regarding the transition between rational, integral,
and C computations.
This commit simplifies the documentation by providing a single generic
bound for `montgomery_reduce_generic()`, and deriving (only) the contractual
bounds for the specializations `montgomery_reduce()` and `fqmul()`.
> reduce.c: Simplify bounds documentation and fix runtime assertion

- .github/workflows/ci.yml
- Makefile
- fips202/native/x86_64/xkcp/KeccakP-1600-times4-SIMD256.c
- mk/config.mk
- mk/crypto.mk
- mk/rules.mk
- mk/schemes.mk
- mlkem/debug/debug.c
- mlkem/native/aarch64/aarch64_zetas.c
- mlkem/native/x86_64/basemul.c
- mlkem/native/x86_64/consts.c
- mlkem/native/x86_64/rej_uniform_avx2.c
- mlkem/verify.c
- scripts/autogenerate_files.py
- scripts/ci/check-namespace
**Summary**:
- Resovles #457 
**Steps**:
- Since `$AR` doesn't care about duplicated symbols, the build system now links the static library after it is built for chekcing any duplicates. Additionally, a quick check for this has been added to CI.
- The build system is adjusted to build test binaries by linking with static library instead of directly with object files, since we'll need to test the built static library anyway. Therefore the build system would be simpler and easier to maintain if we do it this way.
- However, seems like `gcc` and `ar` are not happy with linking with static library if `-flto` is provided. `--plugin` would need to be properly set to the lto plugin location. Using `gcc-ar` as default instead of `ar` should resolve the issue, as the wrapper is already properly …
> Build static library for 3 parameter set

- fips202/fips202.c
`shake128_absorb_once()` calls `keccak_absorb_once()`, which already includes zeroization of the state. The zeroization can therefore be dropped from `shake128_absorb_once()`.
> FIPS202: Remove redundant zeroization in shake128_absorb_once()

- .github/workflows/ci.yml
- Makefile
- mk/config.mk
- mk/crypto.mk
- mk/rules.mk
- mk/schemes.mk
This PR changes the build so that we generate four libraries:
* `libmlkem.a`
* `libmlkem{512,768,1024}.a`
All of those libraries include the FIPS functionality, which is no longer built as a separate `.a` file.
> Build libraries for individual and all security levels

- cbmc/proofs/gen_matrix/Makefile
- mlkem/indcpa.c
* Resolves #470 
`gen_matrix()` concludes with an entry-wise permutation of polynomial coefficients, if required by the native backend.
Previously, the loop over the matrix coefficients was conditional on a custom permutation being present, which would exclude it from the scope of CBMC.
With this commit, the loop is unconditional, and a contract used for the custom permutation. If no custom permutation is needed, it is defined as a no-op which the compiler will automate away.
> CBMC: Add custom reordering loop into CBMC scope

- .github/actions/multi-functest/action.yml
- .github/workflows/ci.yml
- aarch64_be-none-linux-gnu-gcc.nix
- flake.nix
- mk/auto.mk
- mlkem/native/aarch64/README.md
- mlkem/sys/cpucap.h
- scripts/lib/mlkem_test.py
* Resolves #528 
This commit modifies the nix flake to install an AArch64 big endian compiler in the ci-cross shell.
It also modifies the CI to cross-(build+test) mlkem-native on aarch64_be.
This confirms that the C frontend and backend are working on big endian systems. This is important to check since we do have a few cases of endian-ness dependent code.
The AArch64 backend is currently _not_ compatible with big endian systems, and already disabled (this is because we use `__AARCH64_EL__` as a guarding architecture flag -- for big endian, it would be `__ARCH64_EB__`).
> Test mlkem-native on AArch64_be

- mlkem/ntt.c
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.h
- mlkem/rej_uniform.h
Those annotations were previously meant to completely enumerate all changes from the reference implementation, but we have not been diligent adding them, so that now numerous changes are not annotated.
This commit gives up on the idea of annotating every change from the reference implementation, and removes REF-CHANGE annotations accordingly.
> Remove REF-CHANGE annotations

- cbmc/rej_uniform_scalar/Makefile
- cbmc/rej_uniform_scalar/cbmc-proof.txt
- cbmc/rej_uniform_scalar/rej_uniform_scalar_harness.c
- mlkem/rej_uniform.c
Currently, rej_uniform_scalar and rej_uniform are basically the same if no native backend is used (as is the case with CBMC proofs). However, once we include the axiomatized call to native backend in the scope of CBMC, the proof will be simpler if we hoist out the contract for the scalar fallback.
> CBMC: Add separate proof for rej_uniform_scalar

- mlkem/arith_backend.h
- mlkem/fips202/fips202_backend.h
- mlkem/fips202/native/api.h
- mlkem/native/aarch64/src/clean_impl.h
- mlkem/native/aarch64/src/opt_impl.h
- mlkem/native/api.h
- mlkem/native/x86_64/src/default_impl.h
The backend API `mlkem/native/api.h` includes sanity checks on the arithmetic backend. For example, if a custom NTT domain coefficient ordering is defined, then the backend must provide native replacements for almost all functions, and they have to be adapted to the custom order.
Previously, however, `mlkem/native/api.h` was included _beffore_ the backend. This still served the purpose of ensuring that the native API is indeed what the backend implements, but it rendered the sanity checks effectless.
This commit fixes this by reordering the includes accordingly, in both the arithmetic and the FIPS-202 backend.
> Fix ordering of includes in arith/fips202 backend

- examples/custom_backend/mlkem_native/custom_config.h
- mlkem/common.h
- mlkem/config.h
- mlkem/fips202/native/aarch64/src/keccak_f1600_x1_scalar_asm_opt.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x2_v84a_asm_clean.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x2_v8a_v84a_asm_hybrid.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x4_scalar_v84a_asm_hybrid_opt.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm_opt.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm_opt.S
- mlkem/native/aarch64/src/intt_clean.S
- mlkem/native/aarch64/src/intt_opt.S
- mlkem/native/aarch64/src/ntt_clean.S
- mlkem/native/aarch64/src/ntt_opt.S
- mlkem/native/aarch64/src/poly_clean.S
- mlkem/native/aarch64/src/poly_opt.S
- mlkem/native/aarch64/src/polyvec_clean.S
- mlkem/native/aarch64/src/polyvec_opt.S
- mlkem/native/aarch64/src/rej_uniform_asm_clean.S
- mlkem/native/x86_64/src/basemul.S
- mlkem/native/x86_64/src/fq.S
- mlkem/native/x86_64/src/intt.S
- mlkem/native/x86_64/src/ntt.S
- mlkem/native/x86_64/src/shuffle.S
* Resolves #545 
We previously exported two versions of every assembly symbol, one prefixed with a leading underscore, one not. This was to accommodate both Apple and non-Apple platforms.
This commit removes duplicated assembly symbols by introducing separate namespace wrappers
- MLKEM_ASM_NAMESPACE, and
- FIPS202_ASM_NAMESPACE which wrap around the configurable {MLKEM,FIPS202}_NAMESPACE by adding a leading underscore for Apple systems (only).
> Remove double-namespacing for assembly symbols

- mlkem/indcpa.c
**Summary**:
Fixes unused buflen variable in gen_matrix_entry. Detected when importing the code to liboqs and running a build with `scan_build`.
**Do you expect this change to impact performance**: No
> Fixes unused buflen in gen_matrix_entry

- test/hal/hal.c
Fixes #552 
Disables -Wpedantic in hal/hal.c where the result of calling dlsym() needs to be converted from "void *" to the appropriate function-pointer type, which normally generates a warning or error with GCC 14.
All tests pass
"tests bench -r -c M1" now works on macOS with GCC 14.2.0
lint passes
No expected performance impact
> Fix macOS build of benchmark test with GCC 14

- .github/workflows/ci_ec2_container.yml
bcef8f63034f1203abd22646e90182a776a47e39 already tried to do this, but one the ec2 container tests were missed.
> CI: Don't suppress output of `make quickcheck`

- .github/actions/setup-apt/action.yml
- .github/actions/setup-yum/action.yml
- .github/dependabot.yml
- BUILDING.md
- README.md
- requirements.txt
- scripts/tests
This PR eliminates the last pip dependency `click` and adjusts CI and documentation accordingly. 
* Fix https://github.com/pq-code-package/mlkem-native/issues/565
* Fix https://github.com/pq-code-package/mlkem-native/issues/559
> Eliminate `click` pip dependency

- mk/auto.mk
https://github.com/pq-code-package/mlkem-native/commit/b94f8ce2e47e26ae93a54f0c6a04e83ebbec6360 broke the automatic detection of x86 systems and lead to the native x86 backend not being used unless `-mavx2` is passed specifically. The issue is lazy vs. eager evaluation of ARCH_FLAGS within CFLAGS: with := the variable is eagerly evaluated at time of definition, while with += it is lazily evaluated. This matters since auto.mk sets default ARCH_FLAGS only later based on your system. Setting the ARCH_FLAGS in auto.mk thus had no effect. 
This commit changes `auto.mk` to directly modify the CFLAGS instead of the ARCH_FLAGS. This resolves the issue of the x86 backend not being used by default. We may want to eliminate ARCH_FLAGS altogether in a follow up PR.
Fixes #577
> Fix x86 default flags

- BUILDING.md
Clarify that nix should be setup using installer script.
> Split BULDING.md in building vs. developing

- BUILDING.md
- Makefile
- mk/config.mk
- scripts/tests
Currently, when CYCLES is not set explicitly when
building the benchmarking binaries, we default to
NO which results in all 0 cycle counts which is
confusing.
This commit changes the buidl so that it fails
with a error when attempting to build the benchmarking binaries without explicitly setting CYCLES.
> Force explcit CYCLES make variable for benchmarking

- .github/actions/bench/action.yml
- mk/config.mk
- scripts/lib/mlkem_test.py
- scripts/tests
Previously, we distinguished between CFLAGS and ARCH_FLAGS in the `Makefile` and the `tests` script. Ultimately, however, they are both just flags passed to the compiler, and the semantic difference is not worth highlighting at the level of the Makefile and tests script. This commit thus removes ARCH_FLAGS and uses CFLAGS instead.
The CI workflows so far retain their `archflags` parameter, but it is passed as `--cflags` to the `tests` script.
> Remove ARCH_FLAGS from test script and Makefile

- mk/rules.mk
When we build archive files for mlkem-native, we check for duplicated
symbols by linking the target library against a dummy .c file. The
ad-hoc compiler invocation used for this did not use and `-z noexecstack`
flag which led to linker warnings.
This commit addresses this by passing the same CFLAGS to the dummy compilation
as we use in the rest of the build, which in particular includes `-z noexecstack`. The 
only exception is `-static`, which is part of the CFLAGS for the library build, but dropped
for the dummy compilation.
* Fix #590
> Fix linker warning when checking for duplicated symbols

- .github/actions/functest/action.yml
- .github/actions/multi-functest/action.yml
- Makefile
- mk/config.mk
- scripts/lib/mlkem_test.py
Previously, `tests` would automatically detect which QEMU binary to use for emulation. With this commit, this is instead made explicit in the logic of the workflow. This is a step towards simplifying the `tests` script and eventually replacing it by calls to `make`.
> Tests/CI: Move QEMU choice logic from `tests` into workflow

- mk/rules.mk
* Fixes #607 
When checking for duplicated symbols, we build a temporary `a.out` binary by linking a dummy C file against libmlkem{512,768,1024}.a. Afterwards, `a.out` is removed.
When running multiple `make` jobs in parallel, this can lead to a race condition where multiple jobs create and destroy `a.out` at the same time.
This commit fixes this by using a temporary filename derived from the library target, hence avoiding the nameclash and race condition.
> Makefile: Fix race condition during duplicated symbol checking

- Makefile
- mk/bench.mk
- mk/bench_components.mk
- mk/schemes.mk
Previously, `make bench` or `make bench_components` would add hal.c to SOURCES, which would make it part of the libmlkemXXX.a libraries. That should not be so, and the HAL implementation instead be compiled alongside the benchmarking source. This commit changes the Makefiles accordingly.
* Fixes #601 
* Fixes #515
> Makefile: Don't include HAL into libmlkem.a when building benchmarks

- BUILDING.md
- Makefile
- README.md
- mk/rules.mk
- scripts/lib/mlkem_test.py
- scripts/lib/util.py
- scripts/tests
* Based on #602 
* Based on #599 
* Based on #608 
This PR simplifies `tests` to merely become a wrapper around various `make` invocations, which are printed. The only exceptions are:
* Benchmarking: Here, `tests` additionally does some postprocessing
* GH summary generation
> Make `tests` a shallow wrapper around `make`

- scripts/lib/mlkem_test.py
The `--cross-prefix` argument for the `tests` script defaults to `""`, not `None`. This led to the `mlkem_test.py` script incorrectly printing `Cross` to the github log where it should have printed `Native`. This commit fixes this.
> Tests: Fix detection of cross_prefix argument

- cbmc/Makefile.common
- examples/monolithic_build/mlkem_native_all.c
- mlkem/cbmc.h
- mlkem/fips202/fips202.c
- mlkem/indcpa.c
- mlkem/ntt.c
- mlkem/reduce.h
- mlkem/rej_uniform.c
- mlkem/sys.h
- mlkem/verify.h
STATIC_TESTABLE and STATIC_INLINE_TESTABLE were previously used as wrappers
around `static` and `static inline` that were defined as empty for a CBMC
build, thereby lifting visibility of static (inline) functions so that CBMC
would see them.
This commit achieves the same without STATIC_TESTABLE and
STATIC_INLINE_TESTABLE, both of which are removed, by defining `static`
and `INLINE` as the empty string in a CBMC build.
> Remove STATIC_TESTABLE and STATIC_INLINE_TESTABLE wrappers

- scripts/format
* Fix #614 
The examples in `examples/` contain many symlinks to the mlkem-native source files. Previously, `format`, and specifically `clang-format` invoked by it, would follow those symlinks and replace them by a copy of the modified file if the linked file needed re-formatting. This is not desirable: _only_ the file behind the symlink should be changed.
This commit fixes `format` by not running `clang-format` on symlinks.
> Format: Ignore symlinks

- .github/actions/functest/action.yml
- .github/workflows/ci.yml
Previously, the compiler test in the CI would only exercise various
compilers, but not various C standards.
This commit generalizes the compiler test to test compilation with
all combinations of {gcc-4.8, gcc-4.9, gcc-7, gcc-11, gcc-13, gcc-14,
clang-18} and {c90, c99, c11, c17}.
> CI: Generalize compiler test to exercise various C standards

- examples/monolithic_build/mlkem_native_all.c
- scripts/autogenerate_files.py
Every little change causes the line numbers in the mlkem_native_all.h in the  monolithic build to change. This makes reviewing PRs quite annoying and will likely cause some unnecessary merge conflicts.
This commit removes the line numbers.
> Monolithic build: remove line numbers

- .clang-format
- examples/monolithic_build/Makefile
- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/cbd.c
- mlkem/cbd.h
- mlkem/common.h
- mlkem/indcpa.c
- mlkem/indcpa.h
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/rej_uniform.c
- mlkem/rej_uniform.h
This commit introduces the marker MLKEM_NATIVE_INTERNAL_API. This marker is used in front of every declaration and implementation of an API that has external linkage for the standard build process of mlkem-native, but is not part of mlkem-native's public API.
Beyond being an explicit reminder to consumers that they can not rely on the stability of an API so marked as internal, the marker can be unfolded to the `static` keyword for monolithic builds, thereby giving internal linkage to all internal functions. This enables further compiler optimizations, and also removes the corresponding symbols from the resulting monolithic object file.
> Add marker for non-public API

- mlkem/cbd.c
- mlkem/cbd.h
- mlkem/cbmc.h
- mlkem/indcpa.c
- mlkem/indcpa.h
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/rej_uniform.c
- mlkem/rej_uniform.h
- mlkem/verify.h
This PR modifies the CBMC predicates `forall(...)`,
`array_bound(...)` and `array_abs_bound` to use exclusive
upper bounds for the indices.
This simplifies all call sites which previously manually issued
a `-1` to get from an array length to a maximal index.
It will also enable switching to unsigned loop indices everywhere;
the previous versions of `forall(...)`, `array_bound(...)` and
`array_abs_bound(...)` prevented this because they did not work
with the exclusive unsigned upper bound `0`.
Note that the _coefficient_ bounds are not changed and remain inclusive.
> CBMC: Use exclusive upper bounds for `forall` primitive

- cbmc/KeccakF1600_StateExtractBytes_BE/KeccakF1600_StateExtractBytes_be_harness.c
- cbmc/KeccakF1600_StateExtractBytes_BE/Makefile
- cbmc/KeccakF1600_StateExtractBytes_BE/cbmc-proof.txt
- cbmc/KeccakF1600_StateXORBytes_BE/KeccakF1600_StateXORBytes_be_harness.c
- cbmc/KeccakF1600_StateXORBytes_BE/Makefile
- cbmc/KeccakF1600_StateXORBytes_BE/cbmc-proof.txt
- cbmc/run-cbmc-proofs.py
- mlkem/fips202/keccakf1600.c
- mlkem/sys.h
Those functions have an explicit distinction between little and big endian systems and therefore need a proof for either case.
Care has to be taken to allow overwriting the directives in the host system's preprocessor; we disable the auto-detection of endianness if SYS_LITTLE_ENDIAN or SYS_BIG_ENDIAN have been set manually.
> CBMC: Big-endian proofs for KeccakF1600_State{Extract,XOR}Bytes

- examples/custom_backend/mlkem_native/custom_config.h
- examples/monolithic_build/config_1024.h
- examples/monolithic_build/config_512.h
- examples/monolithic_build/config_768.h
- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/common.h
- mlkem/config.h
- mlkem/mlkem_native.h
Previously, the user could customize namespacing by providing macros `MLKEM_NAMESPACE(sym)` and `FIPS202_NAMESPACE(sym)`.
This mode of configuration is slightly inconvenient in that the namespace cannot be controlled from CFLAGS.
This commit addresses this, as follows: Instead of making the namespace macro configurable, make the namespace _prefix_ configurable, and derive the namespace macro: The config provides MLKEM_NAMESPACE_PREFIX and FIPS202_NAMESPACE_PREIFX, and then the derived MLKEM_NAMESPACE(sym) and FIPS202_NAMESPACE(sym) are the concatenation of that, an underscore `_`, and the symbol name `sym`.
All configs and examples are adjusted accordingly.
> Configure namespace prefix instead of namespace macro

- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/cbd.c
- mlkem/cbd.h
- mlkem/cbmc.h
- mlkem/indcpa.c
- mlkem/indcpa.h
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/params.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/reduce.h
- mlkem/rej_uniform.c
- mlkem/rej_uniform.h
* Resolves #324 
Previously, the coefficient bounds in `array_bound(...)` and `array_abs_bound(...)` were inclusive. This was somewhat inconvenient since (a) it required a lot of `-1` in places where the exclusive upper bound was more natural to work woth, and (b) it was a deviation from the runtime debug assertions `POLY_BOUND` which would use exclusive bounds.
This commit switches `array_bound` to use an exclusive upper bound. The lower bound remains inclusive. For `array_abs_bound`, we switch to an exclusive absolute bound.
The macro `UINT12_MAX` (mapping to 4095) is replaced by UINT12_LIMIT, mapping to 4096. Uses of `array_abs_bound(..., UINT12_MAX) are replaced by `array_bound(..., 0, UINT12_LIMIT)`, since we never deal with negative numbers bound by UINT12_LIMIT.
> CBMC: Switch to exclusive coefficient upper bounds

- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/debug/debug.c
- mlkem/debug/debug.h
* Fixes #644 
The debug functions in `debug/debug.c` so far depended on
`snprintf()`, which was added to the stdlib in C99.
To still be able to use it when C90 is used as the language
standard, the _ISOC99_SOURCE macro was manually set before
including `stdio.h`.
This is problematic even if we don't care about C90 debug mode, for two reasons:
- If mlkem-native is used in a monolihic (single-CU) build,
the _ISOC99_SOURCE macro may already be set, leading to an
error.
- More problematically, the monolithic build of mlkem-native
undefines all defines, including `_ISOC99_SOURCE`, which
may alter or break compilation of other sources to come.
Both could in principle be fixed, but it seems better to
simply avoid reliance on `_ISOC99_SOURCE`.
This commit removes the need for `_ISOC99_SOURCE` by …
> Debug: Avoid reliance on C99 snprintf()

- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/debug/debug.h
- mlkem/indcpa.c
- mlkem/native/aarch64/src/clean_impl.h
- mlkem/native/aarch64/src/opt_impl.h
- mlkem/native/x86_64/src/default_impl.h
- mlkem/ntt.c
The numeric macros NTT_BOUND_NATIVE and INVNTT_BOUND_NATIVE could be used by backends to specify an output bound for the forward and inverse NTT. We would then use STATIC_ASSERT's to check that those backend-specific bounds would imply the bounds (NTT_BOUND and INVNTT_BOUND) that the CBMC proofs work against.
The added value of NTT_BOUND_NATIVE and INVNTT_BOUND_NATIVE is questionable. In the end, what we care about is that the native NTT and invNTT adhere to the bounds that CBMC relies on. Any strengthening of the bounds may be good to know, but is otherwise an unnecessary complication of the code.
This commit removes NTT_BOUND_NATIVE and INVNTT_BOUND_NATIVE and uses the contractual bounds NTT_BOUND and INVNT_BOUND in their place.
------
Also, remove the need for `STATIC_ASSERT` by …
> Remove NTT_BOUND_NATIVE and INVNTT_BOUND_NATIVE

- scripts/tests
* Fixes https://github.com/pq-code-package/mlkem-native/issues/652
Previously, `tests bench` and `tests bench --opt=ALL`  would only run the opt benchmarks. This was because of a bug in the helper `do_opt_all()` in the `tests` script. This commit fixes this bug, thereby restoring the desired behaviour.
> Fix `tests bench [--opt=ALL]` so it runs opt and non-opt benchmarks

- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/cbmc.h
- mlkem/debug/debug.c
- mlkem/debug/debug.h
- mlkem/indcpa.c
- mlkem/ntt.c
- mlkem/ntt.h
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/polyvec.h
- mlkem/reduce.h
Previously, debug.h provided a host of bounds checking assertions, such as POLY_BOUND, POLY_UBOUND, POLY_BOUND_MSG, POLYVEC_BOUND, ...
This commit simplifies debug.h by reducing to three assertions
- debug_assert: For any boolean valued assertion
- debug_assert_bound: For a lower+upper bounds assertion on an array, akin to the CBMC assertion array_bound
- debug_assert_abs_bound: For an absolute bounds assertion on an array, akin to the CBMC assertion array_abs_bound.
Moreover, assertion strings are removed: The filename and linenumber already provide enough information to locate the issue when an assertion fails -- the additional text clutters the code and doesn't add much.
While adjusting the code, two smaller issues were noted and fixed:
- The debug assertions had gone out of sync with …
> Debug: Reduce number of macros, assimilate to CBMC assertions

- mlkem/cbd.c
- mlkem/cbmc.h
- mlkem/fips202/keccakf1600.c
- mlkem/indcpa.c
- mlkem/ntt.c
- mlkem/poly.c
- mlkem/verify.h
- proofs/cbmc/invntt_layer/invntt_layer_harness.c
- proofs/cbmc/ntt_butterfly_block/ntt_butterfly_block_harness.c
- proofs/cbmc/ntt_layer/ntt_layer_harness.c
- proofs/cbmc/proof_guide.md
Previously, we were using `int` as the type of loop indices, which requires loop invariants of the form `0 <= i`.
With the recent switch to `unsigned` indices, those invariants are automatic and can be removed for improved readability. This commit does that.
Along the way, it is noticed that some of the NTT proofs still used integral loop indices. Those are changed along the way.
> CBMC: Remove redundant `0 <= ...` assertions in loop invariants

- README.md
- RELEASE.md
- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/cbmc.h
- mlkem/debug/debug.h
- mlkem/indcpa.c
- mlkem/poly.c
- mlkem/poly.h
- mlkem/polyvec.c
- mlkem/reduce.h
- mlkem/rej_uniform.c
- proofs/cbmc/poly_basemul_montgomery_cached/Makefile
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached/Makefile
- proofs/cbmc/polyvec_compress_du/Makefile
* Based on #663 
Previously, runtime assertions via debug_assert_xxx and CBMC
assertions via cassert(...) were separate.
This commit modifies the implementation of the debug assertion
macros so that when CBMC is used, debug assertions are intepreted
as proof obligations.
This removes some redundancy and non-uniformity in the code,
and also reduces the likelihood that debug assertions and CBMC
contracts get out of sync. In some case, this actually happened,
and the commit fixes this. The commit also adds further bounds
assertions in alignment with pre/post conditions.
A slight nuisance is that the debug assertions cannot flatten
nested structures like polyvec for the bounds check, running
into issue https://github.com/diffblue/cbmc/issues/8570. We
work around this by introducing a new …
> Turn debug assertions into CBMC constraints when CBMC is used

- examples/monolithic_build/mlkem_native_monobuild.c
- scripts/autogen
Previously, the generation of the monobuild compilation unit using `autogen` would generate one `#undef` clause for every `#define` found in a file. If a single macro was defined multiple times in different branches, multiple #undef's would be generated.
This commit fixes `autogen` to only emit one `#undef ...` clause per macro per file. This is done by omitting the no longer used line number information from the function yielding the defines. Since the function is gathered into a set, this automatically removes duplicates.
> autogen: Don't generate multiple #undef's for the same macro

- mlkem/native/aarch64/src/intt_clean.S
- mlkem/native/aarch64/src/intt_opt.S
- mlkem/native/aarch64/src/ntt_clean.S
- mlkem/native/aarch64/src/ntt_opt.S
- mlkem/native/aarch64/src/poly_clean.S
- mlkem/native/aarch64/src/poly_opt.S
- mlkem/native/aarch64/src/polyvec_clean.S
- mlkem/native/aarch64/src/polyvec_opt.S
- mlkem/native/aarch64/src/rej_uniform_asm_clean.S
This commit removes all literal pools from the native AArch64 assembly. Those literal pools are slightly easier to read, but impede verification using HOL-Light. Instead, constant vectors are prepared by loading immediates into GPRs and copying/broadcasting them into the target vector.
> AArch64: Remove literal pools from native code

- mlkem/compress.c
- mlkem/indcpa.c
- mlkem/native/aarch64/src/clean_impl.h
- mlkem/native/aarch64/src/opt_impl.h
- mlkem/native/api.h
- mlkem/native/x86_64/src/arith_native_x86_64.h
- mlkem/native/x86_64/src/basemul.c
- mlkem/native/x86_64/src/default_impl.h
- mlkem/poly.c
- mlkem/poly_k.c
* Based on #674 
This PR modifies the backend API to work directly with int16_t arrays rather than the poly_xxx structures.
> Backend API: Remove dependence on poly_* structs

- .github/workflows/integration-liboqs.yml
- integration/liboqs/ML-KEM-1024_META.yml
- integration/liboqs/ML-KEM-512_META.yml
- integration/liboqs/ML-KEM-768_META.yml
- integration/liboqs/liboqs-check-filelist.py
- nix/util.nix
liboqs requires META files providing meta data on the available implementations and required flags for building them.
To ease integration, we include the files in mlkem-native.
This commit also adds script that checks that the source list is kept up to date and runs it in CI.
> Integration: Add liboqs META files

- proofs/cbmc/Makefile.common
"make result" is very useful for checking individual proofs. This commit amends this Makefile target to display the last 4 lines of logs/results.txt following by any lines that contain the string "FAILURE".
This saves the user having to do "less logs/result.txt" (or similar) after every "make result".
For example, a successful proof now concludes:
```
Report was rendered at file:///tmp/nix-shell.kX96Ad/litani/runs/latest/html/index.html
** 0 of 11 failed (1 iterations)
VERIFICATION SUCCESSFUL
```
while a failing proof might show:
```
Report was rendered at file:///tmp/nix-shell.kX96Ad/litani/runs/latest/html/index.html
** 1 of 11 failed (2 iterations)
VERIFICATION FAILED
[PQCP_MLKEM_NATIVE_MLKEM768_scalar_compress_d11.postcondition.2] line 234 Check ensures clause of contract …
```
> Modify the CBMC Makefile "result" target to actually display proof results.

- scripts/tests
Simple correction to Python to correctly pass the self.args.mac_taskpolicy
variable to the underlying execution command.
> Correct setting of macOS taskpolicy variable

- .github/actions/ct-test/action.yml
- .github/workflows/ci.yml
- .github/workflows/ct-tests.yml
- flake.lock
- flake.nix
- mlkem/indcpa.c
- mlkem/kem.c
- test/notrandombytes/notrandombytes.c
- test/test_mlkem.c
Resolves #462 
This extends the mlkem-native tests to support Valgrind-based constant-time tests following the ct-grind approach proposed by Adam Langley in https://github.com/agl/ctgrind.
The basic idea is to mark all output of randombytes as undefined (=secret). Valgrind will then track all values derived from that through the program and warn about any conditional branches and memory addressed depening on it.
In Kyber this leads to multiple false positives (i.e., branches depending on values that are actually public), that we resolve by explicitly declassifying that data (i.e., marking it defined). The cases where this happens are as follows:
1) In key generation: The expansion of the public matrix A uses rejection
sampling which contains conditional branches. The seed used for that
is …
> Add Valgrind-based constant-time tests

- .github/actions/ct-test/action.yml
- .github/workflows/ct-tests.yml
- flake.nix
- mlkem/compress.h
- nix/util.nix
- nix/valgrind/README.md
- nix/valgrind/default.nix
- nix/valgrind/valgrind-varlat-patch-20240808.txt
This commit builds on top of
https://github.com/pq-code-package/mlkem-native/pull/687
which added Valgrind-based constant-time tests detecting
secret-dependent memory accesses and conditional branches.
This commit extends this to also detect secret-dependent
divisions such as those that lead to the KyberSlash
vulnerability.
See https://kyberslash.cr.yp.to/.
We test for that by using the patch to Valgrind proposed
in the KyberSlash paper (see same link).
It adds an option --variable-latency-errors=no|yes to valgrind
which defaults to no. If you set it to yes, it will complain if
you use undefined in division instructions.
This patch has also been sent to the valgrind developers, but was
so far not merged. Luckily our nix setup makes it very easy to
add a patched valgrind and cache it in …
> Add Valgrind-based detection of variable-latency instructions

- .github/workflows/ci.yml
Github recently added Arm64 runners. They are currently in public beta: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
We can potentially replace the pqcp Arm64 runners with that.
> Test: Add Github ubuntu-24.04-arm runners

- mlkem/fips202/native/aarch64/src/keccak_f1600_x1_scalar_asm_opt.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x4_scalar_v84a_asm_hybrid_opt.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm_opt.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_v84a_scalar_hybrid_asm_opt.S
- mlkem/native/aarch64/src/intt_clean.S
- mlkem/native/aarch64/src/intt_opt.S
- mlkem/native/aarch64/src/ntt_clean.S
- mlkem/native/aarch64/src/ntt_opt.S
- mlkem/native/aarch64/src/poly_clean.S
- mlkem/native/aarch64/src/poly_opt.S
- mlkem/native/aarch64/src/polyvec_clean.S
- mlkem/native/aarch64/src/polyvec_opt.S
- mlkem/native/aarch64/src/rej_uniform_asm_clean.S
Resolves https://github.com/pq-code-package/mlkem-native/issues/702
This adds .balign 16 to all global assembly functions to resolve some warnings that show up with gcc 14.2.0.
I also switched all .align's to .balign for consistency. .balign 4 seems to be prefered over .align 4 for aligning to a 4-byte boundary as it is more consistent accross systems (balign always takes bytes, while align takes bytes one some systems and the two-power on most systems).
> Add balign to all AArch64 asm

- mlkem/compress.c
- mlkem/native/api.h
- mlkem/native/x86_64/src/arith_native_x86_64.h
- mlkem/native/x86_64/src/compress_avx2.c
- mlkem/native/x86_64/src/default_impl.h
- test/test_mlkem.c
This commit extends the arithmetic natice interface by the
polynomial compression routines
- poly_compress_d4
- poly_compress_d5
- poly_compress_d10
- poly_compress_d11
- poly_decompress_d4
- poly_decompress_d5
- poly_decompress_d10
- poly_decompress_d11
It also imports the native implementation in AVX2 intrinsics
provided by the official Kyber implementation.
Care has to be taken to not overflow the input buffer during
the vectorization. The official Kyber implementation _does_
overflow them, but ensures at the call-sites that sufficient
space is available, and that no relevant data is overwritten.
While this seems to work, it is difficult to reason about this
code, and it moreover prevents a unified interfaces for the native
(de)compression routines.
To remedy, this commit adds …
> Add AVX2 native polynomial compress/decompression

- README.md
- proofs/hol_light/arm/README.md
This will be addressed through #712, but until then we should be clear that we do not yet claim that mlkem-native's AArch64 [inv]NTT are formally verified.
> Clarify that HOL-Light proofs are not yet synced with shipped ASM

- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/README.md
The HOL-Light/s2n-bignum proofs expect ELF formatted object files, but compilation on MacOS produces Mach-O object files.
This commit modifies the makefile for the HOL-Light proofs in mlkem-native to explicitly convert from Mach-O to ELF using gobjcopy.
Unfortunately, there does not seem to be a way to get a version of `objcopy` through `nix` that supports the required conversion, hence we need to fall back to documentation and expressive error messages to nudge the user to manually install `gobjcopy` via `brew install binutils` when it cannot be found.
> HOL-Light: Add support for MacOS

- .github/workflows/ct-tests.yml
We were running the Valgrind tests both with stock Valgrind, and a patched version to also detect variable-latency instructions. The latter can detect anything the former can and since both are working fine in CI, we can simply drop running the former in CI.
This may cause problems in the future when updating Valgrind in case the patch no longer applies. But we can still switch back in that case. I've left a note.
> CI: Only run constant-time tests using patched Valgrind

- scripts/check-namespace
- scripts/format
- scripts/lint
- scripts/simpasm
The simpasm script was only included in the format script, but not in the lint script. Wrong formatting was, hence, not detected before.
This commit fixed the formatting and also adds the script to the linter.
Same applies to the check-namespace script.
> Properly lint+format all Python scripts

- examples/monolithic_build/Makefile
- examples/monolithic_build/config_1024.h
- examples/monolithic_build/config_768.h
- examples/monolithic_build/main.c
- examples/monolithic_build_multilevel/Makefile
This commit modifies the examples `monolithic_build` and `monolithic_build_multilevel` to create `libmlkemXXX.a` build artifacts as intermediate results, before linking against the application source.
Those intermediates are good targets for future code-size measurements, because in a monobuild the compiler has visibility into what is public and what is internal.
> Monobuild: Build library file as intermediate

- .github/workflows/bench.yml
The SpacemiT K1 8 (Banana Pi F3) supports the RV vector extension
with 512-bit vectors.
Currently, in our benchamrks this remains unused as we compile with
`-march=rv64imafdc_zicsr_zifencei`.
Changing this to
`-march=rv64imafdcv_zicsr_zifencei` will make use of vector instructions
resulting in a significant speed-up.
| Benchmark suite | Current: a41d163217fd0482e7b5995c2038495b0e12d0fd | Previous: df9eb51fa5e87f09e101ce5dd30ff690f6e77fc7 | Ratio |
|-|-|-|-|
| `ML-KEM-512 keypair` | `225141` cycles | `308758` cycles | `0.73` |
| `ML-KEM-512 encaps` | `269656` cycles | `412471` cycles | `0.65` |
| `ML-KEM-512 decaps` | `343348` cycles | `554475` cycles | `0.62` |
| `ML-KEM-768 keypair` | `371206` cycles | `505135` cycles | `0.73` |
| `ML-KEM-768 encaps` | `429962` cycles | `635555` cycles | …
> Benchmarking: Use vector instructions on Banana Pi F3 

- .github/actions/ct-test/action.yml
- .github/actions/setup-shell/action.yml
- .github/workflows/ct-tests.yml
We are using a patched valgrind for the ct tests
which is built in CI and  then cached in the Github Cache. Currently we are using many different compilers for these tests. Currently, for each of these compilers valgrind is recompiled and cached taking up 600-800 MB per
each of the 26 compiler/arch combinations.
We only have 10 GB of cache, so we are constantly triggering cache evictions.
This leads to painfully slow tests for other tests that due to that have to recompile gcc which takes around 45 minutes.
This commit changes the cache key for valgrind to only contain the OS and arch, but not the compiler version.
> CI: Only cache one valgrind per arch

- .github/actions/bench/action.yml
- .github/workflows/bench.yml
- .github/workflows/bench_ec2_reusable.yml
https://github.com/pq-code-package/mlkem-native/pull/740 added
linters to the main ci nix shell - however that includes the
heavyweight LLVM. This breaks our benchmarking.
This commit switches to the more lightweight ci_gcc14 shell.
> Benchmarks: Switch to ci_gcc14 shell instead of ci

- .github/actions/bench/action.yml
- .github/workflows/bench.yml
- .github/workflows/bench_ec2_reusable.yml
- flake.nix
https://github.com/pq-code-package/mlkem-native/pull/747 switched the benchmarking from the ci shell to the ci-gcc14 shell. While this is sufficient for most platforms, it breaks benchmarks on platforms that do not run the Github actions locally, but instead need binaries copied over the network and run through ssh.
This PR fixes that as well and adds a new dedicated benchmarking shell which is the same as the ci shell prior to #740.
> Benchmarks: Add new benchmarking shell

- dev/aarch64_clean/src/rej_uniform_asm_clean.S
* Fix https://github.com/pq-code-package/mlkem-native/issues/749
> Fix include guard for clean AArch64 native implementation

- .github/actions/setup-brew/action.yml
- .github/actions/setup-os/action.yml
- .github/workflows/ci.yml
- Makefile.Microsoft_nmake
* Test Windows-2019, 2022, latest
* Also test MacOs-13, which is x86_64 based
* Along the way, make nmake file compatible with Windows 2019.
> CI: Add further Windows and MacOS tests

- examples/monolithic_build/mlkem_native_monobuild.c
- scripts/autogen
- scripts/format
This commit makes the monobuild file more configurable by guarding the inclusion of fips202 files, as well as the #undef'ing of the macros they define, by !defined(MLK_MONOBUILD_CUSTOM_FIPS202).
This is needed for monobuilds with a custom FIPS-202, AWS-LC being one example.
A comment is added that the `unifdef` tool is useful for statically simplifying the monobuild file for reduced configurations.
Piggy-backing is a commit making `format` faster.
> autogen/monobuild: Guard inclusion of FIPS-202 sources

- .github/workflows/ci.yml
- test/gen_KAT.c
- test/gen_NISTKAT.c
This commit adds a quickcheck using the Mingw-w64 compiler on Windows.
We install Mingw-w64 using Chocolatey which comes preinstalled on the
Github Windows runners.
To make the testvector hashes match, we need to set stdout to binary mode as
otherwise \n gets automatically converted to \r\n causing the hash to not match.
We add this behind preprocessor conditionals in gen_KAT.c and gen_NISTKAT.c.
Note that our Makefile heavily depends on having a Linux-like shell for commands
such as tr. We work around this by running the quickcheck in a bash shell
(which comes with Git for Windows which is preinstalled on the runners).
Resolves #745.
> Add Mingw-w64 quickcheck on Windows

- mlkem/kem.c
- test/notrandombytes/notrandombytes.c
- test/test_mlkem.c
Previously, valgrind CT tests would assume that the underlying randombytes() function would tag its output bytes as secret.
This commit changes this to explicitly tag the coins as secret in the ML-KEM source code.
This simplifies integration with other libraries using a custom randombytes() implementation, and makes the secret/declassify annotations with mlkem-native self-contained.
> CT: Mark random coins as secret outside of randombytes()

- .github/workflows/nix.yml
Github deprecated Ubuntu 20.04 action runners on 2025-02-01 and will stop supporting them 2025-04-01.
See https://github.com/actions/runner-images/issues/11101 This commit removes the single workflow (nix) where we do rely on the ubuntu-20.04 runners.
We remove them early as Github is scheduling brownouts starting March 4 to make people aware of this change.
> Remove ubuntu-20.04 jobs (due to GH deprecating the runners)

- .github/workflows/ci.yml
- mlkem/kem.c
- test/break_pct_config.h
This commit introduces a config option MLK_KEYGEN_PCT_BREAKAGE_TEST. When set, the user must provide a runtime (!) function mlk_break_pct() to indicate if the PCT should be made fail. If set, the shared secret in the PCT will be deliberately corrupted to make the PCT fail. A test is added to exercise the runtime breakage logic.
> Add runtime option to break PCT

- .github/workflows/bench.yml
We are currently expierencing some issues with out benchmarking CI due to one of our self-hosted runners dying last night.
This commit remporarily disables the affected jobs until the runner has been restored.
> CI: temporarily disable A72, A55, BPi

- mlkem/debug.h
When CBMC, debug assertions are transformed into proof obligations in debug.h. For this, debug.h includes cbmc.h, but using the wrong include path "../cbmc.h" which is still a remnant of debug.[ch] living in a separate debug/ directory. This only works because fips202/ happens to be another directory in the include path.
This commit fixes this minor slip by including "cbmc.h" from debug.h directly.
> CBMC: Fix include path

- dev/aarch64_clean/src/aarch64_zetas.c
- dev/aarch64_clean/src/arith_native_aarch64.h
- dev/aarch64_clean/src/clean_impl.h
- dev/aarch64_clean/src/intt_clean.S
- dev/aarch64_clean/src/ntt_clean.S
- dev/aarch64_opt/src/aarch64_zetas.c
- dev/aarch64_opt/src/arith_native_aarch64.h
- dev/aarch64_opt/src/intt_opt.S
- dev/aarch64_opt/src/ntt_opt.S
- dev/aarch64_opt/src/opt_impl.h
- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/native/aarch64/src/aarch64_zetas.c
- mlkem/native/aarch64/src/arith_native_aarch64.h
- mlkem/native/aarch64/src/intt_opt.S
- mlkem/native/aarch64/src/opt_impl.h
- proofs/hol_light/arm/mlkem/mlkem_intt.S
- scripts/autogen
- scripts/check-magic
The C code and other documentation consistently refer to the "layers" of the NTT as "1" through "7".
Previously, the assembly language back-end for AArch64 referred to the layers as "0" through "6".
This PR changes the AArch64 back-end to use "1" through "7" for consistency with the C code throughout.
The Intel back-end is unaffected.
> Normalize naming of NTT Layers

- .github/workflows/bench.yml
This reverts commit cc65ed24dfda5b46154fed7430c32a130bca9071.
The runner should be restored now.
> Renable benchmarks on A72, A55, BPi

- .github/actions/cbmc/action.yml
- .github/actions/setup-nix/action.yml
- .github/workflows/ci_ec2_reusable.yml
- .github/workflows/ct-tests.yml
- .github/workflows/nix.yml
- flake.lock
- flake.nix
- nix/cbmc/default.nix
- nix/util.nix
- scripts/simpasm
- test/mk/auto.mk
- test/mk/rules.mk
**Summary**:
- Upgrade nix channel to 24.11
- Keep 24.05 for gcc48 and gcc49, as both are deprecated in 24.11.
- Clean up redundant Nix wrapper functions for easier maintenance.
- Set Clang 15 as the default compiler for macOS to prevent namespace checking issues in CI (Clang 16 seems to cause failures). A follow-up PR is needed to properly resolve this.
- As noted in `nix/util.nix`: 
- Tools in /Library/Developer/CommandLineTools/usr/bin on macOS are inaccessible in the Nix shell. This issue is addressed in https://github.com/NixOS/nixpkgs/pull/353893 but hasn’t been merged into the 24.11 channel yet. As a workaround, we include the `git` dependency for macOS temporary. 
- Refactored Nix installation and cache setup in setup-nix action:  
- Nix cache is now built per os-arch instead of …
> Upgrade nix to use 24.11 channel

- REFERENCE.md
- mlkem/compress.c
- mlkem/compress.h
- mlkem/indcpa.c
- mlkem/kem.c
- mlkem/poly.c
- mlkem/poly_k.c
- mlkem/sampling.c
- mlkem/verify.h
* Resolves https://github.com/pq-code-package/mlkem-native/issues/785
This commit adds `/* Reference: ... */` annotations for the
mlkem-native source code, outlining on a per-function basis
the connection to the reference implementation.
It also adds a REFERENCE.md file summarizing the deviations.
Signed-off-by: Hanno Becker <beckphan@amazon.co.uk>
> Document relation to reference implementation

- mlkem/poly.c
In most places in the code, we use magic constants with `check-magic: ...` annotations explaining their origin, rather than computing the magic constant in the code and relying on constant evaluation by the compiler.
One place where this was not done is `barrett_reduce()`, where the 'magic' Barrett multiplier was computed in C.
This commit aligns `barrett_reduce()` to other routines relying on magic constants, by hardcoding the magic value in C, and adding a `check-magic: ...` annotation to explain its origin.
> Poly: Hardcode barrett multiplier

- dev/fips202/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
The 1-fold Keccak-F1600 implementation based on v8.4-A Neon instructions uses a 0-lane LD2/ST2 to load/store the Keccak-F1600 state from memory. The upper halves of the Neon registers are unused.
This commit simplifies this by instead using a LDP/LDR targeting the D-forms of the Neon registers.
This matches the version verified by @jargh
> Keccak-F1600: Use d-form LDP/LDR instead of LD2

- .github/workflows/cbmc.yml
- .github/workflows/ci.yml
**Summary**:
Using workflow_run to make CI and CBMC depend on the completeness of Base workflow
But this can only work after the PR is merged into main
**Steps**:
**Do you expect this change to impact performance**: Yes/No
> Make CI and CBMC workflows depend on Base workflow

- .github/workflows/cbmc.yml
- .github/workflows/ci.yml
**Summary**:
workflow triggered by workflow_run wont be rendered in a PR, which is not ideal.
We should probably go with resuing workflows instead
**Steps**:
If your pull request consists of multiple sequential changes, please describe them here:
**Do you expect this change to impact performance**: Yes/No
> Revert using workflow_run

- .github/workflows/base.yml
For some reason this one was missing.
> Add monolithic_build_multilevel_native to examples CI

- .github/workflows/cbmc.yml
We have seen spurious failures in CBMC which we suspect to be related to the available RAM on the CBMC runners. This commit increases the amount of RAM on the CBMC runners to validate this theory.
> CI: Run CBMC on c7g.4xlarge instead of c7g.2xlarge

- integration/liboqs/ML-KEM-1024_META.yml
- integration/liboqs/ML-KEM-512_META.yml
- integration/liboqs/ML-KEM-768_META.yml
- integration/liboqs/config_aarch64.h
- integration/liboqs/config_c.h
- integration/liboqs/config_x86_64.h
- integration/liboqs/liboqs-check-filelist.py
This commit moves the various compile-time options for OQS integration into custom configs `integration/liboqs/config_{c,x86_64,aarch64}.h`.
It also maps the constant-time testing flag CT_TESTING_ENABLED used in libOQS to MLK_CT_TESTING_ENABLED used by mlkem-native.
> Integration/OQS: Add custom configs

- .github/workflows/base.yml
- .github/workflows/bench_ec2_reusable.yml
- .github/workflows/ci_ec2_container.yml
- .github/workflows/ci_ec2_reusable.yml
- .github/workflows/scorecard.yaml
- mlkem/poly.c
- proofs/cbmc/invntt_layer/invntt_layer_harness.c
- proofs/cbmc/ntt_layer/ntt_layer_harness.c
- test/mk/rules.mk
The n-th layer of the NTT needs the zeta table entries at indices `2^(n-1)..2^n-1`. Previously, the initial index was computed using a division by the `len` parameter, upholding the status of the `layer` parameter as a pure ghost variable only needed for the specification, but not the code itself.
This commit gives up the status of `layer` as a ghost variable and instead uses it to compute the initial zeta index using a shift instead of a division.
While `len` is not secret and there is, thus, no risk of information leakage when a `div` instruction is used, it still seems cleaner and faster to work with a shift.
* Resolves #828 
Suggested-by: @rod-chapman
> NTT: Simplify computation of zeta index

- .github/workflows/hol_light.yml
- dev/fips202/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
- mlkem/fips202/native/aarch64/src/keccak_f1600_x1_v84a_asm_clean.S
- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/mlkem/mlkem_keccak_f1600_alt.S
- proofs/hol_light/arm/proofs/mlkem_keccak_f1600_alt.ml
- scripts/autogen
This commit integrates the functional correctness proof for
the AArch64+SHA3 based implementation of Keccak-f1600-x1,
contributed by John Harrison.
> Add proof for AArch64+SHA3 Keccak-f1600-x1

- .github/workflows/hol_light.yml
- README.md
- dev/fips202/aarch64/src/keccak_f1600_x2_v84a_asm.S
- nix/hol_light/default.nix
- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/mlkem/keccak_f1600_x2_v84a.S
- proofs/hol_light/arm/proofs/keccak_f1600_x2_v84a.ml
- scripts/autogen
This commit adds the HOL-Light proof of functional corrrectness
for the v8.4-A+SHA3 based Keccak-f1600-x2 implementation; this
implementation is the default for Arm-based Macs in mlkem-native.
The proof was developed by John Harrison and uses the s2n-bignum
proof infrastructure.
A code change had to be made to align the assembly in mlkem-native
with the one proved correct in HOL-Light:
- Uses of ld2/st2 during loading/storing of the initial/final
Keccak state are replaced by manual ldp/stp+trn{1,2}.
- An unnecessary stack allocation is removed
- An unnecessary register alias is removed
> FIPS202/AArch64: Add HOL-Light proof for v8.4-A+SHA3-based Keccak-F1600-x2

- .github/workflows/base.yml
- BUILDING.md
- Makefile
- scripts/tests
- test/hal/hal.c
- test/mk/config.mk
It has been reported that the -c M1 cycle counting option does seem to work on some Intel Macs as well. This commit renames it to -c MAC and adjusts the documentation accordingly.
* Resolves #810
> Rename -c M1 option to -c MAC

- .github/workflows/hol_light.yml
This commit pins the action to a specific commit.
This addresses https://github.com/pq-code-package/mlkem-native/security/code-scanning/101
> Pin tj-actions/changed-files action

- scripts/autogen
- scripts/simpasm
- scripts/tests
Previously, those scripts would need to be called from the root directory of the repository. With this change, they can be called from anywhere within the repository.
* Resolves #847
> Scripts: Make simpasm, autogen, tests callable from any subdirectory

- dev/aarch64_opt/src/Makefile
- dev/aarch64_opt/src/README.md
- scripts/autogen
This PR adds a suitable Makefile and README.md that explains how to automatically run
SLOTHY on the "clean" AArch64 back-end to produce the "opt" back-end.
> Add a Makefile and documentation for automatically running SLOTHY

- .github/workflows/integration-liboqs.yml
This updates liboqs to the current version in main https://github.com/open-quantum-safe/liboqs/tree/bf515a36091e2bd1dd0fbfe8ce1747a45371312e
As
https://github.com/open-quantum-safe/liboqs/pull/2092 was merged upstream (which removed all remaining patching), we no longer need to remove the patching in the liboqs integration test.
**Summary**:
Provide a brief summary of your changes.
**Steps**:
If your pull request consists of multiple sequential changes, please describe them here:
**Do you expect this change to impact performance**: Yes/No
> Update liboqs to `bf515a3`

- .github/workflows/hol_light.yml
- README.md
- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/README.md
- proofs/hol_light/arm/mlkem/mlkem_poly_tomont.S
- proofs/hol_light/arm/proofs/mlkem_poly_tomont.ml
- scripts/autogen
This commit adds a HOL-Light functional correctness proof for the AArch64-native version of `poly_tomont`.
The proof is structurally similar to that for the NTT and re-uses core proof tools, esp. the lemma about correctness and bound of Barrett multiplications.
The proof executes in a few minutes on a modern machine, but it is notable how some proof steps are significantly slower than others -- similar to the NTT; the proof may be a good test ground for performance improvements.
* Resolves #838
> HOL-Light: Add correctness proof for poly_tomont

- .github/workflows/hol_light.yml
- proofs/hol_light/arm/proofs/keccak_f1600_x1_scalar.ml
- proofs/hol_light/arm/proofs/keccak_f1600_x1_v84a.ml
- proofs/hol_light/arm/proofs/keccak_f1600_x2_v84a.ml
- proofs/hol_light/arm/proofs/keccak_f1600_x4_v8a_scalar.ml
- proofs/hol_light/arm/proofs/keccak_f1600_x4_v8a_v84a_scalar.ml
- proofs/hol_light/arm/proofs/keccak_spec.ml
This commit imports the functional spec for Keccak in HOL into the mlkem-native source tree. Previously, those were indirectly imported from s2n-bignum as part of the runtime nix setup, preventing direct inspection of the assembly specs from the source tree.
The HOL-Light Github workflow is refined slightly to allow for the specification of per-proof dependencies.
* Resolves #863
> HOL-Light: Add functional Keccak spec

- .github/workflows/bench.yml
This commit adds a 2020 Apple M1 Mac Mini to our CI.
> Add Apple M1 Mac Mini (2020) to benchmarking CI

- .github/workflows/hol_light.yml
- README.md
- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/README.md
- proofs/hol_light/arm/mlkem/mlkem_poly_mulcache_compute.S
- proofs/hol_light/arm/proofs/mlkem_poly_mulcache_compute.ml
- proofs/hol_light/arm/proofs/mlkem_specs.ml
- scripts/autogen
* Resolves #842 
This commit adds a HOL specification and functional correctness
proof for the AArch64 native implementation of `poly_mulcache_compute`.
> HOL-Light: Add spec & proof for poly_mulcache_compute

- .github/workflows/ci.yml
Our tests were never actually running c17 tests as the condition in the Github workflow was always false. This commit fixes that.
In addition, this commit adds C23 tests (supported starting from clang18 and gcc14).
> CI: Fix c17 tests and add c23 tests

- .github/workflows/hol_light.yml
- README.md
- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/README.md
- proofs/hol_light/arm/mlkem/mlkem_poly_reduce.S
- proofs/hol_light/arm/proofs/mlkem_poly_reduce.ml
- scripts/autogen
* Resolves #839 
This commit adds the HOL-Light functional correctness proof for the AArch64 assembly implementation of poly_reduce().
The proof was contributed by John Harrison.
> HOL-Light: Add correctness proof for AArch64 asm poly_reduce

- examples/monolithic_build/mlkem_native_monobuild.c
- flake.nix
- mlkem/indcpa.c
- mlkem/poly_k.c
- mlkem/poly_k.h
- mlkem/sampling.c
- mlkem/sampling.h
- mlkem/symmetric.h
- mlkem/sys.h
- nix/cbmc/default.nix
- proofs/cbmc/poly_rej_uniform_x4/poly_rej_uniform_x4_harness.c
- test/bench_components_mlkem.c
* Resolves #764 
This PR updates CBMC to include the change from https://github.com/diffblue/cbmc/pull/8603 which weakens the interpretation of `memory_no_alias` (or `__CPROVER_is_fresh`) in function contract applications: Rather than asserting that every pointer featuring in a `memory_no_alis/__CPROVER_is_fresh` clause be in a separate object, pointers can now point to the same object, so long as the slices they represent are disjoint.
This allows us to undo some artificial splitting of 2D arrays into separate objects, which this PR also does.
> CBMC: Pull and test weakening is_fresh in contract applications

- .github/workflows/hol_light.yml
- nix/hol_light/default.nix
- proofs/hol_light/arm/proofs/build-proof.sh
This commit updates the HOL-Light version in the nix shell
to the latest `main` after the merge of the patch
https://github.com/jrh13/hol-light/pull/131
adding support for the HOLLIGHT_LOAD_PATH environment variable.
This removes the need for an ad-hoc patching of inline_load.ml
in our adaptation of build-proof.sh.
> HOL-Light: Update to `main` for support of `HOLLIGHT_LOAD_PATH`

- examples/bring_your_own_fips202/mlkem_native/LICENSE
- examples/custom_backend/mlkem_native/mlkem/LICENSE
- examples/custom_backend/mlkem_native/mlkem/fips202/LICENSE
- integration/liboqs/ML-KEM-1024_META.yml
- integration/liboqs/ML-KEM-512_META.yml
- integration/liboqs/ML-KEM-768_META.yml
- mlkem/LICENSE
- mlkem/fips202/LICENSE
mlkem-native is Apache-2.0 licensed as indicated in the toplevel
LICENSE file. This commit removes multiple outdated CC0 license
notes from the initial import of the reference implementation.
The note on the origin of the FIPS-202 C implementation is still
present in mlkem/fips202/keccakf1600.c.
> Remove outdated CC0 notices

- proofs/cbmc/Makefile.common
Currently CBMC defaults to use gcc. This is a problem when on MacOS, where we default to clang. On these systems our CBMC proofs only work if the user happens to have gcc in their $PATH.
This commit changes the flags for goto-cc to use the compiler set in $CC which is clang on MacOS and gcc on other platforms.
See https://github.com/pq-code-package/mldsa-native/pull/65 Thanks https://github.com/jakemas for reporting this issue!
> CBMC: switch --native-compiler to $(CC) instead of gcc

- .github/workflows/ci.yml
- integration/liboqs/ML-KEM-1024_META.yml
- integration/liboqs/ML-KEM-512_META.yml
- integration/liboqs/ML-KEM-768_META.yml
- integration/liboqs/config_aarch64.h
- integration/liboqs/config_c.h
- integration/liboqs/config_x86_64.h
- integration/liboqs/liboqs-check-filelist.py
- mlkem/config.h
- mlkem/kem.c
- mlkem/randombytes.h
- mlkem/verify.h
- test/break_pct_config.h
- test/custom_randombytes_config.h
- test/custom_zeroize_config.h
- test/no_asm_config.h
Resolves https://github.com/pq-code-package/mlkem-native/issues/640
This commit makes the name of the randombytes function configurable through
the config.h. Thus far, we have been assuming the function to be called
randombytes.
> Allow customization of randombytes function name 

- nix/s2n_bignum/default.nix
Until now, we used @jargh's development branch of s2n-bignum. This was because that branch would contain the ML-KEM and Keccak specs necessary for the ASM functional correctness statements. Another reason was the missing modelling of the EOR instruction.
We have since imported the relevant files directly into mlekm-native's source tree to facilitate standalone auditing, and EOR has been merged into s2n-bignum `main`.
In consequence, all that's neeed is s2n-bignum's `main` infrastructure, and this commit modifies the nix flake accordingly.
> nix: Use `main` branch of s2n-bignum

- .github/workflows/hol_light.yml
- nix/s2n_bignum/default.nix
- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/mlkem/mlkem_poly_basemul_acc_montgomery_cached_k2.S
- proofs/hol_light/arm/mlkem/mlkem_poly_basemul_acc_montgomery_cached_k3.S
- proofs/hol_light/arm/mlkem/mlkem_poly_basemul_acc_montgomery_cached_k4.S
- proofs/hol_light/arm/proofs/mlkem_intt.ml
- proofs/hol_light/arm/proofs/mlkem_ntt.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k2.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k3.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k4.ml
- proofs/hol_light/arm/proofs/mlkem_poly_mulcache_compute.ml
- proofs/hol_light/arm/proofs/mlkem_poly_reduce.ml
- proofs/hol_light/arm/proofs/mlkem_poly_tomont.ml
- proofs/hol_light/arm/proofs/mlkem_utils.ml
- scripts/autogen
This commit adds low-level specifications and functional correctness proofs for the AArch64 polynomial base multiplication routines
- poly_basemul_acc_montgomery_cached_k2
- poly_basemul_acc_montgomery_cached_k3
- poly_basemul_acc_montgomery_cached_k4
The specs are 'low-level' in the sense that they do only provide a description in HOL of what is being computed on raw words; they do, however, not yet give a high-level description of what the computation does mod-3329: A scalar product in `Prod_i F_q[X]/(X^2-zeta_i)`.
The addition of a high-level spec and the connection of low-level and high level spec will be in a future commit.
s2n-bignum is updated to incorporate the recent addition of various long multiplication instructions.
The other ML-KEM arithmetic proofs needed updating since a …
> HOL-Light: Add low-level spec and proof for AArch64 basemul

- .github/workflows/hol_light.yml
- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/README.md
- proofs/hol_light/arm/list_proofs.sh
- scripts/tests
* Resolves #885 
Usage:
- `tests hol_light -p FUNCTION [--verbose]` runs the HOL-Light
proof for FUNCTION
- `tests hol_light -l` lists all available function names for
which a proof is present.
The use of `--verbose` is recommended since HOL-Light proofs
tend to run for a long time, and without `--verbose` one cannot
track progress.
> Add `tests hol_light` command

- README.md
CBMC checks the absence of some classes of undefined behaviour, but not all. Adjust the README accordingly.
* Resolves https://github.com/pq-code-package/mlkem-native/issues/890
> README: Don't claim absolute absence of UB

- .github/workflows/hol_light.yml
- README.md
- proofs/hol_light/arm/README.md
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k2.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k3.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k4.ml
- proofs/hol_light/arm/proofs/mlkem_specs.ml
* Resolves #843 
* Resolves #844
* Resolves #845 
Work by @jargh, originallty #896 
This changes the specification style used in this proof from raw word operations to integer congruences, under some additional input bound assumptions |x0_i|, |x1_i| <= 2^12.
This relies on some improvements to the underlying automation for congruences and bounds, which are updated in line with some similar changes in s2n-bignum.
https://github.com/jargh/s2n-bignum-dev/commit/50e617bce53a737ef11a605b7660dfe2bb97f01d
So far mlkem_poly_basemul_acc_montgomery_cached_k[34] are left as they are, except that the definition of "montred" is further type-constrained to match the definition used in the updated automation, which is in any case the type instance used in the specifications.
> Switch mlkem_poly_basemul_acc_montgomery_cached_* proofs to integer specs

- proofs/cbmc/README.md
This commit adds a link to the list of undefined behaviors caught by CBMC to the CBMC README.
Unfortunately, the HTML page targetted by the link is not rendered, limiting its usefulness. The CBMC team is aware, and we can update the link once there is a rendered version.
* Resolves #891
> CBMC: Add a link to list of undefined behaviors caught by CBMC

- scripts/tests
This commit adds support for the use of wildcard pattern `*` in invocations of `tests cbmc`.
Example:
```
tests cbmc -p "*poly*"
```
This will run all tests for functions containing "poly".
As before, multiple patterns can be provided, e.g.
```
tests cbmc -p "*poly*" "*native"
```
> CBMC tests: Allow wildcard pattern in list of proofs to run

- .github/workflows/ci_ec2_container.yml
- .github/workflows/ci_ec2_reusable.yml
* Resolves https://github.com/pq-code-package/mlkem-native/issues/604
We often need to manually restart the CI because too many EC2 instances are attempted to be started at the same time.
This commit implements a basic retry-once logic in ci_ec2_reusable.yml: Upon failure to start an EC2 instance, it waits ~30s and retries once before failing. A slight random delay is inserted to reduce the likelihood of clashes if multiple jobs fail at the same time.
> CI: Implement simple retry-once logic for starting EC2 runners

- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/indcpa.c
- mlkem/indcpa.h
- mlkem/kem.c
- mlkem/poly_k.c
- mlkem/poly_k.h
- proofs/cbmc/gen_matrix/Makefile
- proofs/cbmc/gen_matrix/gen_matrix_harness.c
- proofs/cbmc/gen_matrix_native/Makefile
- proofs/cbmc/gen_matrix_native/gen_matrix_native_harness.c
- proofs/cbmc/matvec_mul/matvec_mul_harness.c
- proofs/cbmc/polyvec_add/polyvec_add_harness.c
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached/polyvec_basemul_acc_montgomery_cached_harness.c
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached_native/polyvec_basemul_acc_montgomery_cached_native_harness.c
- proofs/cbmc/polyvec_compress_du/polyvec_compress_du_harness.c
- proofs/cbmc/polyvec_decompress_du/polyvec_decompress_du_harness.c
- proofs/cbmc/polyvec_frombytes/polyvec_frombytes_harness.c
- proofs/cbmc/polyvec_invntt_tomont/polyvec_invntt_tomont_harness.c
- proofs/cbmc/polyvec_mulcache_compute/polyvec_mulcache_compute_harness.c
- proofs/cbmc/polyvec_ntt/polyvec_ntt_harness.c
- proofs/cbmc/polyvec_reduce/polyvec_reduce_harness.c
- proofs/cbmc/polyvec_tobytes/polyvec_tobytes_harness.c
- proofs/cbmc/polyvec_tomont/polyvec_tomont_harness.c
- test/bench_components_mlkem.c
* Resolves #893
This commit changes the definition of `mlk_polyvec` from a struct
wrapper `struct { mlk_poly vec[MLKEM_K] }` to a typedef for
`mlk_poly[MLKEM_K]`. Similarly, it introduces `mlk_polymat`
as a typedef for `mlk_poly[MLKEM_K * MLKEM_K]`.
This ensures that when working with polynomial matrices, 
the polynomial entries are consecutive in memory. 
This needs to be assumed for the correctness of `gen_matrix()`.
From all we know, is a theoretical concern that without this
change, compilers would be free to introduce padding into
`mlk_polyvec`, breaking `gen_matrix()`. Yet, the behaviour of
`gen_matrix` is strictly speaking UB, so even if a compiler
does not use padding in `mlk_polyvec`, it is better to change it.
Defining `mlk_polymat` as a typedef for `mlk_poly[MLKEM_K * MLKEM_K]` …
> Define `mlk_polyvec[_mulcache]` as typedef for array

- proofs/cbmc/keccak_squeeze_once/Makefile
- proofs/cbmc/keccak_squeezeblocks/Makefile
- proofs/cbmc/keccak_squeezeblocks_x4/Makefile
- proofs/cbmc/keccakf1600_extract_bytes/Makefile
- proofs/cbmc/keccakf1600_permute/Makefile
- proofs/cbmc/keccakf1600x4_extract_bytes/Makefile
- proofs/cbmc/keccakf1600x4_permute/Makefile
- proofs/cbmc/matvec_mul/Makefile
- proofs/cbmc/poly_permute_bitrev_to_custom/Makefile
- proofs/cbmc/polyvec_add/Makefile
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached/Makefile
- proofs/cbmc/rej_uniform_native/Makefile
* Resolves #913 
We were informed by the CBMC team that the use of the CBMC flag `--arrays-uf-always` should not be beneficial to our proofs.
This commit comments out this CBMC flag.
> CBMC: Remove unused array parameters

- Makefile
- scripts/tests
* Resolves #924 
`tests all` is intended to run all available tests, including ACVP.
Most tests are parametrized by security level and available as separate targets in the Makefile, which `tests` invokes. For example, `make run_func_512` will run functionality tests for ML-KEM-512.
The ACVP tests are currently not parametrized by the level, but monolithic. They are invoked by `make run_acvp`, not `make run_acvp_{512,768,1024}`.
While `tests acvp` got the invocation of ACVP tests via `make` right, the `tests all` variant did not: It would invoke `make run_acvp_XXX`, which would do nothing.
This commit fixes `tests all` to invoke the ACVP tests via `make run_acvp`.
> Fix running of ACVP tests in `tests all`

- examples/monolithic_build_multilevel_native/mlkem_native_all.c
- examples/monolithic_build_multilevel_native/multilevel_config.h
- mlkem/common.h
- mlkem/config.h
* Resolves #926 
Previously, mlkem-native used undocumented configuration options
- MLK_MONOBUILD
- MLK_EXTERNAL_API
to control the qualifiers used for mlkem-native's internal and public API, respectively.
This commit renames those options to
- MLK_INTERNAL_API_QUALIFIER
- MLK_EXTERNAL_API_QUALIFIER
and documents them.
It also modifies the config for the `monolithic_build_multilevel_native` example to test the `static` public API qualifier.
Also, the PR extends `config.h` with documentation for `MLK_CT_TESTING_ENABLED`.
> Config: Document all configuration options

- examples/multilevel_build/Makefile
- examples/multilevel_build/README.md
- examples/multilevel_build_native/Makefile
- examples/multilevel_build_native/README.md
This option was previously used to indicate that the security level (512/768/1024) should be added to the namespace prefix.
Now, the suffixing is automatic based on whether MLK_MULTI_LEVEL_XXX is set. Setting the MLK_NAMESPACE_PREFIX_ADD_LEVEL flag therefore has no effect.
This commit removes / adjusts all uses or documentation of MLK_NAMESPACE_PREFIX_ADD_LEVEL.
> Remove use of MLK_NAMESPACE_PREFIX_ADD_LEVEL

- .github/actions/functest/action.yml
- .github/actions/lint/action.yml
- .github/actions/multi-functest/action.yml
- .github/workflows/bench.yml
This reverts commit 46bac9aa05c4533c6b8400ff976ba2c73be24ee9.
The MacMini was temporarily unavailable yesterday and, hence, got removed. It seems to have recovered by itself. This commit re-adds it.
> Benchmarking: Re-enable MacMini

- .github/workflows/integration-liboqs.yml
This updates liboqs to the most recent commit in main: https://github.com/open-quantum-safe/liboqs/tree/6337a8424deae09aa835ddd920faff83a8f0e1d7
https://github.com/open-quantum-safe/liboqs/pull/2070 reintroduced patching for mlkem-native to expose the keypair_derand functions. This patching is no longer needed since https://github.com/pq-code-package/mlkem-native/pull/886 got merged. This commit hence adds to the liboqs test in CI the removal of the patch in the copy_from_upstream.yml.
> CI: Update liboqs to 0.13.0-rc1

- mlkem/sampling.c
It was observed in https://github.com/pq-code-package/mldsa-native/pull/86 that
invariant(ctr > 0 ==> array_bound(r, 0, ctr, 0, MLKEM_Q))) can be simplified to
invariant(array_bound(r, 0, ctr, 0, MLKEM_Q)))
as
invariant(array_bound(r, 0, 0, 0, MLKEM_Q))) is just true.
This commit simplifies the one place in mlkem-native where we had a similar implicatation.
**Summary**:
Provide a brief summary of your changes.
**Steps**:
If your pull request consists of multiple sequential changes, please describe them here:
**Do you expect this change to impact performance**: Yes/No
> CBMC: Simplify rej_uniform_scalar proof

- mlkem/kem.c
- mlkem/kem.h
- mlkem/mlkem_native.h
* Resolves #944 
keypair_derand requires 2 * MLKEM_SYMBYTES bytes of randomness. So far the function
signature took a const uint8_t *coins.
This commit changfes the function signature to make the size explicit:
const uint8_t coins[2 * MLKEM_SYMBYTES].
This is in line with the enc_derand function and should reduce the risk of
misuse.
Based on #942.
> keypair_derand: *coins -> coins[2 * MLKEM_SYMBYTES] 

- .clang-format
- dev/x86_64/src/rej_uniform_avx2.c
- examples/bring_your_own_fips202/custom_fips202/tiny_sha3/sha3.c
- examples/bring_your_own_fips202/main.c
- examples/custom_backend/main.c
- examples/custom_backend/mlkem_native/mlkem/fips202/native/custom/src/sha3.c
- examples/mlkem_native_as_code_package/main.c
- examples/monolithic_build/main.c
- examples/monolithic_build_multilevel/main.c
- examples/monolithic_build_multilevel_native/main.c
- examples/multilevel_build/main.c
- examples/multilevel_build_native/main.c
- mlkem/debug.c
- mlkem/native/x86_64/src/rej_uniform_avx2.c
- test/bench_mlkem.c
Fixes #946 
1. Adds "InsertBraces: true" to .clang-format file
2. autogen
3. format
4. lint
All tests OK.
> Add and apply "InsertBraces" option for clang-format

- .github/actions/functest/action.yml
- .github/workflows/base.yml
- scripts/check-namespace
- scripts/tests
* Resolves #372 
This commit adds the parameter --check-namespace to `tests func`. It is false by default. If true, `scripts/check-namespace` is called after both the C and the native build to check namespacing.
Previously, a call to `check-namespace` after `tests func` would only apply to the final binary produced by `tests func`, which was the native one.
> tests: Integrate namespace check into `tests func`

- dev/aarch64_opt/src/README.md
* Resolves #951 
The nix shell for mlkem-native now includes a working setup. This commit adjusts dev/aarch64_opt/src/README.md accordingly.
> Adjust SLOTHY README

- proofs/cbmc/proof_guide.md
The macro `array_bound(arr, idx_low, idx_high, value_low, value_high)` exands to:
```  __CPROVER_forall                                                     \
{                                                                    \
unsigned qvar;                                                     \
((qvar_lb) <= (qvar) && (qvar) < (qvar_ub)) ==>                    \
(((int)(value_lb) <= ((array_var)[(qvar)])) &&		       \
(((array_var)[(qvar)]) < (int)(value_ub)))		       \
}
```
which asserts that the array `arr` elements are within the range `[value_low, ..., value_high - 1]`, with inclusinve lower bound `value_low` and  exclusive boud `value_high`.
**Summary**:
Provide a brief summary of your changes.
**Steps**:
If your pull request consists of multiple sequential changes, please …
> Update array_bound macro description in proof_guide.md

- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/common.h
For readers trying to see through the naming indirection using MLK_NAMESPACE(...) and MLK_NAMESPACE_K(...), the previous definitions
```c
#define MLK_NAMESPACE(s) \
MLK_CONCAT(MLK_CONCAT(MLK_CONFIG_NAMESPACE_PREFIX, _), s)
#define MLK_NAMESPACE_K(s) \
MLK_CONCAT(MLK_CONCAT(MLK_ADD_PARAM_SET(MLK_CONFIG_NAMESPACE_PREFIX), _), s)
```
are a handful.
This commit keeps the functionality as-is, but introduces internal abbreviations for the level'ed and underscore'ed prefix, so that the toplevel definitions for MLK_NAMESPACE[_K] turn into the more expectable
```c
#define MLK_NAMESPACE(s) MLK_CONCAT(MLK_NAMESPACE_PREFIX, s)
#define MLK_NAMESPACE_K(s) MLK_CONCAT(MLK_NAMESPACE_PREFIX_K, s)
```
Also, a comment is added with an example.
> Document MLK_NAMESPACE and MLK_NAMESPACE_K macros

- .github/actions/setup-aws-lc/action.yml
- .github/workflows/all.yml
- .github/workflows/integration-awslc.yml
This commit extends the CI with an integration test for AWS-LC.
The CI checks that mlkem-native successfully integrates into
AWS-LC by building and running basic tests of AWS-LC in FIPS
and non-FIPS mode.
We test both against a fixed commit and main. Testing against a
fixed known-good commit in AWS-LC means we note if we break the
integration. Testing against main means we note if a change in
AWS-LC breaks the integration. The latter is out of our control,
and we may need to temporarily ignore failures, but we should
be aware.
> Add AWS-LC integration test

- .github/workflows/ci_ec2_reusable.yml
- scripts/autogen
* Resolves #950
This commit adds a `--slothy` argument to the `autogen` script. When provided, SLOTHY will be run to re-run all SLOTHY optimizations.
This is done prior to other tasks of `autogen` such as simplifying the optimized files and copying them into the main source tree. Thus, after a change to the clean files, `autogen --slothy` should be all that's needed to update the tree.
One can also specify individual functions to be re-optimized by passing function names to `--slothy`. For example
```
autogen --slothy ntt poly_reduce_asm
```
would re-generate `dev/aarch64_opt/src/{ntt, poly_reduce_asm}.S`.
The CI job for SLOTHY is adjusted to use `autogen --slothy` instead of `make + autogen`.
> autogen: Add `--slothy` argument

- mlkem/cbmc.h
The documentation previously wrongly stated that the absolute bound is inclusive. Instead, it's exclusive. This commit fixes the documentation accordingly.
> CBMC: Fix documentation of `array_abs_bound`

- test/mk/rules.mk
test/mk/rules.mk includes a check for duplicated symbols when building archive files.
The implementation of this check is specific to the toolchain: We already distinguish Darwin vs. non-Darwin, and exclude the check when running with scan-build.
It turns out that the check does also not work with zig, as it uses unsupported linker arguments.
Instead of attempting to make the check more portable, this commit removes it altogether. This is OK because we anyway build various test binaries based on the generated libraries, and the build for those binaries would fail if there were duplicated symbols.
> Makefile: Remove duplicated symbol check

- .github/workflows/ci.yml
- flake.nix
This PR adds nix shells for zig and adds zig compiler tests to the CI.
* Based on #968 
* Resolves #910
> Add nix shells for zig and add zig tests to CI

- README.md
This commit shortens the README, in particular removing the full list of AArch64 assembly routines which are covered by the HOL-Light proofs.
> README: Simplify and shorten

- RELICENSE.md
This PR adds a RELICENSE file. The purpose of this file is to gather consent from mlkem-native contributors that their contributions may be relicensed as `Apache-2.0 OR MIT OR ISC`.
The relicensing itself is planned to be carried out once all contributors have added their names to that file.
Contributors agreeing to the relicensing should push a separate commit adding their name to `RELICENSE`.
> Contributor's agreement to relicensing mlkem-native under `Apache-2.0 OR ISC OR MIT`

- mlkem/fips202/keccakf1600.c
- Namespace NROUNDS and ROL macro
- Fix spacing
- Remove #undef for non-existing `round` macro
> FIPS202: Minor improvements in fips202.c

- .github/workflows/all.yml
- .github/workflows/nix.yml
This commit moves the nix workflow nix.yml into all.yml
and triggers the extended tests ci.yml only once the nix
workflow completes. This prevents concurrent rebuilding
of the expensive ci-cross shell. With the current patch,
the ci-cross shell is built and cached once in nix.yml,
and can then be reused by ci.yml.
Also, the dependency of the nix development tests on the
nix cache build for ci-cross is unnecessary and removed.
> CI: Run extended tests only after optional nix cache rebuild

- proofs/cbmc/lib/summarize.py
CBMC-Starter_Kit PR#207 (https://github.com/model-checking/cbmc-starter-kit/pull/207)
fixed a defect where the total number of proofs reported is one too big when
cbmc-run-proofs.py --summarize is run.
This PR imports that fix into the mlkem-native repo.
Before, running `./run-cbmc-proofs.py --summarize --no-coverage -p fqmul` resulted in
```
| Status  | Count |
|---------|-------|
| Success | 2     |
| Proof     | Status  | Duration (in s) |
|-----------|---------|-----------------|
| mlk_fqmul | Success | 5               |
```
With this fix:
```
| Status  | Count |
|---------|-------|
| Success | 1     |
| Proof     | Status  | Duration (in s) |
|-----------|---------|-----------------|
| mlk_fqmul | Success | 5               |
```
> Fix reporting of total proof count from upstream cbmc-starter-kit repo

- nix/cbmc/default.nix
Update to https://github.com/diffblue/cbmc/releases/tag/cbmc-6.6.0
> CBMC: Update to v6.6.0

- dev/aarch64_clean/src/rej_uniform_asm.S
- dev/aarch64_opt/src/rej_uniform_asm.S
- mlkem/native/aarch64/src/rej_uniform_asm.S
The AArch64 rejection sampling routine samples data into a temporary stack buffer. This stack buffer is copied in full to the output buffer at the end of the routine, regardless of how many bytes were actually sampled. This leaks parts of the original stack values to the output buffer. While the call-site eventually fills the output buffer fully, thereby overwriting the temporary values copied from the stack, this temporary leakage is still undesirable and should be avoided.
This commit avoids unnecessarily leaking uninitialized stack values by explicitly zeroing the temporary stack buffer prior to starting the sampling.
> AArch64: Zeroize rejection sampling stack buffer

- .github/workflows/ci_ec2_reusable.yml
- dev/fips202/aarch64/src/Makefile
- dev/fips202/aarch64_symbolic/keccak_f1600_x1_scalar_symbolic.S
- nix/slothy/default.nix
- scripts/autogen
* Based on #1008
* Resolves #1005 
A major challenge in developing fast assembly for Keccka-F1600 is
register pressure: The Keccak-F1600 state alone occupies 25 registers,
leaving only 5 for the remaining computation.
The AArch64 scalar assembly for Keccak-F1600 used in mlkem-native
is automatically derived from _symbolic_ assembly using the SLOTHY
superoptimizer: What was written by hand is a symbolic version of
the assembly using symbolic placeholders for registers, while the
concrete allocation was left to SLOTHY. Previously, however, only
the final assembly was part of the mlkem-native repository, lacking
both the symbolic versions and the instructions to run SLOTHY.
This negatively impacts transparency, reproducibility, and maintainability
of the library.
This commit adds the …
> Add symbolic assembly for v8-A scalar Keccak ASM

- nix/slothy/default.nix
This pulls in https://github.com/slothy-optimizer/slothy/pull/207 adding support for `ldr <Xd>, [<Xa>, <Xb>, LSL <imm>]`. This is needed for running SLOTHY on the Keccak assembly used in mlkem-native.
> nix: Update SLOTHY

- .github/workflows/hol_light.yml
- dev/aarch64_clean/src/arith_native_aarch64.h
- dev/aarch64_clean/src/rej_uniform_asm.S
- dev/aarch64_opt/src/arith_native_aarch64.h
- dev/aarch64_opt/src/rej_uniform_asm.S
- mlkem/native/aarch64/src/arith_native_aarch64.h
- nix/s2n_bignum/default.nix
- proofs/hol_light/arm/Makefile
- proofs/hol_light/arm/mlkem/mlkem_rej_uniform.S
- proofs/hol_light/arm/proofs/mlkem_rej_uniform.ml
- scripts/autogen
* Resolves #841 
This commit imports John Harrison's HOL-Light specification & proof of functional correctness for the AArch64 Neon implementation of the rejection sampling used in mlkem-native.
Since not all instructions needed in the code are part of the s2n-bignum repository yet, John's development branch of s2n-bignum is used for the time being.
Also, various instructions have been changed to use the X-form rather than the W-form of general purpose registers. This is to work around unmodelled AArch64 instructions in s2n-bignum.
For all the complexity in the AArch64 assembly, the functional specification for rej_uniform is remarkably simple: It's effectively just a filter by `(<) 3329`.
> HOL-Light: Add functional correctness proof for rej_uniform

- CODEOWNERS
- META.sh
- nix/cbmc/0001-Do-not-download-sources-in-cmake.patch
- proofs/cbmc/.gitignore
Two files were erroneously and unintentionally left out of the relicensing from Apache-2.0 to Apache-2.0 OR ISC OR MIT. This commit fixes that.
See RELICENSE.md for the relicensing consent.
> Fix relicensing gap

- dev/aarch64_clean/src/arith_native_aarch64.h
- dev/aarch64_opt/src/arith_native_aarch64.h
- mlkem/common.h
- mlkem/native/aarch64/src/arith_native_aarch64.h
- proofs/cbmc/rej_uniform_native_aarch64/Makefile
- proofs/cbmc/rej_uniform_native_aarch64/rej_uniform_native_aarch64_harness.c
- proofs/hol_light/arm/proofs/mlkem_rej_uniform.ml
* Build on  #1026 
* Part of #1025 
This commit shows that the AArch64 implementation of `rej_uniform_native`
satisfies its CBMC spec atop the HOL-Light spec for the underlying
assembly routine `rej_uniform_asm`.
More precisely, we translate relevant aspects of the HOL-Light spec
for `rej_uniform_asm` to a CBMC spec, and then show that assuming this
spec, the AArch64 implementation for `rej_uniform_native` upholds the
contract defined in `native/api.h`.
> CBMC: Prove AArch64 native API for rej_uniform atop HOL-Light spec

- mlkem/common.h
The backend API `native/api.h` only declares backend functions for which the relevant `MLK_USE_XXX` macro has been set. Those macros are set by the backend header, which hence must be included _before_ inclusion of `native/api.h`. The code in `common.h` which includes both `native/api.h` and the backend header says as much, but then plainly does the opposite: It includes `native/api.h` first, then the backend header. This renders the API consistency checks useless.
This commit fixes this by moving the inclusion of the backend headers ahead of the backend API headers.
> Fix API consistency check for backends

- dev/aarch64_clean/src/arith_native_aarch64.h
- dev/aarch64_opt/src/arith_native_aarch64.h
- mlkem/native/aarch64/src/arith_native_aarch64.h
- mlkem/native/api.h
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k2_native_aarch64/Makefile
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k2_native_aarch64/polyvec_basemul_acc_montgomery_cached_k2_native_aarch64_harness.c
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k3_native_aarch64/Makefile
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k3_native_aarch64/polyvec_basemul_acc_montgomery_cached_k3_native_aarch64_harness.c
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k4_native_aarch64/Makefile
- proofs/cbmc/polyvec_basemul_acc_montgomery_cached_k4_native_aarch64/polyvec_basemul_acc_montgomery_cached_k4_native_aarch64_harness.c
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k2.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k3.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k4.ml
* Part of #1025
This commit shows that the AArch64 implementations of `polyvec_basemul_acc_montgomery_cached_k{2,3,4}_native` satisfiy their CBMC spec atop the HOL-Light spec for the underlying assembly routines.
More precisely, we translate relevant aspects of the HOL-Light specs to CBMC specs, and then show that assuming those specs, the AArch64 implementations uphold their CBMC contracts defined in `native/api.h`.
> CBMC: Prove AArch64 native API for basemul atop HOL-Light spec

- dev/aarch64_clean/src/arith_native_aarch64.h
- dev/aarch64_opt/src/arith_native_aarch64.h
- mlkem/native/aarch64/src/arith_native_aarch64.h
- mlkem/native/api.h
- mlkem/poly.c
- proofs/cbmc/poly_mulcache_compute_native_aarch64/Makefile
- proofs/cbmc/poly_mulcache_compute_native_aarch64/poly_mulcache_compute_native_aarch64_harness.c
- proofs/cbmc/poly_reduce_native_aarch64/Makefile
- proofs/cbmc/poly_reduce_native_aarch64/poly_reduce_native_aarch64_harness.c
- proofs/hol_light/arm/proofs/mlkem_intt.ml
- proofs/hol_light/arm/proofs/mlkem_ntt.ml
- proofs/hol_light/arm/proofs/mlkem_poly_mulcache_compute.ml
- proofs/hol_light/arm/proofs/mlkem_poly_reduce.ml
- proofs/hol_light/arm/proofs/mlkem_poly_tobytes.ml
- proofs/hol_light/arm/proofs/mlkem_rej_uniform.ml
This commit shows that the AArch64 implementations of `poly_reduce_native` and `poly_mulcache_compute_native` satisfiy their CBMC spec atop the HOL-Light spec for the underlying assembly routines.
More precisely, we translate relevant aspects of the HOL-Light specs to CBMC specs, and then show that assuming those specs, the AArch64 implementations uphold their CBMC contracts defined in native/api.h.
> CBMC: Prove AArch64 native API for poly_reduce, poly_mulcache_compute atop HOL-Light spec

- dev/fips202/aarch64/src/fips202_native_aarch64.h
- dev/fips202/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm.S
- dev/fips202/aarch64/x4_v8a_scalar.h
- dev/fips202/aarch64_symbolic/keccak_f1600_x4_v8a_scalar_hybrid_clean.S
- examples/monolithic_build/mlkem_native_monobuild.c
- mlkem/fips202/native/aarch64/src/fips202_native_aarch64.h
- mlkem/fips202/native/aarch64/src/keccak_f1600_x4_v8a_scalar_hybrid_asm.S
- mlkem/fips202/native/aarch64/x4_v8a_scalar.h
- proofs/cbmc/keccak_f1600_x1_native_aarch64/Makefile
- proofs/cbmc/keccak_f1600_x1_native_aarch64/keccak_f1600_x1_native_aarch64_harness.c
- proofs/cbmc/keccak_f1600_x1_native_aarch64_v84a/Makefile
- proofs/cbmc/keccak_f1600_x1_native_aarch64_v84a/keccak_f1600_x1_native_aarch64_v84a_harness.c
- proofs/cbmc/keccak_f1600_x2_native_aarch64_v84a/Makefile
- proofs/cbmc/keccak_f1600_x2_native_aarch64_v84a/keccak_f1600_x2_native_aarch64_v84a_harness.c
- proofs/cbmc/keccak_f1600_x4_native_aarch64_scalar_v8a_hybrid/Makefile
- proofs/cbmc/keccak_f1600_x4_native_aarch64_scalar_v8a_hybrid/keccak_f1600_x4_native_aarch64_scalar_v8a_hybrid_harness.c
- proofs/cbmc/keccak_f1600_x4_native_aarch64_scalar_v8a_v84a_hybrid/Makefile
- proofs/cbmc/keccak_f1600_x4_native_aarch64_scalar_v8a_v84a_hybrid/keccak_f1600_x4_native_aarch64_scalar_v8a_v84a_hybrid_harness.c
- proofs/hol_light/arm/mlkem/keccak_f1600_x4_v8a_scalar.S
- scripts/check-contracts
- Resolves https://github.com/pq-code-package/mlkem-native/issues/1025
This PR proves the contracts of the native Keccak API based on the AArch64 backend which closely resemble the HOL-Light specifications. This completes #1025. 
It also removes the signatures of the un-used functions ` mlk_keccak_f1600_x2_v8a_v84a_asm_hybrid` and `mlk_keccak_f1600_x4_scalar_v84a_asm_hybrid`. 
Furthermore it renames `keccak_f1600_x4_scalar_v8a_asm_hybrid` to `keccak_f1600_x4_scalar_v8a_hybrid_asm` to be consistent with the other function names.
> CBMC: Prove AArch64 Keccak native API atop HOL-Light specs

- .github/actions/setup-nix/action.yml
**Summary**:
This PR is currently a work in progress. It aims to fix the CI error occurring in the `nix-post-check` step.
**Fixes**: #1033
the CI showing error about action step: nix-post-check
> Fixes #1033: CI step nix-post-check fails

- proofs/cbmc/poly_permute_bitrev_to_custom/poly_permute_bitrev_to_custom_harness.c
- proofs/cbmc/poly_rej_uniform_x4/poly_rej_uniform_x4_harness.c
When CBMC checks a function contract, it seems that the preconditions set out in the contract are overlayed by the context set out in the harness. For example, if a function takes a pointer to `foo`, and the harness passes `&f` for `foo f`, then the function would never be evaluated for the possibility of an invalid pointer being passed. For that reason, harnesses must be as minimal as possible, merely declaring uninitialized variables of the expected type and calling the function under proof.
This commit fixes a few instances in mlkem-native where this was not yet the case.
> CBMC: Don't declare structures in harnesses

- .github/workflows/all.yml
- .github/workflows/ci.yml
- flake.lock
- flake.nix
- nix/cbmc/0001-Do-not-download-sources-in-cmake.patch
- nix/cbmc/0002-Do-not-download-sources-in-cmake.patch
- nix/cbmc/default.nix
- nix/slothy/default.nix
- nix/util.nix
- Resolves #1022
[NixOS 25.05 ](https://nixos.org/blog/announcements/2025/nixos-2505/) has been released yesterday bringing various version updates also to nixpkgs.
Notable changes for us are: 
- Default clang/llvm is now 19; we switch to the default in the core shells
- Default gcc is now 14; we switch to it in the core shells
- gcc 7, zig_0_10, zig_0_11 are not longer supported in 25.05; we instead
take it from nixpkgs 24.05
- zig_0_14 has been added; we test in CI now as well
- Unicorn and protobuf versions are now compatible with SLOTHY simpliying the
build
- z3 has been updated to 4.15.0; we take it from 25.05
- clang_20, bitwuzla, qemu now have suitable versions in 25.05; we no longer
need to take them from unstable.
- The upstream CBMC nixpkgs build (6.4.1) uses 3 patches instead …
> Update to nixpkgs 25.05

- RELICENSE.md
This PR adds to RELICENSE.md a section where copyright holders of the AArch64 assembly in mlkem-native can give consent to the relicensing under Apache-2.0 OR ISC OR MIT.
> Copyright holder's agreement to relicensing AArch64 assembly under Apache-2.0 OR ISC OR MIT 

- .github/workflows/ci.yml
- dev/aarch64_clean/meta.h
- dev/aarch64_opt/meta.h
- mlkem/native/aarch64/meta.h
Previously, we only ran compiler tests with -O3.
> CI: Run compiler tests with -O0, -Os, and -O3

- examples/monolithic_build/mlkem_native_monobuild.c
- examples/monolithic_build_multilevel_native/README.md
- examples/monolithic_build_multilevel_native/mlkem_native_all.c
- mlkem/config.h
- scripts/autogen
Previously, we had a various configurations options
MLK_CONFIG_MONOBUILD_XXX
which would control what the SCU file mlkem_native_monobuild.c does.
However, most of those options are actually already covered by the mlkem-native configuration, which the SCU file must have access to anyway. This is different from the configuration options for mlkem_native.h, which may be used in a context where the original sources, including the full configuration, are not present -- in this case, separate configuration options are required.
For the SCU file, however, the following monobuild configuration options are subsumed by configuration options, and can just be suitably renamed:
- MLK_CONFIG_MONOBUILD_WITH_NATIVE_ARITH -> MLK_CONFIG_USE_NATIVE_BACKEND_ARITH
- MLK_CONFIG_MONOBUILD_WITH_NATIVE_FIPS202 -> …
> Remove unnecessary MLK_CONFIG_MONOBUILD_XXX configuration options

- examples/monolithic_build_multilevel_native/Makefile
- examples/monolithic_build_multilevel_native/mlkem_native_monobuild.S
- scripts/autogen
* Builds on #1067 
* Builds on #1063
Analogous to the SCU file examples/monolithic_build/mlkem_native_monobuild.c,
this commit extends autogen to emit a monolithic mlkem_native_monobuild.S
in the monolithic_build_multilevel_native example. This demonstrates that
all ASM files are concatenable into a single assembly unit. This relies on
the prework undefining register aliases, assembly directives, and making
ASM labels unique.
> autogen: Add monolithic assembly file

- integration/awslc/awslc.patch
This commit modifies the AWS-LC importer patch to that the mlkem/src/* files are imported into `crypto/fipsmodule/ml_kem/mlkem/*` rather than `crypto/fipsmodule/ml_kem/mlkem/src/*`. The SCU file mlkem_native.c was already part of `crypto/fipsmodule/ml_kem/mlkem/*`,] and `mlkem_native.S` and `mlkem_native.h` are not used in the AWS-LC import for the time being.
> AWS-LC integration: Keep flat file structure

- .github/workflows/ci.yml
- flake.nix
zig0.11 seems to have dropped from the nix binary cache for MacOS. This means it has to be built from source in the CI significanlty slowing down CI.
Note that both zig 0.10 and zig 0.11 have been dropped in nixpkgs 25.05, so it is expected that it is eventually dropped from the cache. This commit removes zig 0.11 and the even older zig 0.10.
> Nix: Remove zig 0.10 and zig 0.11 shells and CI

- .github/workflows/all.yml
- .github/workflows/integration-liboqs.yml
- Updates liboqs to latest commit from main branch (b5d3dac)
- Updates AWS-LC to latest release v1.54.0 (8568a08)
- Adds version comments for better tracking
> Update liboqs and AWS-LC dependencies

- .github/actions/functest/action.yml
- .github/actions/multi-functest/action.yml
- .github/workflows/ci.yml
- Makefile
- scripts/stack
- scripts/tests
- test/mk/components.mk
- test/test_stack.c
Implements static and dynamic stack analysis using GCC -fstack-usage and valgrind massif.
Usage:
make stack_512
make run_stack_512
or
./scripts/tests stack [--peak-only --dump-massif]
> tests: Support stack usage measurement

- .github/workflows/ci.yml
- .github/workflows/integration-awslc.yml
- BIBLIOGRAPHY.md
- STDLIB.md
- dev/x86_64/src/compress_avx2.c
- integration/aws-lc/add-custom-stdlib.patch
- mlkem/mlkem_native.S
- mlkem/mlkem_native.c
- mlkem/src/common.h
- mlkem/src/fips202/fips202x4.c
- mlkem/src/indcpa.c
- mlkem/src/kem.c
- mlkem/src/native/x86_64/src/compress_avx2.c
- mlkem/src/poly_k.c
- mlkem/src/verify.h
- test/custom_memcpy_config.h
- test/custom_memset_config.h
- test/custom_stdlib_config.h
This PR extends the config to allow customization of
mlkem-native's dependencies on the stdlib: memset and memcpy.
It follows the same mechanism used for zeroize and randombytes.
Custom test configs are added illustrating how the new options work,
and they are exercised in CI.
Further, STDLIB.md is added, documenting the dependencies on the stdlib
and pointing to the customization mechanism.
AWS-LC's mlkem-native config is patched to make use of the customization,
redirecting memset/memcpy to OPENSSL_xxx.
* Resolves #550
> Allow customization of memcpy and memset

- .github/actions/functest/action.yml
- .github/actions/multi-functest/action.yml
- .github/workflows/ci.yml
- scripts/tests
This commit extends `tests` to support `tests --aarch64-fips202-backend` for easier testing of the various FIPS202 AArch64 backends. The CI is adjusted to make use of this option.
Fixes #1009
> tests: Add `--aarch64-fips202-backend` choosing arm fips202 backend

- proofs/cbmc/proof_guide.md
- mlk_poly_tobytes -> poly_tobytes
- poly_tobytes has moved from poly.* to compress.*
Found by @yogappu
> CBMC: Fix mistakes in proof guide

- mlkem/src/indcpa.c
- mlkem/src/sampling.c
- mlkem/src/sampling.h
- proofs/cbmc/poly_rej_uniform_x4/poly_rej_uniform_x4_harness.c
- test/bench_components_mlkem.c
Simplify gen_matrix() and poly_rej_uniform_x4()
1. Simplify poly_rej_uniform_x4() API to explicitly take 4 objects to write, rather than a slice of a larger array.
2. Update gen_matrix() in light of that.
3. Update test/bench_components_mlkem.c
Proof time of poly_rej_uniform_x4() reduces from 20s to 9s on Apple M1.
Proof time of gen_matrix() unchanged at 8s
Runtime performance benchmarks show no significant change.
> Simplify gen_matrix() and poly_rej_uniform_x4()

- proofs/cbmc/README.md
- proofs/cbmc/proof_guide.md
We have seen numerous people trying to reproduce CBMC proofs with tool versions not installed via nix. The results are mixed, but mostly a disaster.
This commit clarifies this in the README adding explicit installation instructions and stressing that you _cannot_ expect to use any version and proofs to work just fine.
> Update CBMC proof guide and README to include installation instructions

- Makefile
- examples/basic/Makefile
- examples/bring_your_own_fips202/Makefile
- examples/custom_backend/Makefile
- examples/monolithic_build/Makefile
- examples/monolithic_build_multilevel/Makefile
- examples/monolithic_build_multilevel_native/Makefile
- examples/monolithic_build_native/Makefile
- examples/multilevel_build/Makefile
- examples/multilevel_build_native/Makefile
- scripts/tests
- Resolves #888 
- Resolves #889 
This PR mean to add the code size measurement for each cycle benchmark for MLKEM binaries.
We adds the ability to measure code size for tests and examples:
- For tests: run `./scripts/tests size`
- For examples: run `./scripts/tests examples -l <example_name> --verbose`
The function is implemented using the `size` command:
- Adds the size command and corresponding Makefile configuration for both tests and each example.
- Filter out empty size results to keep the output clean.
- Sort results in descending order by size to enhance readability.
This enhancement helps track the binary size alongside performance metrics to better understand trade-offs.
> Measure code-size

- .github/actions/ct-test/action.yml
- Makefile
- examples/monolithic_build_multilevel_native/Makefile
- examples/multilevel_build_native/Makefile
- test/mk/auto.mk
- test/mk/compiler.mk
- test/mk/config.mk
> Makefile: Add compile-time compiler+host platform feature detection

- integration/liboqs/ML-KEM-1024_META.yml
- integration/liboqs/ML-KEM-512_META.yml
- integration/liboqs/ML-KEM-768_META.yml
Updates liboqs integration YML files to keep in sync with [open-quantum-safe/liboqs#2221](https://github.com/open-quantum-safe/liboqs/pull/2221) regarding `encaps_derand` procedures
> Expose encaps_derand in liboqs integration YML

- .github/actions/setup-brew/action.yml
CI sometimes fails on MacOS when trying to run `brew install cmake` because `cmake` has already been installed from a separate brew tap.
This commit attempts to resolve this by modifying the setup-brew CI action to only run `brew install` if `brew list` indicates that the target package is not yet installed.
> CI: Try `brew install` only if package not yet installed

- mlkem/src/kem.h
- proofs/cbmc/crypto_kem_check_pk/Makefile
- proofs/cbmc/crypto_kem_check_pk/crypto_kem_check_pk_harness.c
- proofs/cbmc/crypto_kem_check_sk/Makefile
- proofs/cbmc/crypto_kem_check_sk/crypto_kem_check_sk_harness.c
- proofs/cbmc/crypto_kem_dec/Makefile
- Resolved: #1172 
- This PR add the CMBC proof for the `crypto_kem_check_sk`, `crypto_kem_check_pk`
> CBMC: Add proof for `crypto_kem_check_sk`, `crypto_kem_check_pk`

- dev/x86_64/src/nttfrombytes.S
- dev/x86_64/src/ntttobytes.S
- dev/x86_64/src/nttunpack.S
- dev/x86_64/src/reduce.S
- dev/x86_64/src/tomont.S
- mlkem/src/native/x86_64/src/nttfrombytes.S
- mlkem/src/native/x86_64/src/ntttobytes.S
- mlkem/src/native/x86_64/src/nttunpack.S
- mlkem/src/native/x86_64/src/reduce.S
- mlkem/src/native/x86_64/src/tomont.S
Rewrite the x86 assembly functions to use macros instead of local function calls.
This significantly simplifies the formal verification effort.
> Use asm macros instead of local function calls in x86 asm

- flake.nix
- nix/cbmc/default.nix
- Resolves #1122 
- This PR update the bitwuzla form 0.7.0 to 0.8.2(unstable)
> bitwuzla: update the bitwuzla version from 0.7.0 to 0.8.2 in nix

- proofs/cbmc/Makefile.common
- proofs/cbmc/proof_guide.md
When investigating and/or debugging CBMC proof failures, it can be very useful to generate the SMT file(s), but without actually running the provers. It's also useful to generate the SMT files for one or all of Z3, Bitwuzla, or CVC5 for comparison.
Update Makefile.common for CBMC so that for a function x, new Makefile targets are:
smt: generates gotos/x.smt2 for prover (z3, bitwuzla, or cvc5) chosen by the user
in the specific Makefile for that function.
smtz: generates gotos/x.smtz, but always for Z3, ignoring the choice in the Makefile
smtb: generates gotos/x.smtb, but always for Bitwuzla, ignoring the choice in the Makefile
smtc: generates gotos/x.smtc, but always for cvc5, ignoring the choice in the Makefile
smtall: generates all three targets smtz, smtb, smtc as above.
> Add make targets for building SMT files.

- proofs/cbmc/Makefile.common
Adds reporting of location and name of generated SMT file(s)
Updates Makefile.common to report the full pathname to the generated SMT file(s)
for each of the smt, smtz, smtb, smtc, and smtall targets.
> Add reporting of location and name of generated SMT file(s)

- BIBLIOGRAPHY.md
- BIBLIOGRAPHY.yml
- mlkem/src/fips202/fips202.c
- mlkem/src/fips202/keccakf1600.c
- This is a samll fix about bibliography, this PR add all authors for `mupq` instead of just use the  `et.al`
- see https://github.com/pq-code-package/mldsa-native/pull/482#discussion_r2381480490
> Fix bibliography, add all authors for mupq

- .github/workflows/base.yml
- .github/workflows/ci.yml
- .github/workflows/integration-awslc.yml
- Resolves: #1213 
- This PR switch the macos (x86_64) runners from `macos-13` to `macos-15-intel`, due to the `macos-13` runners will not be supported anymore from December 3, 2025, check the following link:
- https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
> Switch macos-13 to macos-15-intel

- proofs/hol_light/arm/proofs/keccak_f1600_x1_scalar.ml
- proofs/hol_light/arm/proofs/keccak_f1600_x1_v84a.ml
- proofs/hol_light/arm/proofs/keccak_f1600_x2_v84a.ml
- proofs/hol_light/arm/proofs/keccak_f1600_x4_v8a_scalar.ml
- proofs/hol_light/arm/proofs/keccak_f1600_x4_v8a_v84a_scalar.ml
- proofs/hol_light/arm/proofs/mlkem_intt.ml
- proofs/hol_light/arm/proofs/mlkem_ntt.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k2.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k3.ml
- proofs/hol_light/arm/proofs/mlkem_poly_basemul_acc_montgomery_cached_k4.ml
- proofs/hol_light/arm/proofs/mlkem_poly_mulcache_compute.ml
- proofs/hol_light/arm/proofs/mlkem_poly_reduce.ml
- proofs/hol_light/arm/proofs/mlkem_poly_tobytes.ml
- proofs/hol_light/arm/proofs/mlkem_poly_tomont.ml
- proofs/hol_light/arm/proofs/mlkem_rej_uniform.ml
* Resolves #1217 
Previously, the HOL-Light proof scripts contained various hardcoded constants related to the length of the code under proof, as well as the lengths of preamble and postamble (stack spill and restore).
This commit replaces those hardcoded numerals with symbolic definitions. As a result, SLOTHY re-optimization should now no longer require a proof script change beyond the update of the byte code which is done by `autogen` already.
> HOL-Light: Avoid hardcoded lengths in HOL-Light proof scripts

- .github/actions/config-variations/action.yml
- .github/workflows/integration-liboqs.yml
- integration/liboqs/config_aarch64.h
- integration/liboqs/config_c.h
- integration/liboqs/config_x86_64.h
Currently our liboqs integration tests are skipping the oqs constant time tests. There is no reason to skip those.
This commit adds
-DCMAKE_BUILD_TYPE=Debug -DOQS_ENABLE_TEST_CONSTANT_TIME=ON which enables the constant-time tests.
- Resolves https://github.com/pq-code-package/mlkem-native/issues/1199
> OQS CI: Enable constant-time tests
